### ISSUE TITLE
404 redirects with hugo server fail in multilingual mode on Windows

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10314]
<details>
<summary>structure</summary>

```text
config/
├── _default/
│   └── config.toml
└── development/
    └── server.toml
content/
├── en/
│   └── _index.md
└── es/
    └── _index.md
layouts/
├── _default/
│   ├── baseof.html
│   ├── home.html
│   ├── list.html
│   └── single.html
└── 404.html
```
</details>

<details>
<summary>config\_default\config.toml</summary>

```toml
baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #40568'

defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.es]
contentDir = 'content/es'
languageCode = 'es-ES'
languageName = 'Espanol'
weight = 2
```
</details>

<details>
<summary>config\development\server.toml</summary>

```toml
[[redirects]]
from = '/en/**'
to = '/en/404.html'
status = 404

[[redirects]]
from = '/es/**'
to = '/es/404.html'
status = 404
```
</details>

---

See:
<https://github.com/gohugoio/hugo/blob/master/commands/server.go#L439>

I suspect that this:

```
file, err := fs.Open(filepath.FromSlash(strings.TrimPrefix(redirect.To, u.Path)))
```

Should be this:

```
file, err := fs.Open(strings.TrimPrefix(redirect.To, u.Path))
```

---

MRE:

```bash
git clone --single-branch -b hugo-forum-topic-40568 https://github.com/jmooring/hugo-testing hugo-forum-topic-40568
cd hugo-forum-topic-40568
hugo server
```

Reference:
<https://discourse.gohugo.io/t/404-pages-on-localhost-for-multilingual-site-failing/40568/15>
