### ISSUE TITLE
Cannot use .Site.RegularPages.Related with index called "categories"; all other taxonomies work fine

### ISSUE THREAD

**Issue by FuadEfendi** [gohugoio/hugo#10346]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.104.0+extended darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes

### The Issue
```
error calling Related: indexing currently not supported for index "categories" and type []interface {}
```
It corresponds to Line 295 of `inverted_index.go`; it seems `categories` is reserved keyword, defined as an interface?

Here is my YAML:
```
taxonomies:
  category: "categories"
  series: series
  tag: tags
  term: terms
  # authors: authors

related:
  includeNewer: false
  indices:
  - name: "categories"
    weight: 100
  - name: date
    weight: 10
  threshold: 80
  toLower: false
```

Note that if I replace "categories" with tags, or series, it works; only "categories" doesn't work.
