### ISSUE TITLE
markdownify raw HTML regression between 0.92.2 and 0.93

### ISSUE THREAD

**Issue by Teknomancer** [gohugoio/hugo#10378]
### What version of Hugo are you using (`hugo version`)?
0.93

<pre>
$ hugo version
hugo v0.93.0-07469082+extended windows/amd64 BuildDate=2022-02-28T08:30:42Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

I do have `config.toml` with the necessary `unsafe = true` setting:
```toml
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]   
    noClasses = false   
```

**To test:**
```html
    <p>{{- "<span class='abbrev'>abcd</span>" | markdownify -}}</p>
```

**Outputs:**
In 0.92.2:
```html
<p><span class='abbrev'>abcd</span></p>
```

In 0.93:
```html
<p>&lt;span class=&#39;abbrev&#39;&gt;abcd&lt;/span&gt;</p>
```

Despite having the `unsafe = true` in `config.toml`, it seems to be ignored in Hugo versions 0.93 and above.
