### ISSUE TITLE
Font size of some characters in the code block is larger than others

### ISSUE THREAD

**Issue by michimani** [gohugoio/hugo#10410]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.105.0+extended darwin/amd64 BuildDate=unknown
</pre>

Other than this version, this bug has been observed in versions 0.93.0 and later.

### Does this issue reproduce with the latest release?

Yes.

### Issue description

On a low-resolution display, only a portion of the code block is larger in font size. I reproduced this on my iPhone 13 Pro.  
However, it is not reproduced in developer mode of Google Chrome, etc., and is reproduced only on the actual device.

I tried using hugo version 0.92.2 (or earlier) for building, but it did not reproduce.  
This is my guess, but I think it may be due to the Mermaid notation support in v0.93.0.

(build by v0.92.2)
![FgjqkPzaYAE7tkw](https://user-images.githubusercontent.com/9986092/199489796-21630882-02c8-4a02-9540-33be26282553.jpg)

(build by v0.93.0 or higher)
![FgjqkP4agAAQnYX](https://user-images.githubusercontent.com/9986092/199489868-ab7a459e-e250-4d09-b330-7e01655035f7.jpg)

The font size of `"AWS": "arn...` is bigger than other text.

Thank you in advance for your confirmation.

**Comment by bep** [comment]
I think 0.93.0 got us a new Chroma (the highlighter in use), which may be the culprit here, but it's not obvious to me what without seeing the details (are you using the inline styles option?)

**Comment by michimani** [comment]
@bep    
Thanks for your quick response.  

he setup for my site is as follows

```toml
theme = "simplog"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        tabWidth = 2
        lineNumbersInTable = false
        style = "dracula"
```

However, I checked again and this event is resolved by applying the style `-webkit-text-size-adjust: 100%;`.

So I will apply the above style to my site as soon as possible.
