### ISSUE TITLE
Unable to import mounted CSS into SCSS.

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#10592]
Hi, Hugo seems doesn't able to load mounted CSS file into SCSS, but normal CSS files are OK.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended linux/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yep.

### Log

```
Template changed WRITE         "/home/razonyang/Projects/razonyang/hugo-lab/layouts/index.html"
WARN 2022/12/31 14:13:30 tingle.js/tingle.css
WARN 2022/12/31 14:13:30 tingle.js/tingle.js
ERROR 2022/12/31 14:13:30 Rebuild failed: TOCSS-DART: failed to transform "main.scss" (text/x-scss): "/home/razonyang/Projects/razonyang/hugo-lab/assets/main.scss:2:8": Can't find stylesheet to import.
```

### Reproduce steps

```toml
// config.toml
[[module.imports]]
path = "github.com/robinparisi/tingle"

[[module.imports.mounts]]
source = "src"
target = "assets/tingle.js"
```

```go
// layouts/index.html
<html>
    <head>
        {{- range resources.Match "tingle.js/*" }}
          {{- warnf "%v" .Name }}
        {{- end }}
        {{ $css := resources.Get "main.scss" }}
        {{ $css = $css | toCSS (dict "includePaths" (slice "node_modules") "transpiler" "dartsass") }}
        <link href="{{ $css.RelPermalink }}" rel="stylesheet">
    </head>
    <body>
        <h1 class="text-red">RED HEADING</h1>
    </body>
</html>
```

```scss
// assets/main.scss
@import "foo/bar";
@import "tingle.js/tingle"; # Comment this line works as expected.

// assets/foo/bar.css
.text-red {
    color: red;
}
```

> Full example located at https://github.com/razonyang/hugo-lab/tree/scss-import-css. `cd exampleSite && hugo server`.

Both `libsass` and `dartsass` are not working.
