### ISSUE TITLE
Footnotes is always rendered at the end of post instead of the writting location

### ISSUE THREAD

**Issue by philong6297** [gohugoio/hugo#10601]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.109.0-47b12b83e636224e5e601813ff3e6790c191e371+extended windows/amd64 BuildDate=2022-12-23T10:38:11Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

I have the following markdown file:
```md
+++
title = "test"
+++

# H1
write something

## h1.1
write something[^1]

[^1]: annex 1 (should be under ``h1.1``)

# H2
write something[^2]

[^2]: annex 2 (should be under ``H2``)
```

It is rendered as this:
![image](https://user-images.githubusercontent.com/29605147/210616460-30d81653-33d3-43d0-b440-619fc92cd3df.png)

How can I get the footnotes in each section? I expected that the ``annex 1`` foonotes should be under heading ``h1.1``

This is the configuration:
```toml
[markup]
  [markup.tableOfContents]
    endLevel   = 3
    ordered    = false
    startLevel = 1
  [markup.highlight]
    anchorLineNos      = false
    codeFences         = true
    guessSyntax        = false
    hl_Lines           = ''
    lineAnchors        = ''
    lineNoStart        = 1
    lineNos            = true
    lineNumbersInTable = true
    noClasses          = true
    style              = 'onedark'
    tabWidth           = 2
  [markup.goldmark]
    parser.autoHeadingID     = true
    parser.autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe    = true
      xhtml     = false
```
