### ISSUE TITLE
Allow "smart merging of config" for language specific configs.

### ISSUE THREAD

**Issue by cmpute** [gohugoio/hugo#10620]
Choosing how the config is merged between user config and theme config is supported by #8633, but the merge between language specific config and base config seems to be not supported.

If I have a theme config
```toml
[params.comments]
color = "aaa"
title = "xxx"
```

then a language specific config
```toml
[[language.en]]
[language.en.params.comments]
title = "yyy"
```

then the color config will not be merged into the final config of that language. Maybe it's feasible but just I don't know how to.

**Comment by jmooring** [comment]
I think the current behavior is correct, and it makes sense to me. A language key has greater specificity than a root key (similar to the way CSS rules work). You can see how this works, even without a theme.

Without a language params table:

```text
[params.comments]
title = 'root'

{{ site.Params.comments }} --> map[title:root]
```

With a language params table, but without any key/value pairs:

```text
[params.comments]
title = 'root'

[languages.en.params.comments]

{{ site.Params.comments }} --> map[]
```

With a populated language params table:

```text
[params.comments]
title = 'root'

[languages.en.params.comments]
title = 'en'

{{ site.Params.comments }} --> map[title:en]
```

**Comment by cmpute** [comment]
I understand that language config has higher priority than the normal config. To make it clearer, what I would like to see is the ability to set `color = "aaa"` for language `en` as well if I have the following lines in the config file:
```toml
[params.comments]
color = "aaa"
title = "xxx"
[[language.en]]
[language.en.params.comments]
title = "yyy"
```

In the current behavior, the `color` setting will just be discarded instead of being merged. So `{{ site.Params.comments.color }}` is empty. It will be great if we can also support a `_merge` option to opt-in the deep merging behavior.
