### ISSUE TITLE
Server url rewrite issue in macOS Ventura (13.2)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10668]
I upgraded to macOS Ventura this weekend, and now I'm having an issue with some server rewrites stopped working. I have no clue as to what, but I assume it's connected to the upgrade. This is the dev server only, when you configure something like this:

```toml
[server]
[[server.redirects]]
from = "/foo/**"
to = "/bar/"
status = 200
```
