### ISSUE TITLE
asciidoc: error position when generate diagram

### ISSUE THREAD

**Issue by cathaysia** [gohugoio/hugo#10686]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.106.0+extended
</pre>

### Does this issue reproduce with the latest release?

I don't know. I use hugo in docker. :(

here is my Dockerfile:

```dockerfile
FROM asciidoctor/docker-asciidoctor:latest

RUN apk add --no-cache hugo

```

and here is my Makefile:

```make
server: image
	docker run -it -v`pwd`:/documents -p1313:1313 hugo_asciidoc hugo server --bind 0.0.0.0 --destination public

build: image
	docker run -v`pwd`:/documents -p1313:1313 hugo_asciidoc hugo --buildDrafts --buildFuture --destination public

image:
	docker build ./docker/ -t hugo_asciidoc
```

----------------------

![image](https://user-images.githubusercontent.com/42114817/216504481-ca20d1ea-e633-4c55-a1b1-d24e56faeb43.png)

just as this picture, pictures are generated in '%E5%86%99%E4%B8%80%E4%B8%AA%E5%86%85%E5%AD%98%E5%88%86%E9%85%8D%E5%99%A8', but not '写一个内存分配器'

here is my config:

```toml
title = 'xxxx'
theme = 'book'

[params]
BookTheme = 'dark'
BookToc = false
BookSection = '*'

[security.exec]
allow = ["^asciidoctor$"]

[markup.asciidocExt]
extensions = ["asciidoctor-mathematical", "asciidoctor-diagram"]
workingFolderCurrent = true
```
