### ISSUE TITLE
site.LanguageCode should default to the language key

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#10690]
Currently for the current language configuration:

```
languages:
  fr:
    name: Français
    weight: 2
```

When navigating the french Site, `site.LanguageCode` will return an empty string. It's only when the user adds a `languageCode` key to the language configuration that `site.LanguageCode` will return something. It means user systematically needs to add 

```
fr: 
  name: Français
  weight: 2
  languageCode: fr-fr
```

I think it would make sense, that `site.LanguageCode` returns the language key, here `fr` if no `languageCode` is set for the language.
