### ISSUE TITLE
Sorting menus by the order they're placed

### ISSUE THREAD

**Issue by chris-79** [gohugoio/hugo#10710]
Why do (menu) items have to be sorted alphabetically by default? And why do we **_have to_** use a "weight" parameter when we can just put them in the order we want??

I just don't understand the reasoning behind this _at all_. &nbsp; ELI5

This should show up in the order that it appears, but it doesn't… it gets sorted alphabetically ("Directory" is first)

```
menu:
  siteNavigation:
    - name: Testing 1-2-3
      url: /123
    - name: Directory
      url: /directory
```

```
{{ with .Site.Menus.sitenavigation }}
<nav aria-label="Primary">
  <ul>
    {{ range . -}}
    <li><a href="{{ .URL }}">
      {{- (replace .Name " " "&nbsp;") | safeHTML -}}
    </a></li>
    {{ end -}}
  </ul>
</nav>
{{ end -}}
```
