### ISSUE TITLE
markup configuring in hugo themes

### ISSUE THREAD

**Issue by Yharimium** [gohugoio/hugo#10716]
### What version of Hugo are you using (hugo version)?
```
hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended windows/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

yes

------

i've tried to configure markup in `./themes/mytheme/config.yaml`

```
markup:
  highlight:
    anchorLineNos: true
    lineNos: true
    lineNumbersInTable: false
    style: trac
    tabWidth: 4
```

and import `mytheme` in `./config.yaml`

```
theme: "mytheme"
```

but markup configuration in that theme didn't work.

if the markup configuration is placed in `./config.yaml` directly, then that can work well.

> PS: This is not the case with params. params in `./config.yaml` and `./themes/mytheme/config.yaml` can both work.

According to hugo docs, this type of file (data) in the themedirs should be merged recursively. If this is a bug, hope you can fix it soon.
