### ISSUE TITLE
Incorrect code fence width affecting background color

### ISSUE THREAD

**Issue by exastone** [gohugoio/hugo#10723]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.110.0+extended darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes. currently using latest release.

The {{ highlight }} function resulting in generating html/css that does not fully span the entire width of the fenced code block when there is long lines.

<img width="841" alt="Screenshot 2023-02-15 at 12 45 08 AM" src="https://user-images.githubusercontent.com/61954919/218928291-460ebb21-4d0c-4ee5-ae8f-25463336f56c.png">

After inspecting the generated css this issue can be resolved by adding `width: fit-content` to the div that immediately follows `<div class="highlight">`

<img width="809" alt="Screenshot 2023-02-15 at 12 49 07 AM" src="https://user-images.githubusercontent.com/61954919/218929048-431b6605-eb0c-4acf-93e9-ec8a97990437.png">

Here is a simple example to reproduce:

```go
{{< highlight md >}}
  // this is a looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line
{{< /highlight >}}
```
Here is the generated html for a simplified example (line numbers option off):

```html
<div class="highlight">
  <pre tabindex="0" style="color:#d8dee9;background-color:#2e3440;-moz-tab-size:4;-o-tab-size:4;tab-size:4;">
    <code class="language-md" data-lang="md">
        <span style="display:flex;">
            <span>  // this is a looooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong line </span>
        </span>
    </code>
  </pre>
</div>
```

and here is the rendered output:

<img width="1168" alt="Screenshot 2023-02-15 at 1 07 24 AM" src="https://user-images.githubusercontent.com/61954919/218931962-b2549e88-2de3-4880-a2d1-c72c46eeb677.png">

and here is the rended output after adding `width: fit-content` to the `<pre>` element:

<img width="1171" alt="Screenshot 2023-02-15 at 1 09 12 AM" src="https://user-images.githubusercontent.com/61954919/218932221-cb15a53c-c4cf-496d-9629-2170ae85dddb.png">

Additional Information:

When `lineNos = true` there are several additional element generated in a code block compared to when `lineNos = false`

When `lineNos = true` the classless `<div>` that immediately follows `<div class="highlight">` can be assigned `width: fit-content` to resolve the issue described.

When `lineNos = false`, there are fewer additional elements generated. The described issue can be resolved by adding `width: fit-content` to the `<pre>` element.

**Comment by jmooring** [comment]
Rendering of fenced code blocks varies with:

- `linenos = false`
- `linenos = inline` (shorthand notation for `lineNos=true` and `lineNumbersInTable=false`)
- `linenos = table` (shorthand notation for `lineNos=true` and `lineNumbersInTable=true`)
- `markup.highlight.noClasses = true` vs. `markup.highlight.noClasses = false`
- Whether or not the content overflows the width of the container

I use this CSS to produce the same visual output for all combinations of the above:

<details>
<summary>main.css</summary>

```css
/* https://github.com/alecthomas/chroma/issues/722 */
.highlight .chroma .lntable .lnt,
.highlight .chroma .lntable .hl {
  display: flex;
}

/* https://github.com/alecthomas/chroma/issues/722 */
.highlight .chroma .lntable .lntd + .lntd {
  width: 100%;
}

/* line numbers inline, no line numbers */
.highlight > pre {
  padding: 1em;
}

/* line numbers in table */
.highlight div {
  padding: 0 1em;
}

.highlight div,
.highlight > pre {
  overflow-x: auto;
}
```
</details>

Example:

```text
git clone --single-branch -b hugo-github-issue-10723 https://github.com/jmooring/hugo-testing hugo-github-issue-10723
cd hugo-github-issue-10723
hugo server
```

There's an [open issue upstream](https://github.com/alecthomas/chroma/issues/722) about one of the combinations, but otherwise I'm not sure this is actionable.
