### ISSUE TITLE
liveReload doesn't render changes when using local module replacements, despite acknowledging file change

### ISSUE THREAD

**Issue by khayyamsaleem** [gohugoio/hugo#10893]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.111.3
</pre>

### Does this issue reproduce with the latest release?
Yes

------

### Issue Description

Not sure if this bug presents for ALL instances of local module replacements, or if I've encountered some kind of edge-case due to the specific module I'm importing, but what's happening is:

have a (admittedly large) external content module, mounted with hugo modules like:

```
module:
  replacements: "github.com/user/repo/some/subpath -> ../.external/subpath"
  imports:
    - path: github.com/user/repo/some/subpath
      mounts:
        - source: "a.md"
          target: "content/docs/a-prime.md"
        # ... more mounts
```

**When `a.md` is modified in `../.external/subpath`,**

-- **the `hugo server` stdout acknowledges that the file was written,**
-- **and the `--debug` output also acknowledges the file was changed and re-rendered,**
-- **and the browser window flashes a refresh**

**but the content remains the same.**

The same behavior is observed with `--disableFastRender` and `--renderToDisk`, and the file in `public/docs/a-prime.html` is not up-to-date.

This behavior is observed on both M1 and Intel macOS machines, as well as a x86_64 linux machine.

This behavior is also observed when using the `HUGO_MODULE_REPLACEMENTS` env var, and with the replacement target being outside the site directory.

**Fully stopping and restarting the hugo server allows the re-render to persist.**

Other flags tried: `--ignoreCache --gc --renderToDisk --disableFastRender --noChmod --poll 1000ms` (in several combinations)

(Repro can be provided upon request, I would just have to anonymize some things).
