### ISSUE TITLE
Make the built-in OutputFormat.Name lower case

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10896]
I'm doing some work to consolidate all Hugo config (for documentation), and I find one odd thing that needs to be corrected. The default set of output formats have mixed-case names (e.g. `Calender`, `RSS`), but all the custom/overrides gets lowercased (because they're map keys in the config), e.g:

```toml
[outputFormats]
  [outputFormats.MyEnrichedFormat]
    baseName = 'myindex'
    isPlainText = true
    mediaType = 'text/plain'
    protocol = 'bep://'
```

Becomes `myenrichedformat`.

We need to fix this, and, cross fingers, I don't think this should do (much) harm, as all the lookup methods we have are case insensitive.
