### ISSUE TITLE
Multihost doesn't handle a mix of baseURLs with and without a /path

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10912]
I'm doing some consolidation config work -- and there's a test case failing that should have passed.

Basically this config:

```toml
[Languages]
[Languages.en]
baseURL = "https://example.com/docs"
[Languages.fr]
baseURL = "https://example.fr"
```
