### ISSUE TITLE
Internal templates not found when isPlainText = true

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#10922]
With this config:

```toml
[outputFormats.HTML]
isPlainText = true
```

And this template code:

```html
{{ template "_internal/pagination.html" . }}
```

We get:

> ERROR ... template "_internal/pagination.html" not defined
