### ISSUE TITLE
Avoid writing to hugo_stats.json when there are no changes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#10985]
I'm trying to use the newly added `cachebusters` with TailwindCSS 3 with a construct like the one below:

```toml
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"
[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
```

Which looks odd and funky, but should allow me to do more fine grained builds as I would not have to trigger a Tailwind build for every template change. Unfortunately the above goes into an endless loop, which I suspect should be possible to prevent.
