### ISSUE TITLE
Official GitHub Actions action does not work on macOS

### ISSUE THREAD

**Issue by myitcv** [gohugoio/hugo#11010]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.112.1
</pre>

### Does this issue reproduce with the latest release?

Yes

Please can I confirm that https://github.com/peaceiris/actions-hugo is the official action to install Hugo in GitHub Actions workflows? Is there an official place where this is documented?

Assuming that it is, there are two blockers to using that action to install Hugo on macOS:

https://github.com/peaceiris/actions-hugo/issues/605
https://github.com/peaceiris/actions-hugo/issues/608

It feels like there should be an official Hugo-project owned and maintained action to make the installation of Hugo as part of GitHub Actions seamless. 

Thoughts?

**Comment by jmooring** [comment]
Our recommended GitHub Action is based on [GitHub's Starter Action for Hugo](https://github.com/actions/starter-workflows/blob/main/pages/hugo.yml).

You would need to modify our [recommended GitHub Action](https://gohugo.io/hosting-and-deployment/hosting-on-github/) to be compatible with macOS. I have never tried this; I have never had a need to use anything other that Ubuntu in a CI/CD workflow.

Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.

**Comment by bep** [comment]
I'll reopen this. It's limited what we as a project can do, but this issue is at least within the scope of things I care (and know a little) about.

**Comment by myitcv** [comment]
> I'll reopen this.

Thanks @bep. My suggestion would be something like `github.com/gohugoio/setup-hugo` as a GitHub action that knows how to install Hugo on various platforms. In the same spirit as https://github.com/actions/setup-go and friends. That should be a relatively simple action, because all it would do is shim the installation of the binaries Hugo already produces for every platform. 

The main use case here (and I'm sure I can't be the first to run into this) is to ensure that all developers of https://github.com/cue-lang/cuelang.org can reliably follow steps in a readme and know that they will work. That requires us to have a build matrix that includes macOS (and windows, at a later date).

**Comment by bep** [comment]
@myitcv yea, we can do something like that ... as to naming the repo ... `setup-actions-hugo`? Sounds a little clumsy, but it makes room for other "setup" repos later...

**Comment by myitcv** [comment]
> Sounds a little clumsy, but it makes room for other "setup" repos later...

Do you know of any such patterns that exist today?

The `setup-*` pattern is _so_ common with GitHub actions. 

I'd suggest unless there are compelling reasons to stray from that (i.e. a clash with another very common pattern), the GitHub pattern is likely to dominate and hence be most "accessible" for folks.

**Comment by bep** [comment]
>The setup-* pattern is so common with GitHub actions.

The example you gave had that context in the org name, `actions/setup-go`. Adding `gohugoio/setup-hugo` would

1. Not tell me that it's about GitHub actions.
2. Give an indication that it's an all purpose "Hugo setup tool", whatever that is...

**Comment by myitcv** [comment]
> The example you gave had that context in the org name, `actions/setup-go`

That's a good point. 

We (perhaps wrongly therefore) went with https://github.com/cue-lang/setup-cue.

Building on your context point, I'll throw `ghactions-setup-hugo` out there as an alternative.

cc @mvdan who often has good ideas re naming.

**Comment by myitcv** [comment]
This is still relevant.

**Comment by agriyakhetarpal** [comment]
Please feel free to run the latest and greatest versions of Hugo (extended) through a combination of `actions/setup-python` and `pipx` via the `pipx run hugo==<your hugo version here> new site mysite` command or similar commands of your liking. I would like to note that this distribution is unaffiliated with the Hugo developers here at the time of writing and is a community-maintained unofficial build.

**Comment by yochem** [comment]
I would like this too, because:

- Keeping the current "official" way up to date is cumbersome. I sometimes visit [this gohugo.io documentation page](https://gohugo.io/hosting-and-deployment/hosting-on-github/) to update my action workflow to use the current recommended commands
- Currently no way to set version to 'latest'
- I'd rather use an "official" action than one from a random gh user
- The default action for deploying hugo on gh pages would be easy to grasp:
```yml
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Hugo
        uses: gohugoio/hugo-action@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
```

I would also suggest that the action runs the `hugo` command to simplify general usage. Passing an `args` argument would allow for more advanced usage of Hugo. Therefore, I suggest the name to be `hugo-action` instead of `setup-hugo`, since it not only _sets up_ hugo, but also runs it.
