### ISSUE TITLE
Add the [params] concept to front matter

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11055]
Note that this is 

* Mostly about documentation.
* We will never (or if we do, we should get some way of converting old) break the "old way" of doing it.

We had a similar situation in `language.params`, where we allowed custom params at the top level. Now we warn about that and we will eventually remove that option.

So, from a documentation standpoint (API spec) this is problematic because it's hard to define which fields that makes up the API when "field A, B, C are Hugo configuration, all the rest are params".

So this proposal suggest that we from a _documentation standpoint_ encourages front matter on the form:

```yaml
title: Hello World
date: 2020-01-01
params:
  color: blue
```

And just to make this clear, this would also continue to work:

```yaml
title: Hello World
date: 2020-01-01
color: blue
```

The "world" is a little more complicated than the above, but let us keep it simple for now.

/cc @jmooring
