### ISSUE TITLE
v0.112.6 - The .URL menu variable ignores the  baseURL subdirectory

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#11062]
config

```toml
baseURL = "https://example.org/foo/"

[[menu.main]]
name = 'Posts'
url = '/posts'
```

template

```
{{ warnf "%s" (index site.Menus.main 0).URL }}
```

v0.111.3 --> `/foo/posts`  (CORRECT)
v0.112.6 --> `/posts`

This is not an issue if you specify `pageRef` instead of `url` in the menu entry definition, but I suspect (unfortunately) that the vast majority of live sites use `url` instead of `pageRef`.

Related: <https://discourse.gohugo.io/t/issue-with-baseurl-in-0-112-0-0-112-6/44656/>
