### ISSUE TITLE
Hugo mod init doesn't work with multiple environments

### ISSUE THREAD

**Issue by ITblacksheep** [gohugoio/hugo#11072]
### What version of Hugo are you using (`hugo version`)?
>0.111.3
<pre>
$ hugo version

</pre>

### Does this issue reproduce with the latest release?
Yes

We have multiple environments each with their own content modules. When trying to do a hugo mod init it now errors out on whatever the last module is in the config directory.

Error: failed to load modules: module "URI to Module" not found in "<path to folder>/themes/URI to Module"; either add it as a Hugo Module or store it in "<path to Folder>/themes".: module does not exist 

Steps to reproduce.

Add import to module point at a .git file.

config.yaml under _default.

```yaml
module:
  hugoVersion:
    extended: true
    min: 0.100.0
  imports:
    - path: <URI>.git
      disable: false
      mounts:
        - source: assets
          target: assets
        - source: layouts
          target: layouts
```
