### ISSUE TITLE
.Site.Social contains unexpected extra key '_merge' as of version 0.112.0

### ISSUE THREAD

**Issue by henryleach** [gohugoio/hugo#11083]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.113.0+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### To Reproduce:

In config.toml

```toml
[social]
fediverse = "https://fosstodon.org"
github = "https://www.github.com"
twitter = "https://www.twitter.com"
stackoverflow = "https://www.stackoverflow.com"
facebook = "https://www.facebook.com"
linkedin = "https://www.linkedin.com"
```

In the partial I have:
```html
<p>{{ .Site.Social }}</p>
<p>{{ range $key, $val := .Site.Social }}
	{{ print $key ": " $val }}<br>
    {{ end }}</p>
```

On Version 0.112.0+ (inc 0.113) this renders to:

```
map[_merge: facebook:https://www.facebook.com fediverse:https://fosstodon.org github:https://www.github.com linkedin:https://www.linkedin.com stackoverflow:https://www.stackoverflow.com twitter:https://www.twitter.com]

_merge: 
facebook: https://www.facebook.com
fediverse: https://fosstodon.org
github: https://www.github.com
linkedin: https://www.linkedin.com
stackoverflow: https://www.stackoverflow.com
twitter: https://www.twitter.com
```

On version 0.111.3 this used to render to:
```
map[facebook:https://www.facebook.com fediverse:https://fosstodon.org github:https://www.github.com linkedin:https://www.linkedin.com stackoverflow:https://www.stackoverflow.com twitter:https://www.twitter.com]

facebook: https://www.facebook.com
fediverse: https://fosstodon.org
github: https://www.github.com
linkedin: https://www.linkedin.com
stackoverflow: https://www.stackoverflow.com
twitter: https://www.twitter.com
```

Without the random, emtpy, additional "_merge" key. Is this key now expected in such a map? I searched for documentation regarding `.Site.Social`, but could only find this old [issue 1380 from 2015](https://github.com/gohugoio/hugo/issues/1380)
