### ISSUE TITLE
resources.Get unable to obtain resource from overlapping mounts

### ISSUE THREAD

**Issue by markdumay** [gohugoio/hugo#11239]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.115.2-8966424e0e521fb1627216a84efd2c5d5917cb0d+extended darwin/arm64 BuildDate=2023-07-08T17:06:56Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes

### Issue
In the context of using a module in local development (using the `replacements` directive), `resources.Get` has trouble reading a file that has been renamed in the module's `mount` config. The method fails with the following message:
```
error calling ExecuteAsTemplate: type <nil> not supported in Resource transformations
```

Replacing `resources.Get` with `resources.GetMatch` seems to fix the issue.

### Context
A test repository is available on https://github.com/gethinode/mod-fontawesome. The repository uses `npm` to wrap the Hugo binary and other dependencies. The repository renames a local file in a module mount, see `~/config.toml`:

```toml
[module]
[...]
  [[module.mounts]]
    source = "dist/scss"
    target = "assets/scss/modules/fontawesome"
    excludeFiles = "fontawesome.scss"
  [[module.mounts]]
    source = "dist/scss/fontawesome.scss"
    target = "assets/scss/modules/fontawesome/fontawesome-free.scss"
```

The `exampleSite` uses the `replacements` directive to use the local module files of its parent, see `~/exampleSite/hugo.toml`:

```toml
[module]
  replacements = 'github.com/gethinode/mod-fontawesome -> ../..'
  [[module.imports]]
    path = "github.com/gethinode/mod-fontawesome"
```

### Steps to reproduce the error
Use the following steps to reproduce the error (npm is required; tested on macOS Ventura 13.4):

1. Run the following commands from a local working directory:
```bash
git clone -b hugo-issue-11239 https://github.com/gethinode/mod-fontawesome.git
cd mod-fontawesome
npm i
npm run mod:update
npm run test
```

2. Confirm the test site is running by starting a local server and navigating to `localhost:1313` (or any other port assigned)
```bash
npm run start
```

3. Stop the server with `Ctrl+c`

4. Replace `resources.GetMatch` with `resources.Get` on line 16 of the file `exampleSite/layouts/partials/head/stylesheet.html`

5. Rerun the test and observe the error message
```bash
npm run test
# error calling ExecuteAsTemplate: type <nil> not supported in Resource transformations
```
