### ISSUE TITLE
An empty ul + li pair in {{ .TableOfContents }}

### ISSUE THREAD

**Issue by MKPlato** [gohugoio/hugo#11280]
### What version of Hugo are you using (`hugo version`)?
hugo v0.115.3+extended

### Does this issue reproduce with the latest release?

In hugo.yml
```
markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
    tableOfContents:
      endLevel: 3
      ordered: true
      startLevel: 2
```

In markdown

```
## head 2
##### head 5
text
```

This will output an empty `<ul><li></li></ul>` like this:

```
<nav id="TableOfContents">
  <ul>
    <li><a>head 3</a>
      <ul>
        <li></li>
      </ul>
    </li>
  </ul>
</nav>
```
