### ISSUE TITLE
Change default merge strategy for `languages.<LangPrefix>.markup` to `deep`

### ISSUE THREAD

**Issue by salim-b** [gohugoio/hugo#11355]
Since https://github.com/gohugoio/hugo/issues/10620 has been resolved, we can set per-language markup config like

```toml
[languages.de.markup.goldmark.extensions.typographer]
leftDoubleQuote = '&laquo;'   # default &ldquo;
rightDoubleQuote = '&raquo;'  # default &rdquo;
```

Now one mustn't forget to also set 

```toml
[languages.de.markup]
_merge = 'deep'
```

since otherwise other options from regular `markup` config aren't respected for lang `de` and Hugo falls back to built-in defaults.

Would be nice if `_merge = 'deep'` could become the default for `languages.<LangPrefix>.markup`.
