### ISSUE TITLE
Module `disable` should not disable other dependencies/modules required by other modules.

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#11376]
Hi, I'm encountering an issue about disabling the modules, for example, there are two modules, `foo` and `bar`, both of them require the `common` module. Their configuration as follows.

```toml
[[module.imports]]
path = "modules/common"
```

And the site configuration as follows.

```toml
[[module.imports]]
path = "modules/foo"

[[module.imports]]
path = "modules/bar"
```

When I disable the `foo` module, then the `common` module will be disabled as well, which is unexpected and causes the `bar` module broken.

```toml
[[module.imports]]
path = "modules/foo"
disable = true

[[module.imports]]
path = "modules/bar"
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=snap:0.117.0
</pre>

### Does this issue reproduce with the latest release?

Yes
