### ISSUE TITLE
Chromastyles for line highlighting isn't using the correct color

### ISSUE THREAD

**Issue by mandaris** [gohugoio/hugo#11445]
### What version of Hugo are you using (`hugo version`)?

```shell
hugo v0.118.2-da7983ac4b94d97d776d7c2405040de97e95c03d+extended darwin/amd64 BuildDate=2023-08-31T11:23:51Z VendorInfo=brew
```

### Does this issue reproduce with the latest release?
Yes.

### What are the steps to reproduce?
Using the command found in the documentation at https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css 

```bash
hugo gen chromastyles --style=monokai > syntax.css
```

This generates a css file where the line highlight is the following.

```css
/* LineHighlight */ .chroma .hl { background-color: #ffffcc }
```

When you run chroma by itself using the following command

```bash
chroma -s monokai --html-styles --style=monokai
```
it will generate the following css

```css
/* LineHighlight */ .chroma .hl { background-color: #3c3d38 }
```
