### ISSUE TITLE
Ignore postcss.config.js from specified module 

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#11490]
The postcss.config.js from some specified module may cause build fails, it will be great if there is an option to ignore it, like the ignoreConfig and ignoreImports.

```toml
[[module.imports]]
path = "github.com/animate-css/animate.css"
```

```
TypeError: Cannot read properties of undefined (reading 'prefix')
    at module.exports (/home/razon/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/animate-css/animate.css@v4.1.1+incompatible/postcss.config.js:18:60)
```
