### ISSUE TITLE
CSS minify breaks `calc` expression

### ISSUE THREAD

**Issue by chrillek** [gohugoio/hugo#11533]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.119.0
Also present in 0.117.0, **not** in 0.115.0
</pre>

### Does this issue reproduce with the latest release?
Yes

CSS source code 
```css
html {
  font-size: clamp(16px, calc(65% + 12 * (100vw - 320px) / 1000), 26px);
}
```
After minification:
```css
html {
  font-size: clamp(16px,calc(65%+12 * (100vw - 320px) / 1000),26px);
}
```

So, the white space around the `+` operator gets removed, while it's preserved around the `*`, `-`, and `/` operators. In 0.115, white space for every oprator but the division was preserved.

However, the `+` and `-` operator _require_ surrounding white space (cf. https://developer.mozilla.org/en-US/docs/Web/CSS/calc#notes). Consequently, `minifiy` breaks the CSS at this point. 

Taking `minify` out of the pipeline fixes the issue, which seems to indicate that it is the culprit here.
