### ISSUE TITLE
Regression in RSS templates author deprecation

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#11639]
The RSS template adjustment didn't consider this simple case:

```toml
[params]
author = 'jdoe'
```
