### ISSUE TITLE
cannot use twitter template

### ISSUE THREAD

**Issue by L1ghtn1ng** [gohugoio/hugo#11657]
### What version of Hugo are you using (`hugo version`)?
<pre>
$ hugo version
hugo v0.120.2-9c2b2414d231ec1bdaf3e3a030bf148a45c7aa17+extended linux/amd64 BuildDate=2023-10-31T16:27:18Z VendorInfo=snap:0.120.2
</pre>

### Does this issue reproduce with the latest release?
Yes

Cannot use the internal twitter card like #11648 

Error: error building site: render: failed to render pages: render of "page" failed: "/home/jay/code/hugo-sites/preview.cybermon.uk/themes/hello-friend-ng-cloudflare/layouts/_default/baseof.html:4:11": execute of template failed: template: _default/single.html:4:11: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/twitter_cards.html:25:9: executing "_internal/twitter_cards.html" at <site>: can't evaluate field twitter in type []interface {}

**Comment by jmooring** [comment]
1\) Are you using a theme? If yes, which theme?

2\) Please post the `params` portion of your site configuration.

**Comment by L1ghtn1ng** [comment]
The theme I am using is this https://github.com/L1ghtn1ng/hugo-theme-hello-friend-ng-cloudflare
```toml
[languages.en.params.logo]
  logoText = 'Cybermon'
  logoHomeLink = '/'


[[params.social]]
  name = 'twitter'
  url = 'https://twitter.com/jay_townsend1'

[[params.social]]
  name = 'github'
  url = 'https://github.com/l1ghtn1ng'


[[params.social]]
  name = 'linkedin'
  url = 'redacted'


[params]
  dateform        = 'Jan 2, 2006'
  dateformShort   = 'Jan 2'
  dateformNum     = '2006-01-02'
  dateformNumTime = '2006-01-02 15:04'

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false
  enableSharingButtons = true
  pygmentsCodefences = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle = "monokai"
  cloudflareWebAnalytics = "redacted"
  enableEmoji = true
  defaultTheme = "dark"

[params.footer]
    trademark = true
    copyright = false
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
    ]
```
