### ISSUE TITLE
Question about the CI configuration page

### ISSUE THREAD

**Issue by boddedo** [gohugoio/hugo#11800]
Hello, it's a question about the documentation: [https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/#configure-gitlab-cicd](https://gohugo.io/hosting-and-deployment/hosting-on-gitlab/#configure-gitlab-cicd)
on this page, there is a lot of process just to "publish" the page, why we need to minify ?
why there is no "hugo --environment production"

why not just:

.gitlab-ci.yml
```
variables:
  GIT_DEPTH: 0
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

image:
  name: registry.gitlab.com/pages/hugo:latest

pages:
  script:
    - cd $CI_PROJECT_DIR
    - hugo --environment production
  artifacts:
    paths:
      - public

  publish: public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```
