### ISSUE TITLE
Allow specifying CodeOwners data in Hugo config file

### ISSUE THREAD

**Issue by privatemaker** [gohugoio/hugo#11812]
I just discovered Hugo's [CodeOwners](https://gohugo.io/methods/page/codeowners/) feature and by proxy the whole `CODEOWNERS` convention by GitHub/Lab. It's somewhat useful, however, it would be perhaps more robust and useful if Hugo also allowed specifying it in `hugo.yaml` file or a `data/codeowners.yaml` as well, such as:

```
codeowners:
  - path: /content/posts/
    contacts: ["@rosa"] 
  - path: /content/research/
    contacts: ["karl@workers.org"]
  - path: /content/pages/
    contacts: ["https://workers.org/j.ball", "@rosa"]
```

This would streamline as a site maintainer the data, but also allow more flexibility in `.Page.CodeOwners` as well something which can be edited in a headless CMS like Decap or Sveltia CMS.

Hugo could also, if it detects the `codeowners:` values, generate the `CODEOWNERS` file in the `/` directory which can be committed to the repo.
