### ISSUE TITLE
Hugo Modules : Allow for `replacements` path within `imports` listing

### ISSUE THREAD

**Issue by HenrySkup** [gohugoio/hugo#11875]
Hi,

I think this might improve the maintenance of config files.  

I have a hugo website pulling modules from several repos and which uses `replacements` to use local files which will be the most up-to-date and gets around issues when the internet is not accessible.

**I think this would be similar to the intention of having the `disable : true | false` in the imports listings.**

### Currently 

```YAML

# config/*/module.yaml

replacements: 
  github.com/me/project-1 -> ../local/file/project-1, 
  github.com/me/project-2 -> ../local/file/project-2, 
  github.com/me/project-3 -> ../local/file/project-3, 
  github.com/me/project-4 -> ../local/file/project-4, 
imports :
  # other imports
  - # Project 1
    disable : false
    path : github.com/me/project-1
    # these imports can get quite complex with mounts 
  - # Project 2
    path : github.com/me/project-2
  - # Project 3
    path : github.com/me/project-3
  - # Project 4
    path : github.com/me/project-4
```

### Suggestion 

```YAML

# config/*/module.yaml

imports :
  # other imports
  - # Project 1
    disable : false
    path : github.com/me/project-1
    replacement : ../local/file/project-1
    # these imports can get quite complex with mounts 
  - # Project 2
    path : github.com/me/project-2
    replacement : ../local/file/project-2
  - # Project 3
    path : github.com/me/project-3
    replacement : ../local/file/project-3
  - # Project 4
    path : github.com/me/project-4
    replacement : ../local/file/project-4
```
