### ISSUE TITLE
Keep (but do not render) terms with render = 'link', list = 'never' 

### ISSUE THREAD

**Issue by djibe** [gohugoio/hugo#12131]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 0.123.0
and 0.123.3

</pre>

### Does this issue reproduce with the latest release?

Yes.

Didn't appear with Hugo 0.120 to 0.122

A taxonomy configured with the cascade is no more built.

It is meant to build a menu for fast access to categories without generating hundreds of pages.

```toml
[[cascade]]
  [cascade._build]
    list = 'never'
    render = 'never'
  [cascade._target]
    kind = '{taxonomy,term}'
    path = '{/specialites,/specialites/**}'
```

### 0.122

![Screen Shot 02-23-24 at 05 24 PM](https://github.com/gohugoio/hugo/assets/13089414/74f00621-86e6-45a7-9123-7614b595e011)

### 0.123.x

![Screen Shot 02-23-24 at 05 17 PM](https://github.com/gohugoio/hugo/assets/13089414/76d4314e-8df5-4f20-8209-bfa581e04fa2)

Thanks
