### ISSUE TITLE
Add some segments thresholds

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#12251]
This is an extension to #10106 and #12222.

Thinking about it a little, it would be useful to add some "thresholds" to the filters in `segments`, e.g:

```toml
[segments.segment1]
  [[segments.segment1.excludes]]
    lang = "n*"
  [[segments.segment1.excludes]]
    en     = "en"
    output = "rss"
  [[segments.segment1.includes]]
    term = "{home,term,taxonomy}"
  [[segments.segment1.includes]]
    path = "{/docs,/docs/**}"
    thresholdDurationSinceLastmod = "24h"
    thresholdCount = 123
```

In the above:

* `thresholdDurationSinceLastmod = "24h"` would mean: Only match pages where `Lastmod` is less than 24 hours old. This would also work nicely with sections/home etc. pages where `Lastmod` isn't explicitly set.
* `thresholdCount = 123` would be used typically in development where you only need a sample test set. I'm not sure how useful this is, though ...
