### ISSUE TITLE
Taxonomy term permalinks expand incorectly when adding custom metadata via a taxonomy term page

### ISSUE THREAD

**Issue by germanftorres** [gohugoio/hugo#12278]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.124.0-629f84e8edfb0b1b743c3942cd039da1d99812b0+extended linux/amd64 BuildDate=2024-03-16T15:44:32Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
Yes

### Description
When combining `[permalinks.term]` configuration with  adding taxonomy term custom metadata, the permalinks are not being generated correctly.

The structure of my site is pretty straightforward with a posts section and  categories/TERM/_index.md pages to augment taxonomy with custom metadata:

```
.
└── content
    └── categories
    |   └── viajes-en-familia
    |       └── _index.md 
    ├── posts
    |   ├── secretos-de-albarracin-pueblo-mas-bonito-teruel.md 
    |   ├── ..
    |   ├── ..

```

In my `hugo.toml`file, I customize the `[permalinks.term]` configuration to localize the permalinks to spanish (categories -> categorias). Note that this site is monolingual, but I'd like to keep the standard categories taxonomy in the source files and tweak url generation though configuration:

```toml
[taxonomies]
  category = 'categories'

[permalinks]
  [permalinks.page]
    posts = '/:year/:month/:day/:filename'

  # [permalinks.taxonomy]
  #   categories = "/categorias"

  [permalinks.term]
    categories = "/categorias/:slug/"      

```
My typical post file uses the categories taxonomy:

```yaml
---
title: "Secretos de Albarracín, el pueblo más bonito de Teruel"
date: 2024-01-19
categories: 
  - viajes-con-amigas
  - viaje-en-familia
  - viajes-romanticos
  - viajes-para-mujeres
author: 
  - Juan Carlos y Mar
---

La gran hoz del río Guadalaviar...
```

And the custom metadata is added to the taxonomy term vía the `/[taxonomy]/[term]/_index.md` file. For demonstration purposes  I will augment just one category with custom metadata and leave the rest without a metadata page:

**/categories/viaje-en-familia/_index.md**
```yaml
---
name: "En familia"
description: "Lugares para viajar con niños y actividades especiales para familias."
---
```

Now, when rendering a post summary template, I render all the categories listed in the post file using the `name` property of the custom metadata, if available, while also linking to the appropriate category page:

**/layouts/posts/summary.html**
```go
  <h2>
    <a href="{{ .RelPermalink }}">{{ .LinkTitle }}</a>
  </h2>
  {{ range .Params.categories }}
    {{- $category := . }}
    {{- $path := printf "%s/%s" "categories" ($category  | urlize ) }}
    {{- with $.Site.GetPage "taxonomyTerm" $path }}
      <a href="{{ .RelPermalink }}">{{ or .Params.name $category }}</a>
    {{- end }}
  {{ end }}
```

Now, with this setup, when rendering a post summary, the links generated for each category show a very strange behaviour. Note that the category that was customized (viaje-en-familia) correclty shows the customized category name in the link text ('En familia') while incorrectly generating the link as the slug is missing:

**output:**
```html
   <h2>
     <a href="/2024/01/19/que-ver-albarracin-teruel/">Secretos de Albarracín, el pueblo más bonito de Teruel</a>
   </h2>
       <a href="/categorias/viajes-con-amigas/">viajes-con-amigas</a>
  
       <a href="/categorias/">En familia</a>
  
       <a href="/categorias/viajes-romanticos/">viajes-romanticos</a>
  
       <a href="/categorias/viajes-para-mujeres/">viajes-para-mujeres</a>
  
```

This seems a bug to me, but as this is my first hugo experience, I'm not really sure if there's something else that I'm missing.

Thanks!

Germán

**Comment by germanftorres** [comment]
Yes, sorry for the long post, didn't know how to put it with less ceremony.

Without any `[permalinks.term]` configuration, the second category ('viaje-en-familia') renders this way:

```html
<a href="/categories/viaje-en-familia">En familia</a>
```
It uses the frontmatter to customize the link text and uses the category `term` to use as the slug for the link.
 
If I add the configuration, the rendered output for this category is:
```html
<a href="/categorias/">En familia</a>
```
Note the slug part is missing. So the link text is still correct and populated from the frontmatter, but somehow hugo is unable to generate the link in the form /categorias/:slug.

**Comment by jmooring** [comment]
@germanftorres 

Take this for a spin. I may be missing a detail, but it seems like what you want.

```text
git clone --single-branch -b hugo-github-issue-12278 https://github.com/jmooring/hugo-testing hugo-github-issue-12278
cd hugo-github-issue-12278
hugo server
```

The published site structure:

```
public/
├── 2024/
│   └── 03/
│       └── 19/
│           └── secretos-de-albarracin-pueblo-mas-bonito-teruel/
│               └── index.html
├── categorias/
│   ├── en-familia/
│   │   └── index.html
│   └── index.html
├── posts/
│   └── index.html
├── favicon.ico
└── index.html
```

Note that layouts/_default/single.html uses the much less fragile [`GetTerms`](https://gohugo.io/methods/page/getterms/) method to render the list of categories.

**Comment by germanftorres** [comment]
@jmooring 
Thanks for putting this sample.

For demonstration purposes, using name instead of title in the category frontmatter

/categories/viajes-en-familia/_index.md
```yaml
---
name: En familia
description: Lugares para viajar con niños y actividades especiales para familias.
---
```
layouts/_default/single.html:
```
{{ define "main" }}
  <h1>{{ .Title }}</h1>

  {{ with .GetTerms "categories" }}
    <p>Categories:
      {{ range . }}
        <a href="{{ .RelPermalink }}">{{ or .Params.name .Title }}</a>
      {{ end }}
    </p>
  {{ end }}

  {{ .Content }}
{{ end }}
```
And finally, adding another category to the post that doesn't have a backing metadata file:

posts/secretos-de-albarracin-pueblo-mas-bonito-teruel.md
```
---
title: Secretos de Albarracín, el pueblo más bonito de Teruel
date: 2024-03-19T09:50:07-07:00
categories: 
  - viajes-en-familia
  - other-categoria
---
```
Without permalink configuration:
```html
  <main>    
  <h1>Secretos de Albarracín, el pueblo más bonito de Teruel</h1>

    <p>Categories:
        <a href="/categories/viajes-en-familia/">En familia</a>
      
        <a href="/categories/other-categoria/">Other Categoria</a>
    </p>
  </main>
```

Adding `[permalinks.term]` configuration:

```toml
[permalinks.taxonomy]
categories = "/categorias"

[permalinks.term]
categories = "/categorias/:slug"
```
```html
  <h1>Secretos de Albarracín, el pueblo más bonito de Teruel</h1>

    <p>Categories:
      
        <a href="/categorias/">En familia</a>
      
        <a href="/categorias/other-categoria/">Other Categoria</a>

    </p>
  </main>
```

So, in the default configuration, the raw permalink term (viajes-en-familia) somehow manages to get slug portion of the rendered `.RelPermalink`. 
If configuring `[permailnks.term]`, the raw category term gets ignored, and only slug or title properties in frontmatter appear to be used. This is insconsistent, since other categories not backed by frontmatter file still use the raw category term (other-categoria).

Hope I managed to express it clearly. Thanks!!
