### ISSUE TITLE
multilingual multihost: Branch bundle resource inadvertently  published to other language when content and resource have the same file name

### ISSUE THREAD

**Issue by ov** [gohugoio/hugo#12320]
I have a multilingual multihost site, so different languages are rendered to different domains (and so folders in `public`). The content for different languages is completely independent, just some layouts, partials and shortcodes are shared.

Starting from v0.123 I see that some content is "leaking" from one language to another. Say I have this:

```
content
├── en
│   └── folder
│       ├── subfolder
│       │   └── file.php
│       └── xxx.php
└── ru
    └── folder
        └── subfolder
            └── file.php
```

The config is:

```toml
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
	[languages.en]
		baseURL = "https://site.com/"
		languageName = "English"
		contentDir = "content/en"
		staticDir = "static/en"
	[languages.ru]
		baseURL = "https://site.ru/"
		languageName = "Russian"
		contentDir = "content/ru"
		staticDir = "static/ru"
```

The generated sites structure looks like this:

```
public
├── en
│   └── folder
│       ├── subfolder
│       │   └── file.php
│       └── xxx.php
└── ru
    └── folder
        ├── subfolder
        │   └── file.php
        └── xxx.php
```

Note that `xxx.php` has leaked to the other language site. This didn't happen in `v0.122.0`, it started in `v0.123.0` and can be reproduced in `latest`.

The sites have multiple pages, but this only happens to "resources", not html or markdown files. I see it happens to php files in `v0.123.0`, but if switching to `latest` it starts affecting images in folders without html or markdown files. Looks like it's getting worse.

I see some similar issues around, but they are mostly related to "shared" translations where the resources are mixed with multilingual html content. In my case the content is completely separate, assuming no "leaking" should ever happen.

Any ideas?

Thank you!

### What version of Hugo are you using (`hugo version`)?

This started with v0.123.0 and still happens in `latest`. Works fine in v0.122.0

### Does this issue reproduce with the latest release?

Yes
