### ISSUE TITLE
Page resource is ignored if primary languages `index.md` is a draft or does not exist

### ISSUE THREAD

**Issue by jneidel** [gohugoio/hugo#12476]
## Description

Configuration:

```toml
# in config/_default/config.toml
defaultContentLanguage = "en"

# config/_default/languages.en.toml
languageCode = "en"
weight = 1

# config/_default/languages.de.toml
languageCode = "de"
weight = 2
```

I have a file structure with local image assets alongside the markdown:
```txt
content
├── misc
    └── page
        ├── index.de.md              --> draft: false
        ├── index.md                 --> draft: true
        ├── file.png
        └── file.jpg
```

If I include `--buildDrafts` everything is fine.
If I don't `/de/misc/page` gets created, but the images are missing.

**Asset creation seems to be linked to the visibility/draft status of the `defaultContentLanguage`'s post.
The same behavior applies if the `index.md` file does not exist in the first place.**

### Expected behavior

Assets are being created since they are used in the secondary language post.

## Reproduce

You can reproduce it using [my project](https://github.com/jneidel/blog) on the branch `reproduce-local-assets-ignored`:

```sh
git checkout reproduce-local-assets-ignored
git submodule init
git submodule update
hugo server -p 1313 --navigateToChanged
```

Open [http://localhost:1313/de/misc/sun-minimeal-coin-verkaufen/](http://localhost:1313/de/misc/sun-minimeal-coin-verkaufen/) (there are plenty of broken images around)

### What version of Hugo are you using?

<pre>
$ hugo version
hugo v0.125.5+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

I would expect there to be no difference.
