### ISSUE TITLE
navigation.Page is nil for taxonomy pages (Hugo v0.128.2+)

### ISSUE THREAD

**Issue by hacdias** [gohugoio/hugo#12652]
Hi!

Since Hugo 0.128.2, it seems that the menu navigation is not working as it did before. To be specific, the `pageRef` cannot find pages by their output permalink. Here's a bit of my `config.toml`, where you can see my taxonomies and menu. Note that `/articles` and `/photos` are categories.

```toml
[permalinks]
  tags = '/tags/:title/'
  categories = '/:title/'

[menu]
[[menu.main]]
  name = '🧁 About'
  pageRef = '/about'
  weight = 1
[[menu.main]]
  name = '✉️ Contact'
  pageRef = '/contact'
  weight = 2
[[menu.main]]
  name = '✏️ Articles'
  pageRef = '/articles'
  weight = 3
[[menu.main]]
  name = '📸 Photos'
  pageRef = '/photos'
  weight = 4
[[menu.main]]
  name = '📖 Guestbook'
  pageRef = '/guestbook'
  weight = 5
[[menu.main]]
  name = '🌈 More'
  pageRef = '/more'
  weight = 6
``` 

Here's the code that fails:

``` 
{{ range .Site.Menus.main -}}
  {{ .Page.Permalink }}
{{ end }}
```

With the following error:

```
executing "partials/base/header.html" at <.Page.Permalink>: nil pointer evaluating navigation.Page.Permalink
```

From my tests, it seems that `.Page` is now nil for `/articles` and `/photos`, where it used to be correctly populated. The workaround is to just change it to `/categories/articles` and `/categories/photos`. That way didn't work before 0.128.2, but seems to be necessary now.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.128.2+extended darwin/arm64 BuildDate=2024-07-04T08:13:25Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes, it is a new issue since 0.128.2. Since commit 8cf96f2 to be exact.
