### ISSUE TITLE
One file generates two pages and is duplicated in categories, tags and archives.

### ISSUE THREAD

**Issue by note4** [gohugoio/hugo#12685]
![image](https://github.com/user-attachments/assets/c9b448df-106e-4105-9d20-101a96b7cd6e)

一个文件生成两个页面，并且在分类、标签和归档中重复出现。
One file generates two pages and is duplicated in categories, tags and archives.

内容会自动重复生成，且路径不同，如果配置了 url 就会有路径和内容一样的两个页面。config.yml配置如下：

The content will be automatically duplicated sheng generation, and the path is different, if you configure the url will have the same path and content of the two pages. config.yml configuration is as follows:

```

defaultContentLanguage: zh
defaultContentLanguageInSubdir: false

taxonomies:
  category: categories
  tag: tags
  series: series

permalinks:
  posts: "/log/:filename/"
  categories: "/:slug/"
  tags: "/tags/:slug/"
  series: "/series/:slug/"
  
languages:
  zh:
    languageName: "中文"
    weight: 1
    contentDir: "content/zh"
```

文件路径如下：
The file path is as follows:
![image](https://github.com/user-attachments/assets/68ee4d18-0d48-414c-b273-4a11c8484b8b)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.1+extended darwin/amd64 BuildDate=unknown VendorInfo=macports
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by note4** [comment]
@bep 

发现一个问题，不改变以下配置：
Found a problem without changing the following configuration:

```
defaultContentLanguage: zh
defaultContentLanguageInSubdir: false

languages:
  zh:
    languageName: "中文"
    weight: 1
    contentDir: "content/zh"
```

如果将中文内容存放路径为`content\zh\posts`会将同一内容生成两次。

If you change the path of Chinese content to `content\zh\posts`, the same content will be generated twice.

如果将中文内容存放路径改为`content\posts`就不会将同一内容生成2次。

If you change the Chinese content path to `content\\posts`, the same content will not be generated twice.

测试环境 hugo 版本：

Test environment hugo version:

Windows 11 `hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended windows/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=gohugoio`

macOS `130`
