### ISSUE TITLE
Security Directives in security.toml Not Recognized by Hugo When Placed in config/_default Folder

### ISSUE THREAD

**Issue by fmaida** [gohugoio/hugo#12752]
I have a blog that hosts its configuration not in a `config.toml` file, but inside a `config/_default` folder. I had to add directives to manage security, but if I add them as a `security.toml` file inside `config/_default`, they don't seem to be recognized by Hugo. However, if I insert them into the `config/_default/config.toml` file, they do work.

## What I did

I was in the terminal, inside my home directory. I tried to create a new post on my Hugo website and edit it with my editor of choice (Helix), so I wrote:

```sh
hugo new --source /Users/Cesco/Documents/Progetti/HTML-CSS/retroblog.it blog/gigetto/index.md --editor hx
```

Hugo gave me this error message, claiming that the command 'hx' is not whitelisted:

```sh
Content "/Users/Cesco/Documents/Progetti/HTML-CSS/retroblog.it/content/blog/gigetto/index.md" created
Editing "/Users/Cesco/Documents/Progetti/HTML-CSS/retroblog.it/content/blog/gigetto/index.md" with "hx" ...
Error: access denied: "hx" is not whitelisted in policy "security.exec.allow"; the current security configuration is:

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']

  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
```

So as prompted I wrote a small portion of code to tackle the security problem:

```toml
[security]
    enableInlineShortcodes = false

    [security.exec]
        allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', ' postcss$', '^tailwindcss$', '^hx$']
        osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE)$']
```

## Here my problems begins...

My Hugo blog does not have a `config.toml` file in the root. Instead, I opted for a **"Config directory approach"**, because it seems more clear to me. So my project root looks like this:

```sh
config
archetypes
resources
content
public
layouts
static
assets
themes
```

Inside the `config` directory I have a subfolder named "_default":

```sh
config
└── _default
    ├── config.toml
    ├── languages.it.toml
    ├── markup.toml
    ├── menus.it.toml
    ├── module.toml
    ├── params.toml
    └── taxonomies.toml
```

I tried to create a `security.toml` file inside `config/_default`, but Hugo seems to ignore it.
In order to get it working I had to add the security configuration part to config.toml

I'm not sure if this is a bug or not

### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.131.0+extended darwin/amd64 BuildDate=2024-08-02T09:03:48Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes
