### ISSUE TITLE
v0.131.0  Permalinks tokens break previous behavior

### ISSUE THREAD

**Issue by MichaelSasser** [gohugoio/hugo#12918]
Permalinks tokens are extremely useful, and I had a couple of places, they would be beneficial. Tere is currently just one issue. They break most of my page.

```plaintext
Error: error building site: render: error expanding "/wiki/Foo:Bar_Baz": permalink ill-formed
```

Instead of running a full-blown wiki, we went with doing that in hugo. To get roughly the same behavior as Wikipedia would, I used the same URL style. This includes colons in the URL.

Since I couldn't find anything where I could transform the `title` into it, I added `url` to every wiki page like the following.

```yaml
# without whitespace
title: "Help:Infobox"
url: "/wiki/Help:Infobox"

# with whitespace 
title: "Foo:Bar Baz"
url: "/wiki/Foo:Bar_Baz" 

# with whitespace but without colons 
title: "Foo Bar"
url: "/wiki/Foo_Bar" 

# without whitespace but without colons 
title: "Foo"
url: "/wiki/Foo" 
```

Because I was unable to find any workarounds and I consider the wiki URL to be a key feature, I can't upgrade to >= v0.131.0.

Would it be possible to add something like a raw `url` feature to hugo that behaves like `url` did prior to v0.131.0? 
Alternatively, if that use case would be interesting for others, something like a `:wikititle` permalink token, that would replicate the behavior I'm looking for (e.g. do the same as `:title` would, but replace whitespace with underscores and keep the letter case)?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.135.0+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes
