### ISSUE TITLE
`watch` not working on custom output template

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#13014]
https://github.com/user-attachments/assets/095bf93f-4e4f-4967-bec8-e4b0daf85ecb

### Reproducer

```yaml
// hugo.yaml
outputFormats:
  SearchIndex:
    baseName: 'Search'
    isPlainText: true
    mediaType: 'application/json'
    noAlternative: true

outputs:
  home:
    - HTML
    - SearchIndex
```

```html
// layouts/_default/index.searchindex.json
{{ partial "index.json" . }}
```

```html
// layouts/partials/index.json
{{ $data := dict
  "version" 1
}}
{{ jsonify $data }}
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.137.0-59c115813595cba1b1c0e70b867e734992648d1b+extended linux/amd64 BuildDate=2024-11-04T16:04:06Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.
