### ISSUE TITLE
the extension of goldmark, passthrough has problem in rendering the tableOfContents

### ISSUE THREAD

**Issue by Ceritor-Hanio** [gohugoio/hugo#13079]
I used LaTex to write my tableOfContents, but when I enabled the passthrough, my tableOfContents was broken. 
the code in my config.yaml:
```
markup:
    tableOfContents:
        endLevel: 4
        ordered: false
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
    defaultMarkdownHandler: 'goldmark'
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
        extensions:
          passthrough: true
          passthrough:
            delimiters:
              block:
              - - \[
                - \]
              - - $$
                - $$
              inline:
              - - \(
                - \)
              - - $
                - $
            enable: true
```
and the pictrue of problem : 
![image](https://github.com/user-attachments/assets/f167e991-de72-450f-bfce-40ee7ad0f592)

when I close the passthrough, my tableOfContents is OK ,but my LaTex in the  content  was broken again....
code:
```
markup:
    tableOfContents:
        endLevel: 4
        ordered: false
        startLevel: 2
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNoStart: 1
        lineNos: true
        lineNumbersInTable: true
        tabWidth: 4
    defaultMarkdownHandler: 'goldmark'
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
```
picture:
![image](https://github.com/user-attachments/assets/ffc655f9-3de3-4847-9c3d-100885095743)

------------------------------------
my environment(hugo is running on my own PC
/):
- win11
- the hugo 0.139
- [hugo-theme-stack-starter](https://github.com/CaiJimmy/hugo-theme-stack-starter)
