### ISSUE TITLE
Reverse the default for publishResources 

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#13087]
I'm in the processing of testing a new JS build feature which, among other things, allows building bundled page resources, and I found myself surprised that the source files were copied to `/public`.

So I had to do this in my home content page:

```yaml
title: Home
build:
  publishResources: false
cascade:
- build:
    publishResources: false
```

The above works, but ... If I'm tangled and surprised by the above behaviour, it's safe to say that others are, too.

One could consider this change to be a breaking one, but I would argue that  having `publishResources: false`  to be the default would be the most secure and least confusing setting.
