### ISSUE TITLE
Support for Custom HTML Components in Hugo Blocks

### ISSUE THREAD

**Issue by KejiaZhang-Robust** [gohugoio/hugo#13097]
While experimenting with Hugo to make my website more dynamic and visually engaging, I tried adding a visitor counter widget from [ClustrMaps](https://clustrmaps.com/). In the process, I discovered that custom HTML components can be added within blocks using the following configuration:

```yaml
- block: markdown
    content:
      title: ""
      subtitle: ""
      text: |-
        --- Public Visitors Records ---
        <div style="width: 100%; max-width: 1500px; margin: auto;">
        <script type="text/javascript" id="clstr_globe" src="//clustrmaps.com/globe.js?d=7zdSSXKi7eBcGoD5h7qJBRW5YdwaXxGApcIULBWJ4Tw"></script>
        </div>
```

As someone without much experience with the underlying technical details, I found this method surprisingly easy to implement and really helpful. It allowed me to add a useful feature to my site without diving too deeply into complex configurations.
