### ISSUE TITLE
`transform.ToMath` output not included in Table of Contents

### ISSUE THREAD

**Issue by nathom** [gohugoio/hugo#13118]
I have set up build time LaTeX compilation with the following options:

```toml
# hugo.toml
[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\\[', '\\]'], ['$$', '$$']]
inline = [['\\(', '\\)'], ['$', '$']]
```

And in `layouts/_default/_markup/render-passthrough-block.toml`:

```
{{ $opts := dict "displayMode" true "output" "html" }}
{{ transform.ToMath .Inner $opts }}
```

`layouts/_default/_markup/render-passthrough-inline.toml`:

```
{{ $opts := dict "displayMode" false "output" "html" }}
{{ transform.ToMath .Inner $opts }}
```

This correctly renders math, including in the headers. However, when `.TableOfContents` renders, the math is omitted. e.g. if the heading is `$\epsilon$-greedy`, it will render as `-greedy`.

I also tried writing a custom table of contents partial like so:

```
{{- $headings := . -}}
{{- if gt (len $headings) 0 -}}
  <ul>
  {{- range $headings }}
    <li>
      <a href="#{{ .ID }}">{{ .Title | markdownify }}</a>
      {{- if .Headings }}
        {{ partial "custom_toc.html" .Headings }}
      {{- end }}
    </li>
  {{- end }}
  </ul>
{{- end }}
```

and this has the same issue. Maybe there is some text filter that removes the rendered LaTeX from `.Title`?

I previously set up my website with LaTeX rendering on the client side, and had no such issues.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.139.2+extended+withdeploy darwin/arm64 BuildDate=2024-11-23T15:33:51Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?

Yes
