### ISSUE TITLE
Restrict re-naming of bundled resources to be a relative path

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#13113]
For some work I'm doing now, I notice that we don't put any restriction on the renaming of bundled resource in front matter.

A bundle resource in a sub folder is being set as `subfolder/myresource.txt`; so forward slashes and no leading slash (this is a relative path).

But you're then allowed to add leading slash to it with this if you want:

```
---
title: "My Bundle"
resources:
- name: /foo/bars.txt
  src: foo/txt1.txt
- name: foo/bars2.txt
  src: foo/txt2.txt
```

Note that I don't think the above is very common, but it will make my situation easier if we can:

* Remove any leading slashes from the new `name`.
* Also convert any Windows slashes to Unix style.

https://gohugo.io/content-management/page-resources/
