### ISSUE TITLE
Comment in yaml-codeblock won't generate html

### ISSUE THREAD

**Issue by hmaier-dev** [gohugoio/hugo#13152]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.139.4+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes, it does.

When using the string:
```
# more publishable markdown files...
```
in a yaml-codeblock, like this
```yaml
      - name: Copy over new files
        run: |
            # Whitelist of all publishable wiki articles
            cp index.md $content
            # more publishable markdown files...
```
instead of the block an `e>` gets generated. When removing the comment, everything works fine. I also tried different strings with which, it sometimes worked and sometimes not. I cannot guess pattern, when the error occurs.

Also there is no special output when building the site. I guess there is something wrong with `goldmark` but I do not fully understand how `hugo` uses `goldmark`. So I'm approaching you guys at first.

Thanks for your time. I would be happy to provide more information on this issue.
