### ISSUE TITLE
Add config build.errors.missingShortcodeTemplateErrorLevel

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#13165]
This would be especially handy when developing a new theme for some content, you would then say:

```toml
[build]
  [build.errors]
     missingShortcodeTemplateErrorLevel="info"
```

Valid values would be `info`, `warn`, `error`; default `error`.
