### ISSUE TITLE
Build with --contentDir doesn't build the section listing page

### ISSUE THREAD

**Issue by vmesel** [gohugoio/hugo#13413]
Hey! I'm trying to build a huge Hugo website (130k pages - single language) through different build commands so I don't need to run a site build every time I need to update a new file.

I'm still trying to figure out the correct approach to do this, but something I noticed is that if I build the section posts using the following command:

```
hugo build --contentDir content/posts/ --destination /tmp/posts --logLevel debug --minify
```

I don't find the section index.html, just the website homepage.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.142.0+extended+withdeploy darwin/arm64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes

**Comment by vmesel** [comment]
Hey @jmooring thank you for the help! I wasn't able to find anything regarding segments before. Saved my day!

**Comment by vmesel** [comment]
Hey @jmooring thank you for the help, although the command works, it's not so obvious its usage.

I have a website where we define the routes on the files, but the file structure is quite different.

```
destinations/ -> section
destinations/content1.md -> subpage but with the url defined as `/from/citya/to/cityb`
destinations/content2.md
routes/ -> section
routes/conten1.md -> subpage with the url defined as `/from/citya/
```

When trying to use the segments settings, I wasnt able to make it build all the pages.

```toml
baseURL = 'https://doesntmatter.com/'
languageCode = 'pt-br'
title = 'Doesnt Matter'
defaultContentLanguage = 'pt'

enableRobotsTXT = true

[languages]
  [languages.pt]
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português'
    weight = 1

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = 0.5

[outputFormats.SITEMAP]
  MediaType = "application/xml"
  BaseName = "sitemap"
  IsHTML = false
  IsPlainText = true
  noUgly = true
  notAlternative = true
  Rel = "sitemap"

[outputs]
  home = ['html']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss', 'sitemap']
  taxonomy = ['html']
  term = ['html']

[segments]
  [segments.home]
    [[segments.home.includes]]
      kind = '{home,term,categories,posts}'
      path = '{/}'

  [segments.routes]
    [[segments.routes.includes]]
    path = '{/routes, /routes/**}'
  
  [segments.destinations]
    [[segments.destinations.includes]]
    path = '{/destinations, /destinations/**}'
```

Command used to build:
```
hugo build --minify --gc --logLevel=debug --renderSegments destination --destination /tmp/destination
```


But for some reason not all of the pages are being built, we have 26k pages that would have been built with this, but just 2k were on the output.
