### ISSUE TITLE
Provide default values for .Site.Params used in a theme

### ISSUE THREAD

**Issue by chipsenkbeil** [gohugoio/hugo#1344]
Is there a way to do this with the current setup? I am creating a theme where colors are injected from associated variable values. I'd like to be able to assume that there is always a value for a configuration (in same vein as [Typesafe Config](https://github.com/typesafehub/config#how-to-handle-defaults)), rather than hard-coding a value every time I access the variable. If there is a best practice for doing this, please let me know!

**Comment by bep** [comment]
No, but it should be.

**Comment by rcsenkbeil** [comment]
@bep, did you have any thoughts on how you would do this? My thoughts were that you could either:

1. Make use of `theme.toml` to place any default values (downside is that some variables are already in use within `theme.toml`)
2. Add a `config.toml` in the theme's root directory that contains default values
3. Add a `default.toml` in the theme's root directory that contains default values

Any default value could be overridden in the user's `config.toml` (or other accepted file type).

E.g.
someTheme/defaults.toml

```toml
[Params]
    name = "Some default"
    color = "#FFF"

    [Params.Extra]
        size = "30px"
```

someSiteUsingTheme/config.toml

```toml
[Params]
    name = "Some user name"

    [Params.Extra]
        size = "45px"
```

Results in `Params.name` being _"Some user name"_, `Params.color` being _"#FFF"_, and `Params.Extra.size` being _"45px"_.
