### ISSUE TITLE
Templates in /content

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#13543]
This is mostly a documentation issue, but I write it down while I think about it.

With #13541 -- this should be possible/practical:

```toml
[module]
  [[module.mounts]]
    excludeFiles = '{single,list}.*'
    source = 'content'
    target = 'content'
  [[module.mounts]]
    includeFiles = '{single,list}.*'
    source = 'content'
    target = 'layouts'
```

**Comment by jmooring** [comment]
> this should be possible/practical

This works fine...

```text
content/
├── posts/
│   ├── post-3/
│   │   ├── bryce-canyon.jpg
│   │   ├── index.md
│   │   └── single.html  <-- used to render posts/post-3, does not affect other content
│   ├── _index.md
│   ├── post-1.md
│   └── post-2.md
└── _index.md
```

```toml
[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
excludeFiles = "**/{single,list}.*"
source = "content"
target = "content"

[[mounts]]
includeFiles = "**/{single,list}.*"
source = "content"
target = "layouts"
```

We can close this issue as resolved with #13541.

I'm waffling on whether to document this. While it works as expected, it also blurs the lines between component directories. Also, when troubleshooting a site or theme (e.g., cloning a site referenced in a forum topic), we may have to look in several places to find a particular template.
