### ISSUE TITLE
Feature request: multilingual author profiles

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/hugo#2467]
Some content creators might blog in multiple languages. Consequently I would be nice to translate certain author informations as well, like in an "About me" section at the end of an article. 

Otherwise, the content creators
1. are either bound to a single language
2. have to maintain multiple author profiles with redundant information
3. or have to use params to create some kind of workaround

Alternatively, authors could add language-specific containers to their author's profile in which they can overwrite default values - much like the current multilingual setup in config files. 

Authors, whose native language doesn't use the latin alphabet could now write their name with a different character set, e.g. in Chinese, Arabic or Japanese.

Example:

``` toml
# file: data/_authors/john.toml

# The following information are the default values
givenName    = "John"
familyName   = "Doe"
displayName  = "John Doe"
shortBio     = "I blog about interesting stuff"
bio          = "An extended biography..."

# de has to match the language prefix from the config file
# shortBio and bio of this section replace the values above in the German version
[languages.de]
shortBio     = "Ich blogge über interessantes Zeug"
bio          = "Ausführliche Biographie..."
```
