### ISSUE TITLE
Currency and number formatting in hugo

### ISSUE THREAD

**Issue by kishaningithub** [gohugoio/hugo#2799]
Im not sure on how to do this in hugo and hence this could be  treated as a question
Say i have front matter for a "product" like this
```toml
+++
name = "Awesome android phone"
price = "13500"
priceunit = "INR"
+++
```
I want the price info to be displayed something like this
```
  13,500 ₹
```
Note the `Currency display` and `comma separation`

How do i do this? Im using the latest version 0.17
