### ISSUE TITLE
Nested array in archetype results in empty frontmatter

### ISSUE THREAD

**Issue by marcguyer** [gohugoio/hugo#3172]
If an archetype has a nested list, you use `hugo new` to create new content based on that archetype, the resulting content file frontmatter is empty. This worked in 0.16 but hasn't worked since. For example, the following archetype fails:

```toml
+++

[[showtimes]]
    time = "2016-01-01T19:30:00"
    tickets = ""
[[showtimes]]
    time = "2016-01-02T19:30:00"
    tickets = ""

+++
```

To replicate, you can use [this repo](https://github.com/bppwrite/bppwrite.github.io), then run `hugo new show/2016-2017/test-show/index.md`.

This has been tested on the latest HEAD with go 1.8 on macos Sierra. See [this discussion](https://discuss.gohugo.io/t/error-creating-content-with-map-in-archetype) for some additional commentary.
