### ISSUE TITLE
Setting mediaType suffix to "" leaves dot

### ISSUE THREAD

**Issue by hatched** [gohugoio/hugo#3471]
In upgrading from Hugo 0.17 to 0.20.7 I had to make a few modifications to the RSS generation. The RSS on my site resides at `/rss`.

Thanks to https://discuss.gohugo.io/t/how-can-i-change-the-rss-url/118/17 I was able to find the missing fields in my toml to get it to properly generate only a single `rss.xml` file. However when I try to set the suffix to "" the generated file is `rss.` 

```TOML
[outputs]
  home = [ "RSS"]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "rss"

[mediaTypes]
[mediaTypes."application/rss"]
  suffix = ""
```
