### ISSUE TITLE
hugo new type/text.md fails

### ISSUE THREAD

**Issue by tubia** [gohugoio/hugo#359]
Hi,  
I use hugo 0.11 in Linux Mint 17.  
I'm trying to use the new features like archetypes.

Actually I'm not able to create new contents using the builder based on archetypes. This is the result:

```
tubia@mypc:~/newsite$ hugo new posts/newtest.md -v
INFO: 2014/07/11 Using config file: /home/tubia/newsite/config.toml
INFO: 2014/07/11 attempting to create posts/newtest.md of posts
ERROR: 2014/07/11 EOF
```

This is `config.toml` :

``` toml
baseurl = "http://yourSiteHere"
languageCode = "it-IT"
title = "New Site"
[Taxonomies]
    tag = "tags"
    category = "categories"
    rassegna = "rassegne"
    genere = "genere"
    luogo = "luogo"
```

This is `archetypes/posts.md` :

``` yaml

---
locandina: "link.jpg"
regista: "Pippo"
year: 1995
genere: "doc"
rassegne: "x"
dataevento: 2014-06-28T18:00:00
luogo: "home"

---
```
