### ISSUE TITLE
Hugo doesn't generate secondary languages in single page mode

### ISSUE THREAD

**Issue by chreble** [gohugoio/hugo#3653]
`Hugo` doesn't generate secondary languages when used in `everything as a page` [mode](https://gohugo.io/content/using-index-md/).

Here's our current directory structure:

```.
├── config.toml
├── content
├── data
├── i18n
├── layouts
├── public
└── static
```

### config.toml

```toml
baseURL = "/"
sectionPagesMenu = "main"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[Languages]
[Languages.fr]
languageCode = "fr-fr"
weight = 0
description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit"
keywords = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat"

  [[Languages.fr.menu.main]]
  url    = "/fr"
  name   = "home"
  weight = 10

  [[Languages.fr.menu.main]]
  url    = "/fr/services/"
  name   = "les services"
  weight = 20

  [[Languages.fr.menu.main]]
  url    = "/fr/bubbles/"
  name   = "les bubbles"
  weight = 30

  [[Languages.fr.menu.main]]
  url    = "/fr/contact/"
  name   = "contact"
  weight = 40

[Languages.en]
title = "The Bubbles Company"
languageName = "English"
languageCode = "en-us"
weight = 1

  [[Languages.en.menu.main]]
  url    = "/en"
  name   = "home"
  weight = 11

  [[Languages.en.menu.main]]
  url    = "/en/services/"
  name   = "the services"
  weight = 21

  [[Languages.en.menu.main]]
  url    = "/en/bubbles/"
  name   = "the bubbles"
  weight = 31

  [[Languages.en.menu.main]]
  url    = "/en/contact/"
  name   = "contact"
  weight = 41
```

### `layouts` directory structure

```.
├── index.html
├── partials
│   ├── bubbles
│   │   ├── demo.html
│   │   ├── header.html
│   │   ├── s1.html
│   │   └── two.html
│   ├── contact
│   │   ├── form.html
│   │   └── page.html
│   ├── footer.html
│   ├── header.html
│   ├── index
│   │   ├── 01-block.html
│   │   ├── 02-block.html
│   │   ├── 03-block.html
│   │   ├── 04-block.html
│   │   ├── 05-block.html
│   │   └── dots.html
│   ├── menu.html
│   ├── services
│   │   ├── 01-block.html
│   │   ├── 02-block.html
│   │   ├── 03-block.html
│   │   ├── demo.html
│   │   └── header.html
│   └── social.html
└── section
    ├── bubbles.html
    ├── contact.html
    └── services.html
```

### `content` directory structure
```content
├── bubbles
│   └── _index.md
├── contact
│   └── _index.md
└── services
    └── _index.md
```

### Hugo output
```$ hugo
Started building sites ...
Built site for language fr:
0 draft content
0 future content
0 expired content
0 regular pages created
8 other pages created
0 non-page files copied
0 paginator pages created
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
2 other pages created
0 non-page files copied
0 paginator pages created
```

As you can see above it only creates `2` other pages for `en` language while it correctly generates the pages for the `main` language.

### Version
```Hugo Static Site Generator v0.24.1 darwin/amd64 BuildDate: 2017-06-26T14:10:47+02:00```
