### ISSUE TITLE
Page-specific sitemap frontmatter is not respected

### ISSUE THREAD

**Issue by mcknco** [gohugoio/hugo#3704]
I believe this is connected to #2622, on v0.25 my sitemap.xml ignores any attempt to override the default values on a page by page basis. Adding something like
```
changefreq: "monthly"
priority: 0.5
```
to a page's frontmatter has no effect, whether it's an _index.md or otherwise. Can anyone reproduce this? I'm curious to hear!

**Comment by gldraphael** [comment]
You need to override the variables under the sitemap field. For yaml it'll be like:

```yaml
sitemap:
  changefreq: "monthly"
  priority: 0.5
```

For toml:

```toml
[sitemap]
  changefreq = "monthly"
  priority = 0.5
```
