### ISSUE TITLE
language is recognized but strings aren't translated

### ISSUE THREAD

**Issue by matteosuppo** [gohugoio/hugo#3748]
We are having an issue creating a localized site: I created a minimal repo that reproduces the problem. Not sure if it's a problem of configuration or other. It works fine for english

https://github.com/matteosuppo/hugo-bug

Also your tutorial may be broken ^^ http://gohugo.io/tutorials/create-a-multilingual-site/

**Comment by mpcabd** [comment]
Multilingual site tutorial is under https://gohugo.io/content-management/multilingual/

As for your problem it's solved once you define a `defaultContentLanguage` in your configuration:

```
...
defaultContentLanguage: "ja"
...
```

This solved it when I tested it for your case.

![image](https://user-images.githubusercontent.com/644992/28798932-8f2c47d4-7646-11e7-9551-5515883e3df2.png)

**Comment by mpcabd** [comment]
Actually I was mistaken, I noticed a lot of issues later on.

1. Mainly you're using `jp` for the language code, but it should be `ja`, which you have noticed because you called the file under `i18n` as `ja.yaml`.
2. In your `themes/test/layouts/index.html` you had `{{.Site.LanguageCode}}` but you should have used `{{.Site.Language}}` because the variable `{{.Site.LanguageCode}}` doesn't change when you switch languages. Maybe it's a bug, but that's what I noticed.
3. You were missing the {{Languages}} part of your config, which tells Hugo that your site is a multilingual site, so I added it:

```
baseurl: "http://localhost:1313/ja/"
languageCode: "en"
theme: "test"
preserveTaxonomyNames: "true"
enableMissingTranslationPlaceholders: "true"

publishdir: "public/ja"
contentdir: "content/ja"

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: "true"
Languages:
  en:
    title: "Site"
  ja:
    title: "ウェブサイト"
```

4. I don't know why you had `/jp` at the end of the baseURL, but if your aim is to have a multilingual site then you don't have to put `/ja` at the end, it will be automatic. But anyway even if you keep it, with proper configuration it will look like this:

![image](https://user-images.githubusercontent.com/644992/28800576-875459dc-764d-11e7-91eb-edacef4807ef.png)
![image](https://user-images.githubusercontent.com/644992/28800582-8e3990f0-764d-11e7-938e-bf78dceb2d91.png)


The file structure looks like this now:

```
$ tree
.
├── README.md
├── config_ja.yml
├── content
│   └── ja
│       └── test.md
└── themes
    ├── test
    │   ├── i18n
    │   │   ├── en.yaml
    │   │   └── ja.yaml
    │   └── layouts
    │       └── index.html
    └── theme.yml

6 directories, 7 files
```

Hope this helps, I was too lazy to fork your repository and send a pull request though.

**Comment by matteosuppo** [comment]
Thank you, what did the trick was adding:

Languages:
  ja:
    title: "ウェブサイト"

**Comment by smellai** [comment]
Actually this is our case:
https://cdn.arduino.cc/reference/jp/
https://cdn.arduino.cc/reference/en/

we have many categories so we need to keep different configurations files, otherwise a single configuration file would be huge. Here is our configurations:

config_en.yml:
```
baseurl: "http://replace-this-with-your-hugo-site.com/"
languageCode: "en-us"
title: "Arduino Reference"
MetaDataFormat: "yaml"
theme: "arduino"
preserveTaxonomyNames: "true"

publishdir: "public/en"
contentdir: "content/en"

taxonomies:
  category: "categories"
  subCategory: "subCategories"

params:
  description: "The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywords."
  category:
  - name: "functions"
    intro: "For controlling the Arduino board and performing computations."
    subCategories:
    - name: "Main"
    - name: "Digital I/O"
    - name: "Analog I/O"
    - name: "Arduino DUE only"
    - name: "Advanced I/O"
    - name: "Time"
    - name: "Math"
    - name: "Trigonometry"
    - name: "Random Numbers"
    - name: "Bits and Bytes"
    - name: "External Interrupts"
    - name: "Interrupts"
    - name: "Communication"
      child:
      - name: "Serial"
      - name: "Stream"
    - name: "USB (Leonardo and DUE only)"
      child:
      - name: "Keyboard"
      - name: "Mouse"

  - name: "variables"
    intro: "Arduino data types and constants."
    subCategories:
    - name: "Constants"
    - name: "Conversion"
    - name: "Data Types"
    - name: "Variable Scope & Qualifiers"
    - name: "Utilities"

  - name: "structure"
    intro: "The elements of Arduino (C++) code."
    subCategories:
    - name: "Control Structure"
    - name: "Further Syntax"
    - name: "Arithmetic Operators"
    - name: "Comparison Operators"
    - name: "Boolean Operators"
    - name: "Pointer Access Operators"
    - name: "Bitwise Operators"
    - name: "Compound Operators"
```

config_jp.yml:
baseurl: "http://replace-this-with-your-hugo-site.com/"
languageCode: "ja"
title: "Arduinoリファレンス"
MetaDataFormat: "yaml"
theme: "arduino"
preserveTaxonomyNames: "true"

publishdir: "public/jp"
contentdir: "content/jp"

taxonomies:
  category: "categories"
  subCategory: "subCategories"

Languages:
  ja:
    title: "Arduinoリファレンス"

params:
  description: "Arduinoのプログラム言語のリファレンスです．　「関数」，「変数と定数」および「制御文と演算子」で構成されています．"
  category:
  - name: "関数"
    intro: "Arduinoで計算や制御をするための関数"
    subCategories:
    - name: "メイン"
    - name: "デジタル入出力"
    - name: "アナログ入出力"
    - name: "Arduino DUE のみ"
    - name: "応用入出力"
    - name: "時間"
    - name: "数学"
    - name: "三角関数"
    - name: "乱数"
    - name: "ビットとバイト"
    - name: "外部割り込み"
    - name: "割り込み"
    - name: "コミュニケーション"
      child:
      - name: "シリアル"
      - name: "Stream"
    - name: "USB（LeonardoとDUEのみ）"
      child:
      - name: "キーボード"
      - name: "マウス"

  - name: "変数"
    intro: "Arduinoのデータ型と定数"
    subCategories:
    - name: "定数"
    - name: "型変換"
    - name: "データ型"
    - name: "変数のスコープと修飾子"
    - name: "ユーティリティ"

  - name: "構文"
    intro: "Arduinoコード(C++)の要素"
    subCategories:
    - name: "制御文"
    - name: "補足の構文"
    - name: "算術演算子"
    - name: "比較演算子"
    - name: "ブール演算子"
    - name: "ポインタ"
    - name: "ビット演算子"
    - name: "複合演算子"
```

Why we have to specify again ```Languages``` if we already wrote at line 2 `languageCode: "ja"` or `languageCode: "en"` ?

or should we put the categories names in a i18n file in some way?
