### ISSUE TITLE
GitInfo now working on v0.26 macos

### ISSUE THREAD

**Issue by f3l1x** [gohugoio/hugo#3788]
Hi.

- Hugo: `Hugo Static Site Generator v0.26 darwin/amd64 BuildDate: 2017-08-09T07:41:16+02:00`
- OS: MacOS Sierra

I'm trying to use GitInfo but it's not working on any page. 

My config toml file:

```toml
baseurl = "https://f3l1x.io/"
languageCode = "en-us"
title = "..."
enableGitInfo = true
```
I start Hugo with: `hugo server -D -v --enableGitInfo`

And I'm always getting error:

```
ERROR 2017/08/09 08:00:54 Error while rendering "page": template: /data/work/f3l1x/f3l1x/layouts/_default/single.html:50:47: executing "/data/work/f3l1x/f3l1x/layouts/_default/single.html" at <.GitInfo.Hash>: can't evaluate field Hash in type *gitmap.GitInfo
```
