### ISSUE TITLE
Possible bug for menu only defined in config file for multilingual site

### ISSUE THREAD

**Issue by Kitefr** [gohugoio/hugo#3819]
Hello,

I've been trying to add a menu to my website using the multilingual feature.
**The menu always return nil** and after some tests i think this might be a bug.

**I'll explain what i have in my files, the tests i made and the results i got from them.**

I updating my website in version 2.0 as a multilingual site both in English (main language) and French.
- I am using hugo version **0.26** on windows. 
- The menu is **only defined in the config file**.
- There is **no** `sectionPagesMenu` setting in the config. 

First, here is my config.toml file:
```toml
baseURL = "http://www.siteurl.com"
metaDataFormat = "yaml"
footnotereturnlinkcontents = "↩"
copyright = "Copyright &copy; 2017"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

theme = "ysart"

# I18n
[Languages]

# English
[Languages.en]
title = "English Title"
weight = 1
languageName = "English"
languageCode = "en-us"
Author = "Yann Schmidt"
Email = "contact@yannschmidt.com"
MediaDir = "/medias/"

[[languages.en.menu.main]]
name = "Games"
identifier = "games"
url = "/games/"
weight = 1

[[languages.en.menu.main]]
name = "Shorts"
identifier = "shorts"
url = "/shorts/"
weight = 2

[[languages.en.menu.main]]
name = "Lab"
identifier = "lab"
url = "/lab/"
weight = 3

[[languages.en.menu.main]]
name = "Illustrations"
identifier = "illustrations"
url = "/illustrations/"
weight = 4

[[languages.en.menu.main]]
name = "Scripts"
identifier = "scripts"
url = "/scripts/"
weight = 5

[[languages.en.menu.main]]
name = "Store"
identifier = "store"
url = "/store/"
weight = 6

[[languages.en.menu.main]]
name = "Contact"
identifier = "contact"
url = "/contact/"
weight = 7


# French
[Languages.fr]
title = "French Title"
weight = 2
languageName = "Français"
languageCode = "fr"
Author = "Yann Schmidt"
Email = "contact@yannschmidt.com"
MediaDir = "/medias/"

[[languages.fr.menu.main]]
name = "Games"
identifier = "games"
url = "/games/"
weight = 1

[[languages.fr.menu.main]]
name = "Shorts"
identifier = "shorts"
url = "/shorts/"
weight = 2

[[languages.fr.menu.main]]
name = "Lab"
identifier = "lab"
url = "/lab/"
weight = 3

[[languages.fr.menu.main]]
name = "Illustrations"
identifier = "illustrations"
url = "/illustrations/"
weight = 4

[[languages.fr.menu.main]]
name = "Scripts"
identifier = "scripts"
url = "/scripts/"
weight = 5

[[languages.fr.menu.main]]
name = "Store"
identifier = "store"
url = "/store/"
weight = 6

[[languages.fr.menu.main]]
name = "Contact"
identifier = "contact"
url = "/contact/"
weight = 7

```
As you can see, my config is pretty simple.
And i use the default menu template for multilingual site shown in hugo documentation:
```html
<ul>
    {{- $currentPage := . -}}
    {{ range .Site.Menus.main -}}
    <li class="{{ if $currentPage.IsMenuCurrent "main" . }}active{{ end }}">
        <a href="{{ .URL | absLangURL }}">{{ .Name }}</a>
    </li>
    {{- end }}
</ul>
```
But debugging the menu return `nil` for the `.Site.Menus.main`.

So i made 2 tests, others where meaningful:
1. I added the `sectionPagesMenu` to the config file. The menu is shown but this is just all the sections from the content directory (which is the normal behavior for this setting) in alphabetical order. It doesn't take the menu items' weight in the config file.
2. I removed the `sectionPagesMenu` and tried the setup a few items without multilingual, **just inside `[[menu.main]]` and the menu works !**

So i have a reason to believe menus in config file in a multilingual site settings does not work as it should be.

Can some reproduce this ?
