### ISSUE TITLE
Translations don't work for `pl` lang code

### ISSUE THREAD

**Issue by skix123** [gohugoio/hugo#3846]
Hi, when using i18n for language `pl` (polish) it doesn't work properly. Example:

`/layouts/index.html`:
```html
Single: {{ i18n "authorsLabel" 1}} 
Plural: {{ i18n "authorsLabel" 2}}
```

`/i18n/en.yaml`:
```yaml
authorsLabel:
    one: "Author"
    other: "Authors"
```

`/i18n/pl.yaml`:
```yaml
authorsLabel:
    one: "Autor"
    other: "Autorzy"
```

When using english (`en`) it works ok:
```html
Single: Author
Plural: Authors
```

... but for polish (`pl`):
```html
Single: Autor
Plural: authorsLabel // <----
```

What is interesting, when I change the language code from `pl` to - for example - `fr` or `es` it works perfectly.

I tried `pl`, `pl_PL`, `pl-PL` but with no success.

I'm using `Hugo Static Site Generator v0.26 darwin/amd64 BuildDate: 2017-08-24T21:20:38+02:00` on macOS.
