### ISSUE TITLE
Clearer Overriding or Params in Multilingual Mode

### ISSUE THREAD

**Issue by MunifTanjim** [gohugoio/hugo#3871]
**Hugo version: 0.26**

## `config.toml`:

```toml
[params]
description = "Site Description"

[languages.de.params]
description = "DE Site Description"
```
## Expected Behavior

While rendering the site for `en`:

`.Site.Params.description` should return `Site Description`

While rendering the site for `de`:

`.Site.Params.description` should return `DE Site Description`

## Current Behavior

`.Site.Params.description` always returns `Site Description`

While rendering the site for `de`:

`.Site.Params.params.description` returns `DE Site Description`

---

This issue was previously mentioned in #3346 & #2615

**Comment by bep** [comment]
Try:

```
[params]
description = "Site Description"

[languages.de]
description = "DE Site Description"
```

Which is the intended design.

**Comment by MunifTanjim** [comment]
I find it a little bit of confusing. Because, I can override both `params` and root level site variable (e.g. `title`) from the same level. This example should explain it:

```toml
title = "Title" # not inside params

[params]
description = "Site Description" # inside params

[languages.de]
# overriding both from same level
title = "DE Title"
description = "DE Site Description"
```

It would be less confusing if `params` could've been overridden from `[languages.de.params]`. Just a suggestion.

Anyway, thanks :smiley:

**Comment by bep** [comment]
>I find it a little bit of confusing.

Yea, that may be true. I will keep this issue open -- but it is not on my priority list to fix it. If someone wants to spend time on it, feel free.

**Comment by lename** [comment]
I was confused too. 
Anyway we should know, how to be with [params.see_more] and [params.recent_posts]? 

This code: 
```toml
[languages.de]
weight = 2
languageName = "Deutsch"

[languages.de.see_more]
enable = true
icon = "fa fa-file-code-o"
```
doesn't give the expected result.
