### ISSUE TITLE
Multiple config files and menu entries

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#3879]
So, after 0.27 was out, I quickly switched to splitting my configs to reduce duplication.

It worked great except for one thing: menus.

I had this in `config-common.yml`:

```yml
menu:
    main:
        - Name: "A"
          URL: "https://foo.bar/"
          Weight: -10
```

And then I had this in `config-development.yml`

```yml
menu:
    main:
        - Name: "B"
          URL: "https://foo.bar/diff/"
          Weight: 0
```

When I run Hugo with `--config=config-common.yml,config-development.yml` only the "B" menu is showing up; it's like it overwrites `config-common.yml`'s menu entry.

The other menu entries are defined in each page's front matter and are common and they do show up fine.
