### ISSUE TITLE
Bug with i18n & Language Code `pl`

### ISSUE THREAD

**Issue by MunifTanjim** [gohugoio/hugo#3947]
**Test Repo**: https://bitbucket.org/MunifTanjim/hugo-test

**Hugo Version**: v0.29
**OS**: Ubuntu 16.04

### /config.toml
```toml
baseURL = "http://example.org/"
title = "Hugo Test Site"

[languages.en]
lang = "en"
[languages.fr]
lang = "fr"
[languages.pl]
lang = "pl"
```

### /i18n/en.toml
```toml
[test]
one = "test en {{ .Count }}"
other = "test en {{ .Count }}"
```

### /i18n/pl.toml
```toml
[test]
one = "test pl {{ .Count }}"
other = "test pl {{ .Count }}"
```

### /layouts/index.html
```html
<!DOCTYPE html>
<html>

<head>
  <title>{{ .Site.Title }}</title>
</head>

<body>
  <p>{{ i18n "test" 1 }}</p>
  <p>{{ i18n "test" 2 }}</p>
</body>

</html>
```

### localhost:1313/
```
test en 1
test en 2
```

### localhost:1313/pl/
```
test pl 1
test
```

## Description

As you can see, the plural (i.e. `other` part of the i18n file) translation is not being detected when the language code is **`pl`**. But it works for any other language code.

I've reproduced the same bug with Hugo v0.28 & v0.27 too. Didn't tried with older versions than those though.
