### ISSUE TITLE
Menu item with weight of 0 sorts incorrectly

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#4058]
I have the following menu items in my config.toml:

```toml

[[menu.main]]
  name = "Home"
  identifier = "home"
  url = "/"
  weight = 0

[[menu.main]]
  name = "About"
  identifier = "about"
  url = "http://carlmjohnson.net/"
  weight = 1

[[menu.main]]
  name = "Github"
  identifier = "github"
  url = "https://github.com/carlmjohnson/"
  weight = 2

[[menu.main]]
  name = "Twitter"
  identifier = "twitter"
  url = "https://twitter.com/carlmjohnson"
  weight = 3

[[menu.main]]
  name = "Archive"
  identifier = "posts"
  url = "/post/"
  weight = 4
```

Sidebar code is boring:

```html
  <nav>
    <ul>
      {{ range .Site.Menus.main }}
        <li><a href="{{.URL}}"> {{ .Name }} </a></li>
      {{end}}
    </ul>
  </nav>
```

As you can see, "Home" should be the first item in the list. But with Hugo v0.30.2 Darwin, I'm getting Home as the _last_ item in my list. I can workaround this by setting the weight to -1 or by adjusting all weights to start with 1 as the first item, rather than 0. 

My guess is that Hugo is not distinguishing between not having a weight set and having a weight of zero, since zero is the default value for numbers in Go.
