### ISSUE TITLE
Notes: release notes 0.32

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4172]
* The build total in the console is now the ... total (i.e. both the static sync and Hugo build) ... more honest and still plenty fast.

Possible breaking changes:

* images and other static resources in "_index.md" folders will have its `RelPermalink` relative to its page.
* images and other static resources in or below "index.md" folders will have its `RelPermalink` relative to its page (respecting permalink settings etc.)
* content pages in or below "index.md" will not get their own `URL`, but will be part of the `.Resources` collection of its page.
* `.Site.Files` is deprecated
* cssmin removed
* `Page.GetParam`does not lowercase your result anymore. If you really want to lowercase your params, do it with `.GetParam "myparam" | lower` or similar.

Also some notes for the docs:

* resourceDir: Where sto store image resources (default: "resources")

```toml
[imaging]
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "NearestNeighbor"

# Defatult JPEG quality setting. Default is 75.
quality = 67
```

```bash
hugo --gc
```

Previously deprecated that will now ERROR:

* disable404 Use disableKinds=["404"]
* disableRSS  Use disableKinds=["RSS"]
* disableSitemap  Use disableKinds=["sitemap"]
* disableRobotsTXT  Use disableKinds=["robotsTXT"] #
