### ISSUE TITLE
Add front matter metadata for Resources

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4244]
Hugo 0.32 added `Resources` with image processing etc.

It uses naming conventions inside folders to bundle images, pages etc. 

This works great. 

A natural extension to this is to add some resource specific metadata to a page's front matter. Some motivations for this are:

* Add metadata to images etc. (title, description, photographer, license)
*  Make it possible to link in project-relative resources:
    * Reuse images from a photo library, no duplication
    * Allow reuse of content files
    * Also makes it possible to bundle content files in home page etc.

I suggest this simple data structure:

```toml
[[resources]]
title = "My Cool Logo"
description = "Some other text"
 # page relative file reference
src = "mylogo.png"
# All fields will be put into a .Params map
license = "CC BY SA"

[[resources]]
 # Project relative file reference
# This will get the metadata from its own front matter, so no need to add more.
src = "/my-pages/mylogo.md"
```

**Comment by regisphilibert** [comment]
Awesome. And then in your template/shortcodes ?
```
{{ range .Resources }}
    {{ .Params.description }}
{{ end }}
```

**Comment by regisphilibert** [comment]
Also by "page relative file reference", do you means it is directory agnostic. (sorry for the lack of better word). We just use the basename for "src"?

**Comment by bep** [comment]
>Also by "page relative file reference", do you means it is directory agnostic. 

There are two use cases for this:

1. Add metadata to a file in the bundle, so you need a way to link the file with metadata.
2. Add a file reference + metadata to a file outside of the page bundle (for example some media library)

So, given this project:

```bash
├── content
│   └── mybundle
│       ├── index.md
│       └── sunset.jpg
└── photos
    └── logo.png
```

To add metadata to the sunset: `src = "mylogo.png"`and to the logo `src = "/photos/logo.png"`.

This was the first idea I came up with and open to suggestion. But the missing leading slash marks it as a file inside the bundle.

**Comment by regisphilibert** [comment]
Gotcha! Makes sense. 
So 2 pages can use a shared image but assign its own "metadata" to it.

**Comment by bep** [comment]
>So 2 pages can use a shared image but assign its own "metadata" to it.

Yea, but the main motivation for the 2) is to avoid duplication + to be able to pull in content from "other places". It makes the bundle less portable, but may be worth it to some.

**Comment by onedrawingperday** [comment]
I like this syntax because it's simple and easily understood.
```
`[[resources]]`
`title = "My Cool Logo"`
`description = "Some other text"`
 `# page relative file reference`
`src = "mylogo.png"`
`# All fields will be put into a .Params map`
`license = "CC BY SA"`
```
But I also think that maybe we need some kind of front matter separator to group these parameters per `.Resource` image. So that it is possible to add meta data to several images in a Page Bundle.

Is grouping these parameters per image possible? Or is it out of scope for the time being?

**Comment by bep** [comment]
>Is grouping these parameters per image possible? Or is it out of scope for the time being?

That is a good idea. I would imagine all/most photos would have the same photographer/license etc. 

Hmm.

What if `src` can be a string or a slice:

```toml
[[resources]]
title = "My Cool Logo"
description = "Some other text"
 # page relative file reference
src = ["l1.png", "l2.png"]
# All fields will be put into a .Params map
license = "CC BY SA"
```

Maybe also some simple wildcard matching:

```toml
[[resources]]
title = "My Cool Logo"
description = "Some other text"
 # page relative file reference
src = "*.png"
# All fields will be put into a .Params map
license = "CC BY SA"
```

... maybe.

**Comment by regisphilibert** [comment]
Why not both? 
If you endup with 50 pictures, the wildcard makes more sense.
If you only have a few though and only 2 or 3 of them share the same metadata, it may be easier for the content manager to use a slice.

Also I suppose this would work ?

```
[[ resources ]]
author = "Whoever
src = "*.png"

[[resources]]
src = "sunset.png"
description = "nice sunset by the beach"
```

**Comment by onedrawingperday** [comment]
Of course parameters like photographer/licence etc will be the same. But the description could very well be different per image in a Page Bundle.

If we have something like this:
`src = ["l1.png", "l2.png"]`

Maybe there can be an easy way to couple it with something like this:
 `description = ["Description for l1.png", "Description for l2.png" ]`

Also I like what @regisphilibert proposed above.
```

[[ resources ]]
author = "Whoever
src = "*.png"

[[resources]]
src = "sunset.png"
description = "nice sunset by the beach"
```
Whatever you think would be best to implement @bep

**Comment by bep** [comment]
@onedrawingperday we should try to avoid making this too hard to understand, but we should strive for "as little text as possible". 

This would maybe work?

```toml
[[resourceGroups]]
license = "CC BY SA"
[[resources]]
title = "My Cool Logos"
description = "Some other text"
src = ["l1.png", "l2.png"]
[[resources]]
title = "My Other Cool Images"
description = "Some other text"
src = "*.png"
```

WIth a little flexibility in the parsing there the "group" is optional.

**Comment by regisphilibert** [comment]
@bep what's the difference between
```
[[resourceGroups]]
license = "CC BY SA"
```
and
```
[[resources]]
license = "CC BY SA"
src = "*"
```

**Comment by bep** [comment]
I'm thinking out loud here, which  may not make sense. But a `resourceGroup` can have many `resource` definitions. Each `resource` can override params values on the group level if needed.

So:

```toml
[[resourceGroups]]
src = "*.png"
title = "My Image"
license = "CC BY SA"
[[resources]]
title = "My Cool Logos"
src = ["l1.png", "l2.png"]
[[resources]]
title = "My Other Image"
src = "l3.png"
```

In the above every PNG image in the bundle will get the title "My Image" and the CC license, but some will get a custom title.
