### ISSUE TITLE
Hugo not listing subsections in permalink URLs when specified

### ISSUE THREAD

**Issue by coatless** [gohugoio/hugo#4307]
### Background

I'm trying to leverage the [`sections`](https://gohugo.io/content-management/sections/#nested-sections) feature of the [permalinks](https://gohugo.io/content-management/urls/#permalinks).

That is, if we define a permalink structure as:

```toml
[permalinks]
  post = "/:sections/:title/"
```

we should get:

```bash
/posts/subsection/title-of-post
```

### Problem

Without specifying a permalink, I receive the URL structure of: 

```bash
/post/subsection/date-title-of-post
```

Upon creating a custom permalink URL to remove the date:

```toml
[permalinks]
  post = "/:sections/:title/"
```

I then only receive: 

```bash
/post/title-of-post
```

### In application

I have the following `content` directory structure:

```bash
├── A
│   ├── toad
│   ├── goat
├── B
├── C
├── D
├── E
└── F
    ├── toad
    ├── goat
    └── lion
```

I've applied the same scheme to all sections, e.g. 

```toml
[permalinks]
  A = "/:sections/:title/"
  B = "/:sections/:title/"
  C = "/:sections/:title/"
  D = "/:sections/:title/"
  E = "/:sections/:title/"
  F = "/:sections/:title/"
```

Each section is still formatted as if I specified everything as:

```toml
[permalinks]
  some-section = "/:section/:title/"
```

or 

```bash
/A/title
```

instead of:

```bash
/A/toad/title
/A/goat/title
...
```

The YML header for the individual post is specified as:

```yaml
---
title: My Post
author: someguy
date: '2015-09-29 10:40:25 -0700'
date_gmt: '2015-09-29 15:40:25 -0700'
categories: ['A', 'toad']
tags: ['toad', 'topic']
comments: true
aliases:
    - /oldsection/my-post/
---
```

Configuration wise:

```toml
baseurl = "/"
languageCode = "en-us"
title = "Website template"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    "A" = "/:section/:title/"
    "B" = "/:section/:title/"
    "C" = "/:section/:title/"
    "D" = "/:section/:title/"
    "E" = "/:section/:title/"
    "F" = "/:section/:title/"
```

### Version Information

Hugo Static Site Generator v0.33 darwin/amd64 BuildDate:
