### ISSUE TITLE
Start Resources :counter first time they're used

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/hugo#4335]
Hello,

This is a follow-up issue which proposes a fix for the issue in https://github.com/gohugoio/hugo/issues/4334.

Here's a copy of the proposal from the [discussion on discourse][1] for convenience:

---

In the [example I provided][2], there are 3 PDF files, and I wanted to first set the `title` of just one pdf file. 

So the alternative you provided:

> The counter is grouped by the matcher + first occurrence of either title or name.
> If you had said:
> 
>     [[resources]]
>     src = “documents/photo_specs.pdf”
>     [resources.params]
>     someParam = “foo”
>     
>     [[resources]]
>     src = "**.pdf"
>     name = "pdf-file-:counter"
>     title = “Photo Specifications #:counter”
> 
> They would be in the same group.

would not work, as that would auto-set the titles of all 3 PDF files.

I thought that my original example:

```toml
[[resources]]
  src = "documents/photo_specs.pdf"
  title = "Photo Specifications"
[[resources]]
  src = "**.pdf"
  name = "pdf-file-:counter"
```

was unambiguous.. *set `title` for just one file and counter-based `name` for all files*.

> If you have suggestions for improvement to the above, they are welcome, but those should come in form of a spec that takes any ambiguity into account.

How about: 

"**An individual counter should be grouped to matcher for each `title` and `name`, but only for the entities that use the `:counter` placeholder.**"

So in the example I posted, the counter will be grouped only with the second matcher, as only that uses `:counter`.

But if the example had been:

```toml
[[resources]]
  # using arbitrary glob
  src = "**s.pdf"  
  title = "PDF s #:counter"
[[resources]]
  src = "**.pdf"
  name = "pdf-file-:counter"
```

`"documents/photo_specs.pdf"` would get a `title` like `"PDF s #1"`, but `name` like `"pdf-file-3"`. This was quite an arbitrary example, and thus an arbitrary outcome. 

But this would then allow a normal example like in my original post to work exactly as expected.

[1]: https://discourse.gohugo.io/t/unexpected-replacement-of-counter-in-resources-title-name/10217/3?u=kaushalmodi
[2]: https://hugo-sandbox.netlify.com/posts/resources-counters-c/

**Comment by kaushalmodi** [comment]
Thank you for taking care of this quickly! I [confirm the fix][1]; the exact same test in https://github.com/gohugoio/hugo/issues/4334 now works!

[1]: https://hugo-sandbox.netlify.com/posts/resources-counters-c/#resource-debug

**Comment by kaushalmodi** [comment]
The older test in #4334 worked fine. But right now, I was trying to create a test case using the params used in https://github.com/gohugoio/hugo/commit/7b472e46084b603045b87cea870ffc73ac1cf7e7, but I am finding strange results.

Here is the [test case][1]:

```toml
[[resources]]
  src = "*specs.pdf"
  title = "Specifications #:counter"
[[resources]]
  src = "**.pdf"
  name = "pdf-file-:counter"
```

It looks like the name and title counters are not yet independent.. 

- Both `checklist.pdf` and `other_specs.pdf` are getting the `Name`: `pdf-file-1`, and
- Both `guide.pdf` and `photo_specs.pdf` are getting the `Name`: `pdf-file-2`, and

It's as if the matcher with `title` caused the `name`-counter to reset?

[1]: https://hugo-sandbox.netlify.com/posts/resources-counters-name-and-title/
