### ISSUE TITLE
Improve title logic for new post/my-post/index.md etc.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4348]
Page Resources may prompt user to systematically create Page Bundles for all of their pages, or not. 

For now, you have to hit
`$ new post/my-post/index.md` which will create a mardown with the following Front Matter
```yaml
title: "Index"
date: 2018-01-28T13:00:17-05:00
draft: true
```
Not only user has to include index.md himself in the path, but will have to rename the default `title`wrongly assumed as "Index"

A simple flag called `--bundle` or other could save many seconds to content creation and result in a simpler:
`$ new post/my-post --bundle`
