### ISSUE TITLE
theme param "theme" breaks build.

### ISSUE THREAD

**Issue by MoritzFago** [gohugoio/hugo#4352]
In the hyde-x theme (see my [fork](https://github.com/MoritzFago/hyde-x)), you have a parameter called "theme" to set the color scheme of the theme. This worked in hugo ~0.19, in hugo 0.34 it breaks the build process in a rather surprising way: no content gets generated, and there isn't any errors, there are a lot of warnings about files it can't find, despite them being there.
if i have 
```toml
[params]
    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"
```
in my config.toml, it breaks.

`hugo version`:
```
Hugo Static Site Generator v0.34 darwin/amd64 BuildDate:
```
