### ISSUE TITLE
Improve language params handling

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4356]
I scratched my head looking into #4352.

I will fix this properly and in a backwards compatible way. I guess we were a little tired and eager to wrap it up when we created the multilingual feature, which has config values and custom params in one map, which when merged with the global settings has potential naming conflicts.

So, we need to add a proper `params` map to each language, so people can do:

```toml
[languages]
[languages.en]
languageName = "English"
weight = 1
title = "My Cool Site"
[languages.en.params]
myParam = "Hi!"
```

The story is slightly longer than the above, but it should fix #4352 and other similar corner cases, and make language configuration more obvious.
