### ISSUE TITLE
Multihost fails with ERROR when no baseURL on top level

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4397]
This should not be needed.

But the current workaround is to replicate one of the `baseURL` values from the `languages` section up to the top level.

```toml
uglyurls = true
baseURL = "https://www.example.com"


[languages]
[languages.en]
baseURL = "https://www.example.com"
languageName = "en"
title = "In English"
weight = 1

[languages.pl]
baseURL = "https://www.example.org"
languageName = "pl"
title = "Po Polsku"
weight = 2
```
