### ISSUE TITLE
YAML code blocks are not supported in posts

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#4410]
I brought this up in https://discourse.gohugo.io/t/triple-backtick-syntax-not-working-for-yaml-hljs/10460. 

If you write a post (ending with .md) in Hugo, and use triple-backtick code block syntax and annotate it with languages "yaml" or "yml", you don't get a code block. This is because highlight.js does not recognize it. Example:

    ```yaml
    apiVersion: apps/v1beta1
    kind: Deployment
    metadata:
      name: helloweb
    ```

This will render like this:

`apiVersion: apps/v1beta1`
`kind: Deployment`
`metadata`
&nbsp;&nbsp;`  name: helloweb`

And not like this:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
```

It's not directly a Hugo problem (the thread has indicated it's a Highlight.js issue).

This currently vastly impedes my usage of Hugo. I am writing technical blog posts and I often have YAML code snippets in my articles. (And I can't use `{{<highlight>}}` shortcode as I want my content to render fine on GitHub markdown, as well as I want it to be portable in case I move to another blogging platform someday.)
