### ISSUE TITLE
Header id with non-english characters doesn't work

### ISSUE THREAD

**Issue by lichtner** [gohugoio/hugo#4452]
Hi guys,
thanks for awesome Hugo. I am the non-English speaker and in my language, we use some diacritic characters like `ščťžýáíôúä`. Problem is when I use this character in `header id` these chars are not converted. E.g.:

```html
## čaj 

<h2 id="čaj">čaj</h2>
```
but this is a problem, because it is impossible to make anchor to this header because browser always converts non-English chars in `href` attribute like this:

```html
<a href="#%c4%8daj">čaj</a>
```
I am not go lang developer but I think a solution to this problem could be easy. Just apply function `urlize` for id attribute of all header elements something like this:
```html
<h2 id="urlize(id)">....</h2>
````
This doesn't effect English anchors but fixes all non-English ids. Thanks. Is it possible to do this?

**Comment by mikhail73** [comment]
I tested it and it works right for me.
Hugo generate:
`<h2 id="čaj">čaj</h2>`
And TOC:
`<li><a href="#čaj">čaj</a></li>`
All works right.

**Comment by mikhail73** [comment]
My config of BlackFriday
```
blackfriday:
  HeaderIDSuffix: false
  plainIdAnchors: true
  FootnoteAnchorPrefix: false
  angledQuotes: true
  smartDashes: true
```
