### ISSUE TITLE
is there a better way to get permalink of a taxnonmy

### ISSUE THREAD

**Issue by iEverX** [gohugoio/hugo#4482]
Hi guys, 
I'm finding a way to not hard code permlinks to template. as below.

with a config,
```toml
[permalinks]
  tags = "/path/to/tags/:title"
```
do i have to use `/path/to/tags/{{ $tag | urlize }}` to generate a path ?
I found nothing about this from the doc and google. thanks
