### ISSUE TITLE
Remove Pygments

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4491]
We now have Chroma as the default. I dont't see a reason to keep the old Python Pygments.

So, here is the plan:

1) Deprecate `pygmentsuseclassic: true`
2) Create aliases for the setting below below the map `highlighter` (or `highlight`?)

```yaml
pygmentscodefences: true
pygmentscodefencesguesssyntax: false
pygmentsoptions: ""
pygmentsstyle: "friendly"
pygmentsuseclasses: true
```

We should maybe hold off with the docs update to the new values.

/cc @kaushalmodi
