### ISSUE TITLE
Archetype fields are parsed/sorted upon instantiations

### ISSUE THREAD

**Issue by yacoob** [gohugoio/hugo#452]
I've created `archetypes/post.md` containing some fields. Most of them are just there to remind me that I should fill them in:

``` yaml

---
zyzio: url
hg:
  - foo
aliases:
  - bar
cover_img: url
social_img: url

---
```

After `hugo new post/foo.md`, it turned out that hugo unhelpfully sorted all of the fields:

``` yaml

---
aliases:
- bar
cover_img: url
date: 2014-08-29T23:18:10+01:00
hg:
- foo
social_img: url
title: foo
zyzio: url

---
```

Not really helpful :(

**Comment by anthonyfok** [comment]
I noticed this discrepancy while going through the documentation, and did some testing.  With the example archetypes/default.md of:

```
+++
tags = ["x", "y"]
categories = ["x", "y"]
+++
```

Hugo v0.11 (`hugo_0.11_amd64_linux new post/test.md`) gives:

```
+++
categories = ["x", "y"]
tags = ["x", "y"]
title = "test"
date = 2015-01-14T02:26:19Z
+++
```

whereas Hugo v0.12 and above (up to HEAD of v0.13-DEV) gives:

```
+++
categories = ["x", "y"]
date = "2015-01-13T19:20:04-07:00"
tags = ["x", "y"]
title = "test"

+++
```

I couldn't get `-f yaml` to work with Hugo v0.11, but oh well...  :-)

So, regardless of the root cause, to the end users, it is a regression: At least for TOML, It used to keep the proper order in v0.11, but now it sorts all the variables alphabetically and messes things up.  I haven't looked into it any deeper, though I wonder if a commit in Hugo causes this, or whether an external library changed.

Just my 2 cents.  :-)

**Comment by halostatue** [comment]
That doesn’t look right, @anthonyfok. As you indicated, if you have this archetype:

```toml
+++
tags = ["x", "y"]
categories = ["x", "y"]
+++
```

If Hugo v0.11 (hugo_0.11_amd64_linux new post/test.md) gives,

```toml
+++
categories = ["x", "y"]
tags = ["x", "y"]
title = "test"
date = 2015-01-14T02:26:19Z
+++
```

Notice that `categories` and `tags` are now sorted and not the same order as the archetype. The later versions also sort, but insert a few other fields.

As I indicated, this is something that the Go team has gone out of its way to ensure `map` structures do not iterate the same way every time (without providing an `omap` implementation that would make this work for us).

That said, I did a *little* more digging, and the folks behind YAML have possibly [done us a favour](http://blog.labix.org/2014/09/22/announcing-yaml-v2-for-go#mapslice) if we use `yaml.MapSlice` instead of `map[string]interface{}`. It’s not perfect (you lose fast lookup…), but I don’t know of another way to have an ordered map in Go at this point.
