### ISSUE TITLE
Preserve comments in YAML/TOML in the Remarshal func

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4520]
Do some string replacement

"# My comment" => "hugocomment = "My comment" => and back.

Ignore the last step for JSON (which does not support it).

**Comment by kaushalmodi** [comment]
For JSON, may be use a hack like shown here: https://stackoverflow.com/a/244858/1219634

```
..
"_hugo_comment": "My comment",
..
```

**Comment by razonyang** [comment]
I'm interested in this, it would helpful for readers to view important annotation. I have a question is that is it possible preseve the comments and display it in-place?

```yaml
foo:
  bar:
    fizz: buzz # annotation for fizz.
```

Remarshal to TOML.

```toml
[foo.bar]
fizz = "buzz" # annotation for fizz.
```
