### ISSUE TITLE
Add a Markdown URL rewriter

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4574]
So, we have the `relref` and `ref` shortcodes to help with linking in content files, and we have page
 bundles which enables page-relative linking of image resources etc.

But, given this example:

```markdown
[I'm an inline-style link](/posts/my-post)
![alt text](/images/logo.png
```

All of the above are relative to the host (server) root. Which works fine ... most of the time.

But it gets challenging for sites with many languages ... 

```markdown
[I'm an inline-style link](/jp/posts/my-post)
```

Esp. if the translation method is to just copy the English content tree and start translating.

1. It is easy to do transformations of the links above.
2. It is, however, hard to find a "good rule that fits all".

So, I suggest that we add a `UrlRewriter` (for content only for starters), configurable either globally or per language:

```toml
[languages.en]
languageName = "English"
weight = 1

[languages.nn]
languageName = "Nynorsk"
weight = 2
contentDir = "content_nn"
[[contentURLWriter.nn]]
type = "link" # or image (or all)
pattern = ".*"
rewrite = `{{ .URL | relLangURL }}`
[[contentURLWriter.nn]]
type = "image" # or images (or all)
pattern = ".png"
rewrite = `{{ .URL | upper }}`
```

The above example is quickly typed and the API can be improved, but my thoughts are:

* We pick the first matching regexp for a given link
* We treat the `rewrite` rules as Go templates with both a `.Site` `.URL` and all of Hugo's template funcs.
