### ISSUE TITLE
server command panic when live add multihost

### ISSUE THREAD

**Issue by moorereason** [gohugoio/hugo#4603]
Stumbled into this while [troubleshooting a user's config](https://discourse.gohugo.io/t/11403).

In HEAD, given the following config.toml:

```toml
baseurl = "/"

[Languages]
[Languages.en]
baseURL = "https://example.en"
languageName = "English"
weight = 1
title = "In English"
contentDir = "content"

# [Languages.de]
# baseURL = "https://example.de"
# languageName = "German"
# weight = 2
# title = "In German"
# contentDir = "content_de"
```
Run `hugo server` and then uncomment the `de` section.

```none
panic: runtime error: index out of range

goroutine 107 [running]:
github.com/gohugoio/hugo/commands.server.func1(0xc4201340c0, 0xe63d86, 0xf)
        /home/X/src/github.com/gohugoio/hugo/commands/server.go:195 +0x712
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc4201340c0, 0x14e5901, 0xc4201c1c78, 0x5a8d0a)
        /home/X/src/github.com/gohugoio/hugo/commands/commandeer.go:213 +0xc28
github.com/gohugoio/hugo/commands.(*commandeer).fullRebuild(0xc4201340c0)
        /home/X/src/github.com/gohugoio/hugo/commands/hugo.go:855 +0x34
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc42073e7a0, 0xc4201340c0, 0xc4207527b0, 0xc4207573d0)
        /home/X/src/github.com/gohugoio/hugo/commands/hugo.go:920 +0x48d
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /home/X/src/github.com/gohugoio/hugo/commands/hugo.go:896 +0x291
```
Offending line:  https://github.com/gohugoio/hugo/blob/e614d8a57c2ff5eef9270d51fcc6518398d7ff88/commands/server.go#L195
