### ISSUE TITLE
Problem listing languages in a correct order and switching to a language-specific page URL

### ISSUE THREAD

**Issue by Andrew-Schetinin** [gohugoio/hugo#4778]
I'm using Hugo 0.40.1 on Ubuntu, and trying to create a language switch control using the following code:
```
{{ range $.Site.Languages }}
	<span href="#"> {{ .Lang }} - {{ .LanguageName }} </span>
{{ end }}
```
Where the **config.yaml** file contains the following:
```
languages:
  en:
    weight: 1
    LanguageName: english
  es:
    weight: 2
    LanguageName: español
  fr:
    weight: 3
    LanguageName: français
```
There are the following problems with this:
1.  no matter what I'm trying, I cannot display the **.LanguageName** - either an empty string is displayed, or the current page language name is repeated all over; note that **.Lang** works correctly - but this is the only success
2. according to the documentation, **$.Site.Languages** is supposed to work in the order specified by **weight**, but does not work like that and languages are not ordered in any predictable way
3. it is unclear (from the documentation) how to construct URLs pointing to different languages of the current page
