### ISSUE TITLE
Broken markdown conversion around code blocks

### ISSUE THREAD

**Issue by geeknoid** [gohugoio/hugo#4785]
I'm having formatting problems with an indented fenced code block. To repro:

- Create a new site 
- Add the ananke theme to the site
- Add the attached file as content/troubleshooting.md
- Build the site using Hugo 0.40.2

You'll see that the YAML code block from the markdown file didn't get rendered correctly in the HTML. It simply didn't get interpreted as a code block. You can see the previous code block was converted properly. If you remove the leading dashes (-) on both the first and last line of the code block, then it formats properly. If you outdent the whole code block so that it starts on column 0, then it formats properly. So there's something about being indented and having those dashes present. The resulting HTML has a list in it instead of a code block, so something is getting confused and treating this sequence as a list.

I scoured our site and found many instances of indented code blocks that contain lines which start with - and this is the only block where the bug happens. So something about the specific structure of the code block is getting the parser confused.

[troubleshooting.zip](https://github.com/gohugoio/hugo/files/2042690/troubleshooting.zip)

**Comment by nonumeros** [comment]
mainly because of the dash that follows, you'd probably have to space it out some more

     ```yaml
        - job_name: 'istio-mesh'
        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        static_configs:
        - targets: 'istio-mixer.istio-system:42422'
     ```
![screenshot_2018-05-27_11-06-03](https://user-images.githubusercontent.com/11535575/40587570-eda9d54e-619e-11e8-80d6-048754b359ba.png)
