### ISSUE TITLE
i18n: plural tags (other than one) are not working

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#4889]
Consider the following exemple:
```
# i18n/en.yaml
time:
  one: "Once"
  two: "Twice"
  zero: "Never"
  other: "{{ .Count }} Times"
```
`{{ i18n "time" 1 }}` > Once
`{{ i18n "time" 2 }}` > 2 Times
`{{ i18n "time" 0 }}` > 0 Times

According to the go-i18n package, it is supposed to support this (http://cldr.unicode.org/index/cldr-spec/plural-rules), meaning the following tags:

* zero
* one
* two
* few
* many
* other

But when, any other number than __1__ is passed as an argument to the `i18n` function, it always returns the value of the `other` key.

Am I missing something?
