### ISSUE TITLE
.IsTranslated is set to `true` although there is no translated content

### ISSUE THREAD

**Issue by nop33** [gohugoio/hugo#5195]
Here's a minimal example to reproduce the issue: https://github.com/nop33/hugo-minimal-setup

This is the project structure
```
project/
└── content/
    ├── subpage/
    │   ├── _index.fr.md
    │   └── _index.md
    └── _index.md
```

And these are my language settings in the `.config.yml`:
``` yaml
languageCode: "en-us"
defaultContentLanguage: "en"
languages:
  en:
    languageName: "English"
    weight: 1
  fr:
    languageName: "French"
    weight: 2
```

Now, when I check for `{{ .IsTranslated }}` in the template where the home page is rendered, it is set to `true`, even though a `content/_index.fr.md` file doesn't exist.

Since a translation of the `content/_index.md` has not been defined, why is Hugo creating an empty page for the French translation, in the particular case, the French home page?

```
Hugo Static Site Generator v0.48 darwin/amd64 BuildDate: 2018-08-29T06:33:08Z
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.11"
```

I asked for help from the community, but haven't received any replies yet: https://discourse.gohugo.io/t/how-to-translate-only-a-subset-of-the-pages/14083

I also found these 2 issues, but they didn't help:
* https://github.com/gohugoio/hugo/issues/3470
* https://github.com/gohugoio/hugo/issues/2699
