### ISSUE TITLE
safeURL function doesn't escape `+` character in a template

### ISSUE THREAD

**Issue by akshaybabloo** [gohugoio/hugo#5253]
In template `safeURL` function doesn't escape `+` character. Example:

Consider the following settings under `config.toml`:

```toml
# config.toml
[params]
  fontFamilyURL = "https://fonts.googleapis.com/css?family=Space+Mono:400,700"
```

I am then trying to use this in an HTML template as:

```html
<!-- baseOf.html -->
{{ .Site.Params.fontFamilyURL | safeURL }}
```

The above code generates -> `https://fonts.googleapis.com/css?family=Space&#43;Mono:400,700` instead of `https://fonts.googleapis.com/css?family=Space+Mono:400,700`. You can see that `+` is replaced by `&#43;`, but when I use `safeHTML`, I have no such problem.

The issue is something similar to #5236.

I am using `Hugo Static Site Generator v0.49/extended windows/amd64 BuildDate: unknown`
