### ISSUE TITLE
 [params] in multilingual site do not always behave as expected (in the documentation)

### ISSUE THREAD

**Issue by divinerites** [gohugoio/hugo#5357]
## Issue

`[params.foo]` do not behave correctly when you have **partiallly** some of the parameters in the language section.

Works fine when you have **all** or **none** of the parameters

You can see it in action here, I created a dedicated hugo site who expose this behaviour: [https://github.com/divinerites/mytest](https://github.com/divinerites/mytest)

![capture d ecran 2018-10-26 a 10 08 35](https://user-images.githubusercontent.com/32342823/47553373-4034ca00-d907-11e8-9a8f-f21f8517ff56.png)

```toml
[params]
    [params.case_1_lang]
        id      = "params.case_1_lang.id ROOT"
        title   = "params.case_1_lang.title ROOT"

    [params.case_problem]
        id      = "params.case_problem.id ROOT"
        title   = "params.case_problem.title ROOT"

    [params.case_3_nolang]
        id      = "params.case_3_nolang.id ROOT"
        title   = "params.case_3_nolang.title ROOT"

    [[params.listeLangues]]
        code = "fr"
    [[params.listeLangues]]
        code = "en"

[languages]
    [languages.fr]
        languageCode = "fr-fr"
        title = "languages.fr.title"

        [languages.fr.params.case_1_lang]
            id      = "languages.fr.params.case_1_lang.id FRANCAIS"
            title   = "languages.fr.params.case_1_lang.title FRANCAIS"
        [languages.fr.params.case_problem]
            # id      = "languages.fr.params.case_problem.id FRANCAIS"
            title   = "languages.fr.params.case_problem.title FRANCAIS"

    [languages.en]
        languageCode = "en"
        title = "languages.en.title"

        [languages.en.params.case_1_lang]
            id      = "languages.en.params.case_1_lang.id ANGLAIS"
            title   = "languages.en.params.case_1_lang.title ANGLAIS"
        [languages.en.params.case_problem]
            # id      = "languages.en.params.case_problem.id ANGLAIS"
            title   = "languages.en.params.case_problem.title ANGLAIS"
```

## Disclaimer 

I opened a [thread](https://discourse.gohugo.io/t/is-it-possible-to-have-global-params-in-a-multilingual-site/14773/4) on discourse, and Bep's response pointed to the documentation he improved to be more clear.

This was comforting me in the fact that  [params] in multilingual site do not always behave as expected. I tested it in all ways, and created a minimal site for exposing this "wrong" behaviour.

I was really reluctant to fill a bug because such a feature is largely used in the wild and should have been reported before. But I do not fear to look like a (french) fool, so I fill a bug ...
