### ISSUE TITLE
Hugo strips emoji in taxonomy keys

### ISSUE THREAD

**Issue by slurps-mad-rips** [gohugoio/hugo#5367]
Hello,

I've been porting my blog recently from Nikola to Hugo and one thing I've run into an issue with is that I can't have emoji as tags. For instance, when the frontmatter looks like

```yaml
layout: post
tags: ["c++", "optional", "⛔"]
markup: md
```

It will render `$key` of `.Site.Taxonomies.tags` as an empty string.

When trying to use the `emojify` pipe, as in

```yaml
tags: ["c++", "optional", ":heart:"]
```

Hugo will strip away the `:` before it reaches the pipe, and simply render the text `heart`.
