### ISSUE TITLE
Add a better (and consolidated) cache design

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5404]
Several of the things I want to do in Hugo (pages from data sources etc.) needs a cache to ... survive.

We do caching on several levels in Hugo, but the file cache(s) are spread around and you cannot configure much more than the directory they live in.

I suggest we add a concept of named caches with sensible default configuration. Configuration options:

* Path
* TTL (time to live), value in seconds >= 0. 0 Effectively means "no cache", -1 means forever.

The default value will, in most cases, be assigned a directory below `cacheDir`, so we need to do some work in that area, too, if there is no value set for that option and you're running on a CI server (Netlify etc.).

Some defaults could look like this:

```toml
[caches]
[caches.image]
path = ":resourceDir/_gen/images"
ttl=-1
[caches]
[caches.getJSON]
path = ":cacheDir/getjson"
ttl=600
```

/cc @kaushalmodi @regisphilibert
