### ISSUE TITLE
Use time.Duration (10m) for maxAge in file cache

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5438]
The current:

```toml
[caches]
[caches.getjson]
dir = ":cacheDir"
maxAge = -1
[caches.getcsv]
dir = ":cacheDir"
maxAge = -1
[caches.images]
dir = ":resourceDir/_gen"
maxAge = -1
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = -1
```

-1 means forever. I guess we should establish a good baseline for this before it's too late ...

Note that the motivation for cache expire in the above is different:

* getJSON / getCSV, handle potential changes in the source (and potentially also clean up unused)
* images/assets: Clean up unused files

The current value is noted in seconds, but I would be happy to change that to something bigger if that makes sense. 

Suggest value(s) for the above?

@moorereason @regisphilibert @onedrawingperday and gang
