### ISSUE TITLE
Work in progress: Externalized page metadata

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#5455]
> Also see #5510 -- a concurrent batch variant (whatever that would look like) could also be considered.

This issue describes a way to add or modify `Page` metadata in batches from external file(s). This is the information you currently only set in `Page` front matter.

Some use cases:

* The default page sort is `ByWeight` (with fall back to date and then title). Setting weight in front matter to get a particular order can be cumbersome if you have thousands of articles. With this implemented, you can re-arrange the pages by assigning `weight` in batches by Glob pattern matching.
* Tag all pages with both `funny` and `cat` in the path with the tag `Funny Cats` 
* Add category `Other` to pages with no category set.

Some examples in `TOML`:

```toml
# Re-arrange the blog posts so dog articles come first.
# Note that the `:counter` will restart at each `meta` element.
[[meta]]
match = "/*/blog/**"
matchFirst = """
**dog*
**cat*
**
"""
counterStart = 10 # default is 1
counterIncrement =  10 # default is 1
replace = true # default is false
[[meta.data]]
weight = ":counter"

# Add a category and a title to blog posts with none set.
[[meta]]
match = "/*/blog/**"
[[meta.data]]
title = "Blog article #:counter"
categories = ["Other"]
```

* There can be many `meta` definitions, and all pages will be tested against all of them.
* A page that matches both the Glob pattern in `match` and `matchFirst` will be assigned the given metadata. if `replace = true` any existing value will be replaced.
* The `match` pattern is primarily "motivated by speed", but it also allows for simple and coarse-grained patterns in `matchFirst`.
* The values in `meta.data` map directly to what you would normally set in page front matter.
* The patterns in `matchFirst` sets the order of the 1-based `:counter` placeholder. In the example above, the articles about `dog` will get `weight` 10, 20, 30, and then come the cats and finally all the other.
* In the example, `matchFirst` is a multiline string, but we will accept string arrays, too.
We will match against the `canonical path`* (always prefixed by the current language, so one can do `/{en,jp}/blog/**` etc).

`*`: It would be tempting to match against `.RelPermalink`, but that will typically change across languages. We need to define the term `canonical path` as part of this issue.
  

Some references:

* This proposal is inspired by how we do "page resources" metadata, see https://gohugo.io/content-management/page-resources/#the-counter-placeholder-in-name-and-title
* Having this configuration in the site configuration will make more sense once #5422 is ready (should be next very soon)
* This proposal will also make more sense/add more value if you also consider #5255 and #5074
