### ISSUE TITLE
.Lastmod does not honor front matter override

### ISSUE THREAD

**Issue by paulprogrammer** [gohugoio/hugo#5523]
Using `.Lastmod` in template, and getting only the git lastmod.  `lastmod` property in front matter is ignored.

post front matter:
```
---
title: Range Damage
author: Stets Newcomb
lastmod: "2017-03-03T14:15:59-06:00"
---
```

template:
```
{{ define "main" }}
	<div id="page-wrapper" class="smaller-viewport">
		<section class="news">
			{{ range .Pages }}
			<article>
				<div class="date">
					<span class="month">{{ .Lastmod.Format "Jan" }}</span>
					<span class="day">{{ .Lastmod.Format "02" }}</span>
				</div>
				<div class="excerpt">
					<h2>{{ .Title }}</h2>
					<address>{{ .Params.author }}</address>
					{{ .Content | truncate 90 }}
				</div>
			</article>
			{{ end }}
		</section>
	</div>
{{ end }}
```

Month and day are "DEC" and "13" -- the day I did git checkin.  If I haven't checked it in yet, its 01-01-0001T00:00:00-00:00

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).

**Comment by dadoonet** [comment]
I came today to that issue. This has been indeed discussed on discourse but the conclusion is that the documentation and the behavior are not consistent.

To have a proper behavior which matches the documentation, there is indeed a workaround, which consists of changing the config by:

```yml
frontmatter:
  date:
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - lastmod
  - :git
  - date
  - publishDate
  publishDate:
  - publishDate
  - date
```

Would it be possible to reopen this issue and either fix the documentation or change the default order?
