### ISSUE TITLE
Number types don't work properly in JSON data files

### ISSUE THREAD

**Issue by nathnolt** [gohugoio/hugo#5685]
I have a simple data file like this:

userdata.json
```json
[
	{
		"name": "John doe",
		"salary": 300
	},
	{
		"name": "Frank foobar",
		"salary": 500
	},
	{
		"name": "Rick foobar",
		"salary": 400
	}
]
```
and in my layout I'm doing

```go
{{where .Site.Data.userdata "salary" "<" 500 }}
```
The output is `[]` but the expected output is `[map[salary:300 name:John doe] map[name:Rick foobar salary:400]]`

If I have the same thing as a `yaml` file

```yaml
---
- name: John doe
  salary: 300
- name: Frank foobar
  salary: 500
- name: Rick foobar
  salary: 400
```

It does give me the expected output of `[map[salary:300 name:John doe] map[name:Rick foobar salary:400]]`

I'm not quite proficient in Hugo or go html/templates, so excuse me if this issue has been posted already, but I couldn't find it with my current knowledge.

`>hugo version` output

Hugo Static Site Generator v0.54.0-B1A82C61 windows/amd64 BuildDate: 2019-02-01T09:42:02Z
