### ISSUE TITLE
Assign internal page to a menu item from the configuration file

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#5711]
Currently while managing menus, user can choose from the following options:

1. Use `menus.yaml`/`config.yaml`
This was intentionally designed to add external menu items on top of internal page items. But many use it for every menu items (internal or external) as it allow to group all your menu logic in the same file. Drawback is, URL to internal pages have to be hardcoded, making it a pain to efficiently maintain when permalinks evolve.

2. Use Front Matter
This allow to link a page directly to a menu item making it available as a menu item variable (`.Page`) while in the template. Also, permalinks are constantly mapped, regardless of config/permalink change.
But this is hard to handle, as every menu item must reside in the page's file. In big scale projects, with many menus and even more menu items, managing those can be 🤕.

Personally I would love to use `menus.yaml` to manage any kind of menu items but most of the time I have to rely on Front Matter, because I need to access the page from the template, or let Hugo handles permalink mapping (editor using slug etc...)

## Proposal

Allow to assign a page to a menu item from the configuration files by using the same syntax as `.Site.GetPage` (relative to site's). 
In place of using `url`, user would use `page`

```
main:
  - name: About
    page: about
    weight: 1
  - name: Contact
    page: about/contact
    weight: 2
  - name: FAQ
    page: faq
    weight: 3
  - name: External Blog
    url: https://bloggy.tumblr.com
    weight: 4
```

cc/ @budparr
