### ISSUE TITLE
Is it author or AuthorName?

### ISSUE THREAD

**Issue by afranke** [gohugoio/hugo#5921]
https://gohugo.io/getting-started/configuration/ claims I should add
```toml
[params]
  AuthorName = "Jon Doe"
```
while https://gohugo.io/variables/site/ suggests
```toml
[params]
  author = "Nikola Tesla"
```

Are they both correct or is one of them wrong? In any case, the docs should be fixed.
