### ISSUE TITLE
Custom menu entry variables

### ISSUE THREAD

**Issue by inwardmovement** [gohugoio/hugo#5953]
It would be great to allow using custom menu entry variables.
(Usecase example: detect external links to automatically add `target=_"blank"`)

config.yml:
```
menu:
  footer:
    - Name: "GitHub"
      URL: "#"
      Identifier: "github"
      External: true
      weight: 1
```

nav.html:
`<a ... {{ with .External }}target="_blank"{{ end }}>`
