### ISSUE TITLE
Global params not merged with multilang params

### ISSUE THREAD

**Issue by toby3d** [gohugoio/hugo#6033]
# hugo
```bash
) hugo env                                                                                                                                                                                      12:30:57
Hugo Static Site Generator v0.62.2/extended linux/amd64 BuildDate: unknown
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13.5"
```

# Configs
## config/_default/params.yaml
```yaml
metas:
- property: "article:author:username"
  content: "toby3d"
- property: "article:author:gender"
  content: "male"
```

## config/_default/params.ru.yaml
```yaml
metas:
- property: "article:author:first_name"
  content: "Максим"
- property: "article:author:last_name"
  content: "Лебедев"
```

## config/_default/params.en.yaml
```yaml
metas:
- property: "article:author:first_name"
  content: "Maxim"
- property: "article:author:last_name"
  content: "Lebedev"
```

# Templates
## layouts/_default/baseof.html
```html
{{- range .Site.Params.metas }}
  <meta {{ if .property }}property="{{ .property }}"{{ else }}name="{{ .name }}"{{ end }} content="{{ .content }}" />
{{- end }}
```

# What I expect
* If the key is available only in the root, then its value will be used;
* If the key is only in the localized version, then its value will be used;
* If the key is in the root and in the localized version, then the value from the localized version will be used:
  * Neighboring keys in the section merge with the parameters in the localized version according to the same rules;

## English
```html
<meta property="article:author:first_name" content="Maxim">
<meta property="article:author:last_name" content="Lebedev">
<meta property="article:author:username" content="toby3d">
<meta property="article:author:gender" content="male">
```

## Russian
```html
<meta property="article:author:first_name" content="Максим">
<meta property="article:author:last_name" content="Лебедев">
<meta property="article:author:username" content="toby3d">
<meta property="article:author:gender" content="male">
```

## Any/other/unsupported lang
```html
<meta property="article:author:username" content="toby3d">
<meta property="article:author:gender" content="male">
```

# What I get
Only keys from the localized version are used. Similar or neighboring keys in the root (or even entire sections of the configuration) are completely ignored.

## English
```html
<meta property="article:author:first_name" content="Maxim">
<meta property="article:author:last_name" content="Lebedev">
```

## Russian
```html
<meta property="article:author:first_name" content="Максим">
<meta property="article:author:last_name" content="Лебедев">
```

**Comment by toby3d** [comment]
```bash
> hugo env
Hugo Static Site Generator v0.58.3/extended linux/amd64 BuildDate: unknown
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13.1"
```

Still reprodused as described above.

**Comment by johnelliott** [comment]
I also noticed the disableKinds stuff not merging when using TOML and YAML, so it seems to me like the tool does not merge at all, it simply chooses a file to use. I don't know why the documentation says merge. I suppose should read the source code and see...

**Comment by toby3d** [comment]
# hugo
```bash
) hugo env                                                                                                                                                                                      12:30:57
Hugo Static Site Generator v0.62.2/extended linux/amd64 BuildDate: unknown
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13.5"
```

# Configs
## config/_default/params.yaml
```yaml
- property: "article:author:username"
  content: "toby3d"
- property: "article:author:gender"
  content: "male"
```

## config/_default/params.ru.yaml
```yaml
metas:
- property: "article:author:first_name"
  content: "Максим"
- property: "article:author:last_name"
  content: "Лебедев"
```

## config/_default/params.en.yaml
```yaml
metas:
- property: "article:author:first_name"
  content: "Maxim"
- property: "article:author:last_name"
  content: "Lebedev"
```

# Templates
## layouts/_default/baseof.html
```html
<!DOCTYPE html>
<html>
  <head>
    ...
    {{- range .Site.Params.metas }}
      <meta {{ if .property }}property="{{ .property }}"{{ else }}name="{{ .name }}"{{ end }} content="{{ .content }}" />
    {{- end }}
    ...
  </head>
  <body>
    ...
  </body>
<html>
```

# Output
## English
```html
<!DOCTYPE html>
<html>
  <head>
    ...
    <meta property="article:author:first_name" content="Maxim">
    <meta property="article:author:last_name" content="Lebedev">
    <!-- no article:author:username from config/_default/config.yaml -->
    <!-- no article:author:gender from config/_default/config.yaml -->
    ...
  </head>
  <body>
    ...
  </body>
<html>
```

## Russian
```html
<!DOCTYPE html>
<html>
  <head>
    ...
    <meta property="article:author:first_name" content="Максим">
    <meta property="article:author:last_name" content="Лебедев">
    <!-- no article:author:username from config/_default/config.yaml -->
    <!-- no article:author:gender from config/_default/config.yaml -->
    ...
  </head>
  <body>
    ...
  </body>
<html>
```
