### ISSUE TITLE
Check hugo new vs language content directories

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6062]
There seems to be some confusion there.

**Comment by yutotakano** [comment]
I'm not sure if this is the relevant issue, but `hugo new` always creates new posts in the defaultContentLanguage directory. For info, I adopt the Language Content Directories structure instead of suffixing individual markdown files.

When the configuration file is as follows (or similar):
```toml
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"

  [languages.ja]
    languageName = "Japanese"
    weight = 2
    contentDir = "content/ja"
```

all but the first command below fail to do what I want them to do:

| Command | Expected File Creation | Actual File Creation |
| ------------- | ------------- | ------------- |
|  `hugo new post/blah.md`  | `content/en/post/blah.md` | `content/en/post/blah.md` |
| `hugo new ja/blah.md`  | `content/ja/blah.md` | `content/en/ja/blah.md` |
| `hugo new content/ja/blah.md`  | `content/ja/blah.md` | `content/en/content/ja/blah.md` |

There is effectively no method of creating new posts in a different language other than to change `defaultContentLanguage` and running `hugo` once to apply it. This surely needs to be fixed.
