### ISSUE TITLE
Configure external helpers via output formats

### ISSUE THREAD

**Issue by florisdf** [gohugoio/hugo#6089]
Hi,

The support of pandoc adds many options to possible output formats for Hugo. However, it is now limited to html output. I guess an incredible amount of flexibility would be added when external helpers, like pandoc, can be configured via the output formats configuration, e.g.

```toml
[mediaTypes]
  [mediaTypes."text/tex"]
    suffixes = ["tex"]
    
[outputFormats]
  [outputFormats.TeX]
    mediaType = "text/tex"
    helper = "pandoc"
    helperArgs = ["-t latex"]
```

This would make for a hassle-free way to generate PDF versions of web pages.

Or is this beyond the scope of Hugo?
