### ISSUE TITLE
scss content wrongly compile to base64

### ISSUE THREAD

**Issue by AoiYamada** [gohugoio/hugo#6104]
before compile
```scss
.some-class:: before {
      content: url("data: image/svg+xml; utf8, <svg xmlns=\"http://www.w3.org/2000/svg\" width=…2= '14' ></line><line x1= '21' y1= '18' x2= '3' y2= '18' ></line></svg>");
}
```

after compile
```css
.some-class:: before {
      content: url(data:image/svg+xml;utf8;base64,PHN2ZyB4bWxucz0nXCJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Z1wiJyB3aWR0aD0i4oCmMj0iLz48cGF0aCBkPSJNMjEgMThIM3oiLz48L3N2Zz4=);
}
```

then the svg is disappeared
