### ISSUE TITLE
Uniq not working on a slice of maps

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6105]
Apology the vocabulary used here for Golang's types is inaccurate. I will use `slice` to define what is commonly known as non-associative arrays and `map` for associative arrays.

Consider the following Front Matter field:

```
slice_of_maps:
  - firstname: Victor
    lastname: Hugo
  - firstname: Émile
    lastname: Zola
  - firstname: Victor
    lastname: Hugo
```

Using uniq on it:
```
{{ .Params.slice_of_maps | uniq }}
```
Will return the following error: `error calling uniq: elements must be comparable`.

Following the motivation behind #5852 I suspect we would want any kind of "collection" to be processed by `uniq`.

[Repo here](https://github.com/regisphilibert/hugo-slice-methods-maps)

Note that `intersect`, though not producing an error would simply return an empty strings when asked to process two "slices of maps" sharing common entries. If `intersect` is not impacted by the resolution of this issue, I'll create a seperate one.
