### ISSUE TITLE
Add a general "resources/pages matcher" for configuration

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6141]
We have several issues in the backlog that wants to _apply some configuration to a sub-set of pages/resources_.

One example would be the _output formats per kind_, which screams for a more fine-grained selection.

I suggest that we specify a new `resourcesFilter` configuration element that we can create a really fast implementation of that we can plugin in the relevant situations.

For `Pages` it could maybe look like:

```
resourcesFilter:
   exclude:
      kind: ["home", "taxonomyTerm"]
   include:
      path: ["blog/***", "docs/***"]

```

In the above:

* `kind` is something `Page` specific (for now).
* `Path` works across all resources (pages, images etc.) and would be a Unix slashed path relative to the content root. If would include the filename and extension for resources backed by a file, e.g. `blog/myblogpost.md`.
* Both `path` and `kind` are slices that get OR filtered.

/cc @regisphilibert @budparr and gang.

**Comment by regisphilibert** [comment]
That is needed indeed. Where would the settings go in this configuration example? Below the `resourceFilter` declaration? Like so:

```
resourcesFilter:
      path: ["blog/***", "docs/***"]
      params:
        output:
          - HTML
          - JSON
```
