### ISSUE TITLE
Allow to set the priority for theme param vs. module param

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#6172]
When using multiple themes/theme components, themes are prioritised— with the latter having a lower priority.

```
theme:
  - custom-hugo-theme
  - default-hugo-theme
```

Now, I’m using the very cool Hugo components like this:

```
theme:
  - custom-hugo-theme
module:
  imports:
    - path: github.com/…/default-hugo-theme
```

Modules seem to always have a higher priority than local themes. The order in the config file does not matter. Is there a way to change this?

Or is this the suggested way: Eliminate the theme param (if at least one module is used) and use the module param exclusively?

**Comment by bep** [comment]
My brain was a little drained once I finished this feature, but my main thoughts were, I think:

* We need to keep the existing config working.
* Eventually we will update the docs so that there is one and only one way to import other modules.

So, to answer your question: I don't think I want to add logic to encourage using something that I eventually want to remove from the documentation.

**Comment by Brixy** [comment]
> My brain was a little drained once I finished this feature …

I can believe that. The whole Hugo community appreciates your efforts very much.

Just tested: With

```
module:
  imports:
    - path: github.com/…/custom-hugo-theme
    - path: github.com/…/default-hugo-theme
```

you can simulate the old behaviour and benefit from all the possibilities.
