### ISSUE TITLE
Allow for richer metadata in taxonomy entries

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6174]
I'm just making notes of this after looking at it ... I'm not sure how great an idea it is.

We currently can do something ala:

```yaml
title: "Hugo Rocks!"
categories: 
- "cool"
- "funny"
categories_weight: 32
```

So, we currently have a `weight` that has an effect of the order _this page_ in the _categories_ listings.

Thinking about these taxonomies as _aggregated views_, we may want to have a more fine grained way of adding/overriding metadata. Something ala:

```yaml
title: "Hugo Rocks!"
categories: 
- cool
- funny:
  - title: "Hugo Rocks the funny boat!"
  - weight: 34

```
