### ISSUE TITLE
Allow specifying files in mounts

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#6221]
See the related discussion in #6219 for more info.

The gist is that it can be very handy to specify specific files in mounts like:

```yaml
module:
  mounts:
    - source:           site/static/docs/4.3/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/4.3/assets/img/favicons/favicon.ico
      target:           static/favicon.ico
```

**Comment by bep** [comment]
If the driving motivation behind the above is to get those icons placed in the root, what about:

```yaml
module:
  mounts:
    - source:           site/static/docs/4.3/assets/img/favicons
      target:           static
    - source:          site/static/docs/4.3/assets/img/favicons
      target:           static
```
