### ISSUE TITLE
Consolidate "content renderer" configuration

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6229]
Some notes and very much work in progress:

* We currently pick the "content renderer" by file extension with a possible override setting the `markup` in front matter (e.g. `markup:  md`; this became much easier to do on scale with `cascade`)
* We have a list of aliases, but in short `md = blackfriday`, `mmark = mmark`, `ad = asciidoc`, `org = org`.

This "thinking issue" relates to #5963.  If we decide to add Goldmark, then:

1. Goldmark will be the new default (with an adapter for the existing Blackfriday config)
2. I assume that we need/want to keep Blackfriday as an option for a transitional period.

This issue will try to specify:

* Any improvements in how we specify what `parser` and `renderer` to use.
* Output Formats may come into play here. We may want to think about how to specify a "renderer per output format" (HTML, ePub...)
* A new and consolidated configuration struct:

```toml
[contentFoo]
[contentFoo.blackfriday]
plainIDAnchors = true
hrefTargetBlank = false
angledQuotes = false
latexDashes = true
```
