### ISSUE TITLE
`hugo server` ignoring relativeURLs = true in HTML head

### ISSUE THREAD

**Issue by gleichda** [gohugoio/hugo#6362]
When running a hugo server hugo ignores the `relativeURLs = true` and `canonifyURLs = false` in config.toml

config.toml (emptied the strings)
```toml
languageCode = "en-us"
title = ""
relativeURLs = true
canonifyURLs = false

theme = "m10c"
[params]
  author = ""
  description = ""

    [[params.social]]
        name = "github"
        url = ""
    [[params.social]]
        name = "medium"
        url = ""
```

run command: ```hugo server --port ${PORT} --bind=0.0.0.0 --disableLiveReload --appendPort=false --baseURL ${BASE_URL} ```

Tested with and without --baseURL and now I'm using the `--appendPort=false` as a workaround.

With hugo server:
<img width="1244" alt="hugo server" src="https://user-images.githubusercontent.com/15176026/65376600-372cb400-dca2-11e9-8912-65c0abc8e0d8.png">

Verified a different behaviour with `hugo`:

```bash
$ cat public/index.html | grep stylesheet
    <link rel="stylesheet" href="./css/main.min.f90f5edd436ec7b74ad05479a05705770306911f721193e7845948fb07fe1335.css" />
```

```
$ hugo version
Hugo Static Site Generator v0.58.3-4AAC02D4 linux/amd64 BuildDate: 2019-09-19T15:30:47Z
$ uname -a
Linux 38c18c2cdeeb 4.19.44+ #1 SMP Tue Jul 30 23:06:26 PDT 2019 x86_64 Linux
# alpine:latest Docker Container
```
