### ISSUE TITLE
Infinite redirect with internationalization

### ISSUE THREAD

**Issue by hazcod** [gohugoio/hugo#6447]
### Hugo version
Hugo Static Site Generator v0.58.3/extended darwin/amd64
+ Latest netlify version (?)

## config.yaml
```yaml

assetDir: static
publishDir: generated

DefaultContentLanguage: en
languages:
    en:
        languageName: English
        weight: 1
    nl:
        languageName: Nederlands
        weight: 2


disableHugoGeneratorInject: true
#disableLiveReload: true

enableRobotsTXT: true

permalinks:
  posts: /:year/:month/:title/

outputFormats:
    - html:
        minify:true

minificationOptions:
    KeepConditionalComments: true
    KeepEndTags: false
```

### Issue
When visiting the default language on `/en/`, the site keeps infinitely redirecting.
This is because of response:
```html
<!DOCTYPE html><html><head><title></title><link rel="canonical" href=""/><meta name="robots" content="noindex"><meta charset="utf-8" /><meta http-equiv="refresh" content="0; url=" /></head></html>
```
