### ISSUE TITLE
DefaultContentLanguage[InSubdir] not changing

### ISSUE THREAD

**Issue by mirisbowring** [gohugoio/hugo#6479]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.59.1-D5DAB232 linux/amd64 BuildDate: 2019-10-31T15:21:02Z
</pre>

### Does this issue reproduce with the latest release?
yes

### Problem
I started configuring multilanguage support to my hugo project.  
In my `config.toml` I added:
```toml
LanguageCode = "de"
DefaultContentLangauge = "de"
DefaultContentLangaugeInSubdir = true
DisableLanguages = []

[languages]
    [languages.de]
        weight = 1
        languageName = "Deutsch"
    [languages.de.menu]
        [[languages.de.menu.main]]
            identifier = "projects"
            name = "Projekte"
            title = "Projekte"
            url = "/projects/"
            weight = 5
    [languages.en]
        weight = 2
        languageName = "English"
    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "projects"
            name = "Projects"
            title = "Projects"
            url = "/projects/"
            weight = 5
```
But when i start the server with:
```bash
hugo server --watch --debug
```
The logs are saying, that en ist still the default language and is not beeing added in a subdir:
```
DEBUG 2019/11/05 09:19:22 Write redirect to main language en: http://localhost:1313/
DEBUG 2019/11/05 09:19:22 creating alias: en redirecting to http://localhost:1313/
DEBUG 2019/11/05 09:19:22 Render XML for "sitemap" to "/en/sitemap.xml"
DEBUG 2019/11/05 09:19:22 Render XML for "sitemapindex" to "sitemap.xml"
```
I also tried to disable en (to check whether hugo would fallback to de) but that's not possible (because en is the default language):  
```
ERROR 2019/11/05 09:14:30 Cannot disable default language "en"
```

According to the docs and all guides i've read, i should have done the configuration right.  
  
My contents are organized by the file name:
```
my-projekt
└── content
    └── projects
        ├── post1.de.md
        ├── post1.en.md
        ├── post2.de.md
        └── post2.en.md
```

I am hoping for a quick fix or advice because I have to finish this project soon.

Thanks.
