### ISSUE TITLE
Add languageDirection to language configuration

### ISSUE THREAD

**Issue by frjo** [gohugoio/hugo#6550]
A number of languages are written from [right to left](https://en.wikipedia.org/wiki/Right-to-left) (rtl). It would be good to have a setting for that in Hugo languages.

You can already add any settings you like as a param and that is how I do it now for the sites that use a "rtl" language. But I think this deserves an official setting with a fixed name to make it easier for themes to implement.

The attribute that is set on the html tag is named "[dir](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir)" so I suggest we name the setting "languageDir". Similar to "languageName" that already is present.

A html template could then look like this:

``` html
<html class="nojs" lang="{{ .Site.Language.Lang }}" dir="{{ .Site.Language.LanguageDir | default "ltr" }}">
```

And the language configurations like this:

```
languages:
  sv:
    weight: 1
    languageName: "Svenska"
  en:
    weight: 2
    languageName: "English"
  ar:
    weight: 3
    languageName: "العربية"
    languageDir: "rtl"
```
