### ISSUE TITLE
`markdownify` no longer produces smartypants

### ISSUE THREAD

**Issue by XhmikosR** [gohugoio/hugo#6571]
With Hugo >= 0.60.0, when using the `markdownify` function, we no longer get smartypants.

```yml
markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false
```

```md
description: Get started with Bootstrap, the world's most popular framework for building responsive, mobile-first sites, with BootstrapCDN and a template starter page.
```

and this in a layout:

```html
<p class="bd-lead">{{ .Page.Params.Description | markdownify }}</p>
```

```diff
diff --git "a/C:\\Users\\xmr\\Desktop\\1.html" "b/C:\\Users\\xmr\\Desktop\\2.html"
index 4519767..a797964 100644
--- "a/C:\\Users\\xmr\\Desktop\\1.html"
+++ "b/C:\\Users\\xmr\\Desktop\\2.html"
@@ -1 +1 @@
-Get started with Bootstrap, the world’s most popular framework for building responsive, mobile-first sites, with BootstrapCDN and a template starter page.
+Get started with Bootstrap, the world's most popular framework for building responsive, mobile-first sites, with BootstrapCDN and a template starter page.

```
