### ISSUE TITLE
v0.60.0 Markdown code fences no longer highlighted using Pygments

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#6577]
I use pygments to highlight code fences. For example, I have this simple markdown code block:

<pre>
```yaml
key: value
array:
- val1
- val2
```
</pre>

With v0.59.0, I get this nicely syntax highlighted block via Pygments:

![image](https://user-images.githubusercontent.com/159209/70110230-35b52b80-1603-11ea-9333-eac222c510f6.png)

```
<div class="highlight" style="background: #eeeedd">
<pre style="line-height: 125%">
<code class="language-yaml" data-lang="yaml"><span></span>
<span style="color: #8B008B; font-weight: bold">key</span>: value
<span style="color: #8B008B; font-weight: bold">array</span>:
- val1
- val2
</code></pre></div>
```

After upgrading to v0.60.0 I get a lot more HTML generated, but the colors aren't really doing anything useful (for example, YAML field names are not highlighted):

![image](https://user-images.githubusercontent.com/159209/70110361-93497800-1603-11ea-92cb-001dc95b26e1.png)

```
<div class="highlight">
<pre style="background-color:#eed;-moz-tab-size:4;-o-tab-size:4;tab-size:4">
<code class="language-yaml" data-lang="yaml">key:<span style="color:#bbb"> </span>value<span style="color:#bbb">
</span><span style="color:#bbb"></span>array:<span style="color:#bbb">
</span><span style="color:#bbb"></span>-<span style="color:#bbb"> </span>val1<span style="color:#bbb">
</span><span style="color:#bbb"></span>-<span style="color:#bbb"> </span>val2<span style="color:#bbb">
</span></code></pre></div>
```

As for my config.yaml, I don't have any blackfriday settings or goldmark settings. I just have these:

```yaml
pygmentsUseClassic: true # disable Chroma
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
pygmentsUseClasses: false
pygmentsStyle: perldoc
```
