### ISSUE TITLE
Suggest markup.tableOfContents default change.

### ISSUE THREAD

**Issue by J-Siu** [gohugoio/hugo#6623]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.61.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

Theme: https://github.com/Vimux/Binario (latest pull master). (This theme use `{{ .TableOfContents }}` in post_toc.html. So it should not be the cause of following behavior.)

I tested with following md file.

```md
A test for hugo 0.61 with goldmark.

<!--more-->

# H1

## H2

### H3

#### H4

##### H5

###### H6

##### H5

#### H4

### H3

## H2

# H1
```

I believe following is the default(I read somewhere but can't find it, but the current behavior matches):

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 2
````

Following is result:

![Screen Shot 2019-12-16 at 8 35 01 PM](https://user-images.githubusercontent.com/3171920/70959473-6c029a00-204a-11ea-8173-c3254e14c8e8.png)

---

With:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 3
````

![Screen Shot 2019-12-16 at 9 26 03 PM](https://user-images.githubusercontent.com/3171920/70959617-be43bb00-204a-11ea-86bd-a2bd85c66581.png)

---

I trided a few other number and come to the conclusion that the ToC start indentation at `startLevel` + 2, not + 1.

I think a safer default value will be as follow:

```toml
[markup]
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
````
![Screen Shot 2019-12-16 at 8 39 45 PM](https://user-images.githubusercontent.com/3171920/70959633-c8fe5000-204a-11ea-915f-0a7c7a4823e3.png)

This will be safe as long as H1 (#) is not used (and properly should not) inside md file.
