### ISSUE TITLE
hugo deploy ignores patterns always removing files

### ISSUE THREAD

**Issue by ssbarnea** [gohugoio/hugo#6681]
My website is hosted on a AWS S3 bucket which also containst other files not managed by hugo. That works on a bare domain which means that I cannot move conttent another bucket to isolate hugo generated site.

I tried to use patterns to control deployment but apparent it has zero effect, it always ignore them.
```
deployment:
  targets:
    - name: aws
      URL: s3://bucket?region=eu-west-1
  matchers:
    - pattern: "^posts\\/"
```

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### References
* https://discourse.gohugo.io/t/hugo-deploy-deletes-not-respecting-patterns/22533
