### ISSUE TITLE
Allow content mounts to be files

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6684]
I was trying to make a portable GitHub type of repo with render hooks and tried this:

```toml
[module]
  [[module.mounts]]
    source = "README.md"
    target = "content/_index.md"
```

This failed:

```bash
 Error building site: process: readAndProcessContent: walk: Readdir: fdopendir: not a directory
```
