### ISSUE TITLE
Hugo CSS minify breaks AMP validation

### ISSUE THREAD

**Issue by braderhart** [gohugoio/hugo#6699]
## Description
Hugo is stripping the space after a parenthesis when doing minification. This happens when doing both resource minification, or when using the `--minify` option.

Un-minified:
```css
body {
	-webkit-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
	-moz-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
	-ms-animation: -amp-start 8s steps(1,end) 0s 1 normal both;
	animation: -amp-start 8s steps(1,end) 0s 1 normal both
}
```

Minified:
```css
body{-webkit-animation:-amp-start 8s steps(1,end)0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end)0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end)0s 1 normal both;animation:-amp-start 8s steps(1,end)0s 1 normal both}
```

The issue is here `steps(1,end)0s`.

Oddly, when testing with the minify module Hugo is using [here](https://go.tacodewolff.nl/minify) it works correctly:

```css
body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}
```

## What version of Hugo are you using?
```Hugo Static Site Generator v0.62.0/extended linux/amd64 BuildDate: unknown```

## Does the issue happen in the latest release?
Yes
