### ISSUE TITLE
Handle ambiguity in reverse indexes for .GetPage 

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#6701]
The fix for #6696 works in the simple cases, but was a little hastily added to get the "truly portable links" demo up and running without thinking about the big picture.

This problem applies to both file and dir mounts, but is easier to explain with a file.

With two different modules that each defines a content mount:

```toml
[module]
  [[module.mounts]]
    source = "page.md"
    target = "content/blog/article.md"
```

```toml
[module]
  [[module.mounts]]
    source = "page.md"
    target = "content/docs/tutorial.md"
```

Then a reference to `/page.md` would be ambiguous.

To cut the discussion short, I think the only solution would be to say that:

* Use `.Page.GetPage` if you need to link using source references that may differ from the target (as used in https://github.com/bep/portable-hugo-links/)
* For these references, we will only look in the module and mount that the Page comes from.

/cc @kaushalmodi @regisphilibert @onedrawingperday
