### ISSUE TITLE
Heading render hooks to allow better fixing of header overlaps in themes

### ISSUE THREAD

**Issue by dudleycodes** [gohugoio/hugo#6711]
**The Issue**

Many websites include non-scrolling headers that are fixed to the top and have a defined height. When clicking on a URL anchor (`#fragment`) browsers do not respect the height of the fixed header resulting in users being taken too far down the page.

**Background**

A quick and dirty fix would be to nest a span inside all heading elements like so:

```html
<h3><span id="one"></span>one</h3>
```
and then the HUGO theme's styling could make adjustments as needed:

```css
h3{ position:relative; }
h3 span{ position:absolute; top:-120px;}
```

The issue with this approach is that it could break a lot of existing HUGO themes out there.

**Proposal**

Add a render hook template for headings that would allow theme developers to modify headings, such as in the "dirty" example above, as needed by the theme.

For example, `/layouts/_default/_markup/render-h1.html`, could be written as:

```html
<h1><span id="{{ .Id }}"></span>{{ .Content }}</h1>
```

**Comment by dudleycodes** [comment]
For anyone who stumbles across this feature request here's a SCSS workaround. It works but definitely causes a browser performance hit. I recommend further-narrowing the selector scope as much as you can.

```scss
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    &[id]::before {
      /* Header height offset for anchor links */
      content: "";
      display: block;
      height: var(--menu-height);
      margin-top: calc(var(--menu-height) * -1);
      visibility: hidden;
    }
  }
```
