### ISSUE TITLE
Local module: file does not exist

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6722]
Reading this [thread](https://discourse.gohugo.io/t/modules-error-file-does-not-exist/20794) I think the setup form this test [repo](https://github.com/regisphilibert/hugo-issue-6722) should work. Yet I get the following error: 
```
Error: add site dependencies: load resources: loading templates: walk: open "debug" (""): file does not exist
```

What it does is try and load a module whose files are stored locally (in the themes directory as mentioned in the doc) and use the mounts directive to assign its directory to Hugo's filesystem.

```
module:
  imports:
    - path: imgix
```

And from the module config.yaml:
```
module:
  hugoVersion:
    extended: false
    min: "0.62.2"
  mounts:
    - source: debug
      target: layouts/partials/debug
```
