### ISSUE TITLE
Walk error when mount target more than one level down

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6730]
When trying to map mounts with the following: 

```
module:
  imports:
  - path: github.com/theNewDynamic/hugo-module-imgix
    mounts:
      - source: func
        target: layouts/partials/func
      - source: markup
        target: layouts/_markup
      - source: data
        target: data
```

I get 
```
Error: add site dependencies: load resources: loading templates: walk: open "func" (""): file does not exist
```

`func` is the only failing mount, which might indicate it is due to it being in a"sub directory".
Might share some causes with https://github.com/gohugoio/hugo/issues/6209

### Config
```
macOS Catalina 10.15.2 (19C57)
go version go1.12.4 darwin/amd64
Hugo Static Site Generator v0.62.2-83E50184/extended darwin/amd64 BuildDate: 2020-01-05T18:56:31Z
```
### Repos 

Project Test Repo: https://github.com/theNewDynamic/hugo-module-imgix/releases/tag/v0.0.1 (dedicated release)
Module Repo: https://github.com/theNewDynamic/hugo-module-imgix

### Step to reproduce:

1. Clone Project Test Repo
2. Hit `hugo` or `hugo serve` using latest Hugo version.
