### ISSUE TITLE
RSS output link does not contain base url

### ISSUE THREAD

**Issue by loikein** [gohugoio/hugo#6744]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.62.2/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

### Discription
This issue roughly started after Hugo 0.55, since I remembered thinking there was something wrong with the way I implement the new formatting. 
For example, all my post as in RSS readers have since appeared as `/post/2019/mm/title`, which was not true before.
I use my own theme without specifying `rss.xml`, so I am assuming that this must be something to do with Hugo generator's embedded RSS template.

Any help is welcome!

**Comment by loikein** [comment]
Bump.

Further discription:
For example, following is the output of my website using default RSS template. Note how the `<link>`'s were wrongly generated. 

```xml
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>loikein's notes</title>
<link>/</link>
<description>Recent content on loikein's notes</description>
<generator>Hugo -- gohugo.io</generator>
<language>en-gb</language>
<lastBuildDate>Fri, 30 Nov 2018 00:00:00 +0000</lastBuildDate>
<atom:link href="/index.xml" rel="self" type="application/rss+xml" />
<item><title>Notes on The Missing Semester of Your CS Education</title>
<link>/post/2020/05/notes-missing-semester/</link>
…
```

**Comment by bep** [comment]
The built-in template uses `Permalink` which I'm confident adds the baseURL ... if it's set.

**Comment by loikein** [comment]
It is set, unfortunately.

**Comment by loikein** [comment]
<details><summary>My `config.yaml`:</summary>

```yaml
baseUrl: 'https://notes.loikein.one/'
languageCode: en-gb
title: loikein's notes
theme: hugo-lithium-loikein
googleAnalytics: UA-143089736-1
disqusShortname: loikein-github
ignoreFiles:
  - \.md$
  - \.Rmd$
  - \.Rmarkdown$
  - \.ipynb$
  - _files$
  - _cache$
hasCJKLanguage: true
rssLimit: 50

publishDir: ../loikein.github.io

permalinks:
  post: '/:section/:year/:month/:slug/'

menu:
  main:
    - name: Notes
      url: /post/
      weight: 1
    - name: Writings
      url: /writings/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Search
      url: 'https://duckduckgo.com/?q=site%3Anotes.loikein.one'
      weight: 4
    - name: Source
      url: 'https://github.com/loikein/loikein.github.io'
      weight: 10

params:
  description: 'Personal research blog about math, economics and programming'
  footer: loikein
  disqusURL: 'https://notes.loikein.one'

  highlightjsVersion: 10.0.0
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - python
    - applescript

  highlightjsTheme: github
  favicon: favicon.ico
  logo:
    url: logo.png
    width: 50
    height: 50
    alt: Home
```
</details>
