### ISSUE TITLE
Less-than not escaped in code blocks with Blackfriday

### ISSUE THREAD

**Issue by jgreely** [gohugoio/hugo#6856]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.60.1-96066756 darwin/amd64 BuildDate: 2019-11-29T14:59:30Z
$ hugo version
Hugo Static Site Generator v0.64.0-241DB8F7 darwin/amd64 BuildDate: 2020-02-04T09:10:23Z
</pre>

The less-than character is not being escaped in code blocks if you render with Blackfriday under 0.60-0.64. Worked in 0.59.1.

Here's a sample one-page site:

https://github.com/jgreely/hugo-blackfriday-code-bug

**Comment by satotake** [comment]
@jgreely 

Hugo >= 0.60 is supposed to have a bug of syntax highlight feature with blackfriday.
So, unless you require highlighting feature, this can be avoided with configuration like 

```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.highlight]
    codeFences = false
```

`goldmark` has its own highlighting feature.
And Hugo >= v0.6.0 uses it when `goldmark` is set as markdown handler.
Therefore it works fine with `goldmark`
