### ISSUE TITLE
defaultContentLang not taken into account for hugo new

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#6895]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.0-DEV linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

---

Sample config:

```
baseURL = "https://www.example.com/"
title = "Lorem"
defaultContentLanguage = "el"
defaultContentLanguageInSubdir = true

[languages.el]
description = "Lorem"
languageName = "ΕΛ"
languageCode = "el"
contentDir = "content/el"
weight = 1

[languages.en]
description = "Lorem"
languageName = "EN"
languageCode = "en"
contentDir = "content/en"
weight = 2
```

I expected that changing to `defaultContentLanguage = "en"` and executing `hugo new` would create the content file under `content/en`.

Instead the content file was again created under `content/el`

It seems that Hugo takes into account the first instance of the `contentDir` parameter and ignores the `defaultContentLanguage ` parameter.

---

Related GitHub issues: #5233 , #5234

**Comment by jzeneto** [comment]
This still occurs in Hugo 0.84.2, but here the situation is a bit different: `hugo new` takes `en` regardless of `defaultContentLanguage` value.

```toml
# in config/_default/config.toml
defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false

# in config/_default/languages.toml
[pt]
contentDir = "content/pt"
[en]
contentDir = "content/en"
```

With that config, issuing `hugo new test` returns `<path>/content/en/test created` (`<path>` is my site's folder).
