### ISSUE TITLE
Panic when home page is drafted

### ISSUE THREAD

**Issue by Tnze** [gohugoio/hugo#6927]
### What version of Hugo are you using (`hugo version`)?
Installed by brew.
<pre>
$ hugo version
Hugo Static Site Generator v0.65.1/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
yes

```bash
$ hugo server
Building sites … panic: BUG: parent not set for "/categories"

goroutine 90 [running]:
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleTaxonomies.func1(0xc00067b330, 0xb, 0x563f8a0, 0xc000894c30, 0xc000644100)
        /private/tmp/hugo-20200220-49331-1p75klb/hugo-0.65.1/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:526 +0x79c
github.com/armon/go-radix.recursiveWalk(0xc000894c60, 0xc000833de8, 0x563f800)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc000894cc0, 0xc000833de8, 0xc000833d00)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000271020, 0xc000833de8, 0xc000833e00)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleTaxonomies(0xc0004eba70, 0x0, 0x0)
        /private/tmp/hugo-20200220-49331-1p75klb/hugo-0.65.1/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:514 +0x92
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc0004eba70, 0x0, 0x0)
        /private/tmp/hugo-20200220-49331-1p75klb/hugo-0.65.1/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:724 +0xd4
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
        /private/tmp/hugo-20200220-49331-1p75klb/hugo-0.65.1/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:772 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc0007c9f68, 0x0)
        /private/tmp/hugo-20200220-49331-1p75klb/hugo-0.65.1/src/github.com/gohugoio/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008946c0, 0xc0008b0100)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**Comment by bep** [comment]
Do you have your site source somewhere where I can have a look?

**Comment by Tnze** [comment]
> Do you have your site source somewhere where I can have a look?

That's a private repo. But I have successfully reproduced it in the following steps：

1. Create a new site: `hugo new site .`
2. Download [hermit](https://github.com/Track3/hermit) theme.
3. 
```bash
hugo new posts/first_post.md
hugo new posts/_index.md
hugo new _index.md
```

And then it's panic.

config.toml
```toml
baseURL = "http://example.org/"
languageCode = "zh-cn"
title = "Jdao.online"
theme = "hermit"
hasCJKLanguage = true
copyright = ''

enableRobotsTXT = true

pygmentsStyle = "solarized-dark"
pygmentsCodeFences = true
pygmentsCodefences  = true
pygmentsUseClasses  = true

[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[author]
    name = "Tnze"

[params]
    author = "Tnze"
    bio = "There are 10 kinds of people in the world, one knows binary, the other don't."
    subtitle = "Record what I learned at ordinary times"
    homeSubtitle = "Record what I learned at ordinary times"
    
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    themeColor = "#494f5c"
    footerCopyright = ''
```
