### ISSUE TITLE
Exclude self from `cascade`.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#6940]
Currently the keys/value stored in the reserved `cascade` map are applied to children **and** self. I originaly supported this decision to better align with my own understanding of `cascading` but after months of using the feature, I feel it has proven cumbersome as, more often than not, `cascade` values will not apply to self. 

This forces the user to overwrite `cascade` values from self's FM for the most commonly used `cascade` keys like `outputs` or `draft` or the newly introduced `_build`.

Today, in order to build a section whose children should not `render` you have to:

```
---
title: Persons
# cascade overwrite for self
_build:
  render: true
# cascade
cascade:
  _build:
    render: false
```

Today to build a section whose children will produce `ical` files:

```
---
title: Events
# cascade overwrite for self
outputs:
  - HTML
  - RSS
# cascade
cascade:
  outputs:
    - HTML
    - ICAL
```

For this reason, I think we should question this behaviour, by maybe polling users, and consider a change. (discussing breaking changes, address in documentation etc...)
