### ISSUE TITLE
taxonomy permalinks behaviour has changed/no longer working

### ISSUE THREAD

**Issue by jonisbell** [gohugoio/hugo#7065]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.67.1 linux/amd64 BuildDate: 2020-03-16T08:05:22Z
</pre>

### Does this issue reproduce with the latest release?

Yes

To provide continuity with our previous blogging software we created pagination at the year, month and day directories.

eg
* `/archives/2020/01/01/blog-post.html`
* `/archives/2020/01/01/` and `/archives/2020/01/01/page/2`
* `/archives/2020/01/` and `/archives/2020/01/page/2`
* `/archives/2020/` and `/archives/2020/01/page/2`

We did this using a script which added frontmatter based on the date of the post:

eg
```
day: 2020/03/03
month: 2020/03
year: '2020'
```

And the following permalinks config in `config.yaml`.

```
taxonomies:
  category: categories
  year: year
  month: month
  day: day

permalinks:
  posts: /archives/:year/:month/:day/:filename/
  categories: /archives/category/:slug/
  year: /archives/:year/
  month: /archives/:year/:month/
  day: /archives/:year/:month/:day/
```

We're currently using Hugo 0.58.3 and this works perfectly but now we're attempting to upgrade to Hugo 0.67.1 but this no longer works correctly.

The behaviour in 0.67.1 is that pagination for the years (at `/archives/2020/page/2`, etc) is created but no pagination is created for months or days. Instead, a single set of directories is created `/archives/1/01/01/page/2` and `/archives/1/01/page/2`, etc. These taxonomies index.html files contain the most recent day and month of blog posts.

I believe this may be related to the changes in https://github.com/gohugoio/hugo/commit/b2dcd53e3c0240c4afd21d1818fd180c2d1b9d34
