### ISSUE TITLE
Make build.list:false into an enum with more meanings

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7075]
I started to use the construct below to create headless sections and bundles:

```yaml
cascade:
    _build:
        render: false
        list: false
        publishResources: false
```

And it caught me a little bit by surprise that `list:false` in the above would also exclude them from `$headless_section.Pages/RegularPages`, this throws away a bunch of very useful use cases.

So, I see how you would want the above behaviour _some of the times_ (private pages ...), but I think it's more common to use the above as a "navigation inside the headless bundle", to make tree structures (menus), product listings etc.

So, I will make sure that `list:false/true` will still work, but I'm changing it to be a an enum:

```
list: never, always, local
```

```yaml
cascade:
    _build:
        render: false
        list: local
        publishResources: false
```

The above would then make any page available via `$p.Pages` and `$p.RegularPages`, but not via `site.RegularPages` and `site.Pages`.

Protests/etc. welcome.

/cc @regisphilibert @kaushalmodi @onedrawingperday @budparr
