### ISSUE TITLE
Hugo0.65:keywords of html mata,Add square brackets automatically

### ISSUE THREAD

**Issue by hollson** [gohugoio/hugo#7105]
In my toml of page，like this
```toml
+++
title= "my post title"
keywords= "keyword1,keyword2,keyword3"
date= 2020-03-29
+++
```

but in my html page，Becomes like this，Is it really necessary to add square brackets?
```html 
<meta name="keywords" content="[keyword1,keyword2,keyword3]">
```
