### ISSUE TITLE
Empty list items in table of contents when heading structure skips a level

### ISSUE THREAD

**Issue by exprez135** [gohugoio/hugo#7128]
### What version of Hugo are you using (`hugo version`)?

v0.68.3 on macOS via HomeBrew
### Does this issue reproduce with the latest release?

Yes.

---

Whenever I enable the Table Of Contents in a situation without any `endLevel` specified in the site configuration:
> ## Extra-Curriculars
> #### Heading Four Here without Heading Three Before It
> ## Technology
> #### Heading Four Here without Heading Three Before It

The Table of Contents comes out looking like this:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/16708935/78458027-23f89900-7674-11ea-8f2b-ce55623499a6.png">

I believe the expected behaviour would be for no extra bullet point to appear (or to appear with the H4).

If I add an H3:
> ## Extra-Curriculars
> ### Testing
> #### Heading Four Here
> ## Technology
> #### Heading Four Here without Heading Three Before It
then:
<img width="510" alt="image" src="https://user-images.githubusercontent.com/16708935/78458028-29ee7a00-7674-11ea-8f9a-ad145b034bae.png">

### Work-Around
If I manually set an `endLevel`, the problem disappears. It is only when one is not set that the problems occur.

**Comment by exprez135** [comment]
Related support thread I opened on the forum: https://discourse.gohugo.io/t/requesting-help/9132.

**Comment by jmooring** [comment]
Please re-open.

To reproduce:

```
git clone --single-branch -b hugo-github-issue-7128 https://github.com/jmooring/hugo-testing hugo-github-issue-7128
cd hugo-github-issue-7128
hugo server
```

Contrary to the original report, the follow does **not** resolve the problem:

```
[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2
```

Related: <https://discourse.gohugo.io/t/24460>

**Comment by jmooring** [comment]
Please re-open.

**Comment by tejasjadhav** [comment]
I possible workaround for this was using CSS

For me, this is how it looked like earlier
![image](https://github.com/user-attachments/assets/6d213aef-368b-428c-8e49-e2a5b5f552e6)

I applied the following CSS rules
```css
.table-of-contents ul {
  padding-inline-start: 0;
  list-style: none;
}

.table-of-contents ul:has(> li > a) {
  padding-inline-start: 40px;
  list-style: disc;
}
```

This resulted in the following output
![image](https://github.com/user-attachments/assets/7998e46c-f6ed-4df2-bd5a-7028212e4bbb)

This retains the nesting, but at the same time, hides indentation for empty lists

**Comment by jerrychan7** [comment]
For anyone running into similar ToC issues, I wrote a template library that generates a ToC.
[https://github.com/jerrychan7/hugoPerfectToC](https://github.com/jerrychan7/hugoPerfectToC)
This project can correctly generate the table of contents, but the disadvantage is that the performance is relatively poor.
Since the project parses HTML, it can theoretically parse any extension correctly. Or work with the heading rendering hook.

<details>
<summary>Example configuration, and markdown file (click to expand)</summary>

Assuming the extension is enabled:

```yaml
markup:
  goldmark:
    extensions:
      strikethrough: false
    extras:
      subscript:
        enable: true
```

For the following markdown:

```md
---
title: "Markdown Syntax Guide"
date: 2024-10-01T23:17:15+08:00
draft: false
---

#### not h1/h2 first

------------------------------

## Headings

↓ The heading in the blockquote element.
  Hopefully it will be possible to jump by ID, the same behavior as other heading elements.

> # H1 in blockquote
>
> ## H2 in blockquote

------------------------------

## Table

##### non-incrementing heading

↑ Some non-incrementing headings.

------------------------------

# heading in ul/ol

* ## h2 in top level
  * ### h3 in sub-level
* #### h4 in top level

------------------------------

# H~2~O

```

</details>

Comparison between the directory generated by Hugo and the directory generated by my project:

| `PAGE.TableOfContents` | ToC generated by my project |
|---|---|
| <ul><li><ul><li><ul><li><ul><li>not h1/h2 first</li></ul></li></ul></li><li>Headings</li></ul></li><li>H1 in blockquote<ul><li>H2 in blockquote</li><li>Table<ul><li><ul><li><ul><li>non-incrementing heading</li></ul></li></ul></li></ul></li></ul></li><li>heading in ul/ol<ul><li>h2 in top level<ul><li>h3 in sub-level<ul><li>h4 in top level</li></ul></li></ul></li></ul></li><li>H2O</li></ul> | <ul><li>not h1/h2 first</li><li>Headings<ul><li>H1 in blockquote<ul><li>H2 in blockquote</li></ul></li></ul></li><li>Table<ul><li>non-incrementing heading</li></ul></li><li>heading in ul/ol<ul><li>h2 in top level<ul><li>h3 in sub-level</li></ul></li><li>h4 in top level</li></ul></li><li>H<sub>2</sub>O</li></ul> |

**Comment by jmooring** [comment]
I'm closing this.

1. Markdown headings should not be incremented by more than one level at a time. If you are using heading levels to change appearance, don't. Use CSS instead, either globally to style all headings of the same level, or use [Markdown attributes](https://gohugo.io/content-management/markdown-attributes) to style individual headings. For example:

    ```text
    ## Section 1 {class=foo}
    ```

    or

   ```
   ## Section 2 {style="font-size: 12px"}
    ```

2. If you ignore the guidance above, use this CSS to remove the marker from list items that don't have a direct link:

    ```css
    /* 1. Ensure items with links always behave like standard list items */
    #TableOfContents li:has(> a) {
      display: list-item;
    }
    
    /* 2. Remove the marker from LIs that don't have a direct link */
    #TableOfContents li:not(:has(> a)) {
      display: contents;
    }
    
    /* 3. Maintain indentation for nested lists inside the "markerless" LIs */
    #TableOfContents li:not(:has(> a)) > ul,
    #TableOfContents li:not(:has(> a)) > ol {
      display: block;
      padding-left: 40px; /* Standard browser indentation */
      margin-block: 0;    /* Prevents awkward vertical gaps */
    }
    ```

   Note that the above works with both ordered and unordered lists.
