### ISSUE TITLE
Bug: setting related.toLower = true changes param display

### ISSUE THREAD

**Issue by carlmjohnson** [gohugoio/hugo#7198]
I was playing with related content indices and I set this in my config.toml:

```toml
[related]
includeNewer = true
threshold = 0
toLower = true

[[related.indices]]
  name  = "series"
  weight = 200

[[related.indices]]
  name = "topic"
  weight = 200

[[related.indices]]
  name = "title"
  weight = 150

[[related.indices]]
  name  = "kicker"
  weight = 100

[[related.indices]]
  name  = "authors"
  weight = 100
```

When I did so, the authors became lower case on my pages, presumably because the data underlying the slice was mutated.

### What version of Hugo are you using (`hugo version`)?

Hugo Static Site Generator v0.69.0/extended darwin/amd64 BuildDate: unknown
