### ISSUE TITLE
Multiple menus doesn't work if menu name contains upper case letter

### ISSUE THREAD

**Issue by minitauros** [gohugoio/hugo#7245]
### What version of Hugo are you using (`hugo version`)?

v0.69.2

### Does this issue reproduce with the latest release?

Yes

## How to reproduce

/content/en/_index.html

```
---
menu:
    main:
        weight: 1
    footerLeft:
        weight: 1
---
```

/content/en/about.html

```
---
title: About us
translationKey: about
menu:
    main:
        weight: 2
    footerLeft:
        weight: 4
---
```

in /layouts/_default/baseof.html

```
{{ range .Site.Menus.footerLeft }}
    <li>
        <a href="{{ .URL }}"
           class="{{ if $currentPage.IsMenuCurrent " footerLeft" . }}active{{ end }}"
        >{{ .Name }}</a>
    </li>
{{ end }}
```

Both items do not appear in the menu.

If I change the front end matter from an array with objects to an array with strings, i.e. 

```
---
title: About us
translationKey: about
menu:
    - main
    - footerLeft
weight: 4
---
```

boom it's in the menu.

If I change the menu name to all-lowercase, i.e. `footer`, it also works.

Documentation does not seem to mention anything about this, so I'm assuming it's not supposed to happen.
