### ISSUE TITLE
defaultContentLanguage case sensitivity

### ISSUE THREAD

**Issue by grachov** [gohugoio/hugo#7264]
With the config like this:

```yaml
defaultContentLanguage: en-US

languages:
  en-US:
    ...
```

I get error:

```
Error: site config value "en-US" for defaultContentLanguage does not match any language definition
```

Changing `en-US` to `en-us` in both places solves the issue. Is it expected, as I did not find any mention in the documentation?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.70.0-7F47B99E linux/amd64 BuildDate: 2020-05-06T11:18:50Z
</pre>

### Does this issue reproduce with the latest release?
Yes
