### ISSUE TITLE
Error building site: plain HTML documents not supported

### ISSUE THREAD

**Issue by kaihendry** [gohugoio/hugo#7296]
Hugo Static Site Generator v0.70.0/extended linux/amd64 BuildDate: unknown

When using a valid markdown file: https://s.natalian.org/2020-05-20/Nexus_One.md

I get **plain HTML documents not supported** and Hugo errors out.

You can have HTML in Markdown. I've even gone through the hoop jump of

```
markup:
  goldmark:
    renderer:
      unsafe: true
```
