### ISSUE TITLE
Add server.redirects/rewrite support support

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7323]
Syntax and motivation stolen from Netlify docs:

```toml
# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

Note that we must do rewrites for status == 200, see https://docs.netlify.com/routing/redirects/rewrites-proxies/#limitations
