### ISSUE TITLE
Allow a taxonomy term to be an object with parameters

### ISSUE THREAD

**Issue by jordan-dlh** [gohugoio/hugo#7371]
This is a proposal to extend Hugo's handling of taxonomy terms in front matter.

**Proposal:** In a page's front matter, allow a taxonomy term (in the following examples: contributors) to be an object and not only a string. So we would go from this:
```
---
title: example
contributors:
  - jordan
  - julian
---
Lorem Ipsum
```
To this:
```
---
title: example
contributors:
  - name: jordan
    params:
        role: author
  - name: julian
    params:
        role: editor
---
Lorem Ipsum
```
Of course this would not be mandatory.

The intended effect is that in a page template, we could leverage the presence of parameters to show (in this example) the exact role a contributor has relatively to this page, and this can change from page to page for the same contributor (so it can not be a parameter in the term's own page). At the moment of writing this is only possible in a contrived (imho) way, by duplicating some information in another object of the front matter (see https://discourse.gohugo.io/t/custom-parameter-for-a-taxonomy-in-front-matter/24835).

This proposal makes it so the syntax is the same as for pages resources so it is not surprising. It also makes it so that in absence of particular handling, the taxonomy terms are used just as usual (with .Permalink and .LinkTitle typically). An adequate handling would be to check if .Params.role is set, in my example, and show it if so.
