### ISSUE TITLE
Update to gopkg.in/yaml.v3

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7404]
Will need to do a review of the "what could break" ...

## Notes from the upgrade

It now complains on duplicate keys, a good thing (there were some bad test data in there):

```yaml
title: Tax NB
weight: 8
publishdate: "2000-01-06"
weight: 1002
lag:
- Sogndal
```
