### ISSUE TITLE
How does the org front matter format work on an associative array?

### ISSUE THREAD

**Issue by xinii** [gohugoio/hugo#7440]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### How does the org front matter format work on an associative array?
If there is a YAML front matter like this,

```yaml
title: an amazing title
tags:
- tag1
- tag2
menu:
  example:
    parent: Example Topic
    weight: 1
```

From the official [docs](https://gohugo.io/content-management/front-matter/#front-matter-formats), we know that we can translate a part of above to an org front matter like this,
```org
#+title: an amazing title
#+tags[]: tag1 tag2
```

But how to handle the following part?
```yaml
menu:
  example:
    parent: Example Topic
    weight: 1
```

I tried the following way which seems a little bit stupid, but it didn't work.
```org
#+menu: example
#+menu.example.parent: Example Topic 
#+menu.example.weight: 1
```
