### ISSUE TITLE
Hugo Module Imports: Allow version reference in module config.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#7475]
### The problem

For now it is not possible for a Hugo Module to enforce a version for its imports from its `config.yaml`.

```
# currentmodule/config.yaml
module:
  imports:
  - path: github.com/whodat/hugo-anothermodule
```

Which means, any Hugo projects importing `currentModule` will end up with the latest version of `anotherModule` unless they manipulate the `go.mod` file with `hugo mod get -u` or by hand. 
Which means, the maintainers of `currentModule` have no way, unless through documentation, to ensure their users are using the right, tested, validated version of `anotherModule`.

### Currently

Current behaviour imports the latest version of any module whose path is added to the `module.imports` array and records it on the upmost project's `go.mod` require statements.

### Proposal

I think we could add another key "version" the the imports entries which could now only support `latest` or a string matching a symver tag/release. 
(Other variations, like `>1.0.2 <=2.3.4` or `3.3.x` would be welcome but really not that important at the moment.)

```
# currentmodule/config.yaml
module:
  imports:
  - path: github.com/whodat/hugo-anothermodule
    version: v0.1.3
```

```
# hugo-website/config.yaml
module:
  imports:
  - path: github.com/thatteam/hugo-currentmodule
    version: latest
```
