### ISSUE TITLE
The `range` function returns an array in the wrong order.

### ISSUE THREAD

**Issue by joywek** [gohugoio/hugo#7491]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.72.0/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

My template code:
```
      <ul class="site-menu">
        {{ $currentPage := . }}
        {{ range .Site.Menus.main }}
          <li class="site-menu-item {{ if $currentPage.HasMenuCurrent "main" . }}active{{ end }}">
            <a href="{{ .URL }}">{{ .Name }}</a>
          </li>
        {{ end }}
      </ul>
```

The site configuration:
```
menu:
  main:
  - name: HOME
    url: /
  - name: BLOG
    url: /blog/
  - name: ABOUT
    url: /about/
```

Result:

```
ABOUT | BLOG | HOME
```
