### ISSUE TITLE
Front matter maps and order

### ISSUE THREAD

**Issue by pavelstoev-lci** [gohugoio/hugo#7535]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.74.3-DA0437B4
</pre>

### Does this issue reproduce with the latest release?

<pre>
Yes.
</pre>

Consider the following YAML front matter:

```yaml
steps:
  bbb:
    - item11
    - item12
    - item13
  AAA:
    - item21
    - item22
    - item23
```

Issue 1: Using the following Hugo code always prints `aaa` and `bbb` lowercase (text casing is lost):

```html
{{- range $ii, $ee := steps -}}
{{ $ii }} {{ $ee }}
{{- range $i, $e := $ee -}}
{{ $i }} {{ $e }}
{{- end -}}
{{- end -}}
```

Issue 2: It may be by design based on my research - the order is lost and AAA comes first.

Both issues are not obvious based on how one reads the front matter and some (reasonable I think) expectations and difficult to work around - for issue #1 I had to force the use of title case function, and for issue #2 I had to invent a prefix which is then sorted by before being removed from the output.
