### ISSUE TITLE
Invalid permalinks generated by helpers

### ISSUE THREAD

**Issue by widget** [gohugoio/hugo#7596]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3-DA0437B4 linux/amd64 BuildDate: 2020-07-23T16:22:34Z
</pre>

### Does this issue reproduce with the latest release?

Latest is 0.74.3

### Problem

Permalinks can be generated with `#` characters, for example my site used the permalink configuration

```toml
[permalinks]
page = "/:slug/"
post = "/:year/:month/:title/"
```

and a front matter of

```yml
title: "Slipgate After-Action Report #1"
date: 2020-07-25
tags:
  - sgcp
categories:
  - aar
```

Generates a file of `public/2020/07/slipgate-after-action-report-#1/index.html`.  This is a valid Linux path but not a valid uri, see [RFC 2396](https://www.ietf.org/rfc/rfc2396.txt).  This is due (I think) to `URLize` in `helpers/url.go`.
