### ISSUE TITLE
Problem mounting non-rooted mount into data root

### ISSUE THREAD

**Issue by richtera** [gohugoio/hugo#7616]
compile on master

<pre>
$ hugo version
Hugo Static Site Generator v0.75.0-DEV-ED754F5A/extended darwin/amd64 BuildDate: 2020-08-31T07:15:27-0400
</pre>

### Does this issue reproduce with the latest release?
Yes.

Using a mount with

`target: data/somefolder`

mounts the source at the root of the data folder.

**Comment by richtera** [comment]
Sample output of hugo config mounts
```zsh
% hugo --config ./.config.yml config mounts
{
   "path": "project",
   "dir": "/Users/andy/Development/platform-themes",
   "mounts": [
      {
         "source": "content",
         "target": "content"
      },
      {
         "source": "data",
         "target": "data"
      },
      {
         "source": "repos/builder-course-PlvZSzcF2VNeXanE8IWQ/content",
         "target": "content/courses/PlvZSzcF2VNeXanE8IWQ"
      },
      {
         "source": "repos/builder-course-PlvZSzcF2VNeXanE8IWQ/data",
         "target": "data/PlvZSzcF2VNeXanE8IWQ"
      },
      {
         "source": "layouts",
         "target": "layouts"
      },
      {
         "source": "i18n",
         "target": "i18n"
      },
      {
         "source": "archetypes",
         "target": "archetypes"
      },
      {
         "source": "assets",
         "target": "assets"
      },
      {
         "source": "static",
         "target": "static"
      }
   ]
}
{
   "path": "module-student-template-combined@feature-data-builds",
   "dir": "/Users/andy/Development/platform-themes/themes/module-student-template-combined@feature-data-builds/",
   "mounts": [
      {
         "source": "archetypes",
         "target": "archetypes"
      },
      {
         "source": "assets",
         "target": "assets"
      },
      {
         "source": "data",
         "target": "data"
      },
      {
         "source": "layouts",
         "target": "layouts"
      },
      {
         "source": "static",
         "target": "static"
      }
   ]
}
```
Sample config file
```yaml
baseURL: /
languageCode: en-us
title: SelfStudy Learning Site
disablePathToLower: true
params:
  type: shortcodes
  date_format: Monday, Jan 2, 2006
  copyright: SelfStudy Inc. All rights reserved.
  disable_mathjax: true
  features:
    lock: false
    studybar: false
    theme: light
blackfriday:
  plainIDAnchors: true
  hrefTargetBlank: true
  fractions: false
  extensions:
    - EXTENSION_HARD_LINE_BREAK
    - EXTENSION_LAX_HTML_BLOCKS
    - EXTENSION_SPACE_HEADERS
markup:
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - html
    - rss
  section:
    - html
    - json
  page:
    - html
    - json
theme: module-student-template-combined@feature-data-builds
module:
  mounts:
    - source: content
      target: content
    - source: data
      target: data
    - source: repos/builder-course-PlvZSzcF2VNeXanE8IWQ/content
      target: content/courses/PlvZSzcF2VNeXanE8IWQ
    - source: repos/builder-course-PlvZSzcF2VNeXanE8IWQ/data
      target: data/PlvZSzcF2VNeXanE8IWQ
pluralizeListTitles: false
```
But the $.Site.Data returns the root of data inside of repos/builder-course-PlvZSzcF2VNeXanE8IWQ/data instead of an object with a property PlvZSzcF2VNeXanE8IWQ containing the data.
