### ISSUE TITLE
Provide a do not track option for Vimeo shortcode

### ISSUE THREAD

**Issue by Brixy** [gohugoio/hugo#7700]
```
Hugo version: v0.75.1
```

There is a do not track option for embedded vimeo videos: `dnt`. I tested it locally, and it works: No cookies are stored.

Does it make sense to have something like this?

```
privacy:
  vimeo:
    disable: false
    enableDNT: false
    simple: false
```

This is the regular iframe:

```
<iframe src="SOURCE" width="760" height="428"></iframe>
```

And this the do not track enhanced iframe:

```
<iframe src="SOURCE?dnt=1" width="760" height="428"></iframe>
```

Thank you!
