### ISSUE TITLE
Output format (AMP) .Site.Menus.main is not getting output as AMP format

### ISSUE THREAD

**Issue by blackb1rd** [gohugoio/hugo#7767]
### What version of Hugo are you using (`hugo version`)?

<pre>
v0.75.1
</pre>

### Does this issue reproduce with the latest release?
Yes.

## Reproduce method
With the config .Site.Menus.main:

```toml
     [menu]
 
       [[menu.main]]
         identifier = "about"
         name = "about hugo"
         pre = "<i class='fa fa-heart'></i>"
         url = "/about/"
         weight = -110
 
       [[menu.main]]
         name = "getting started"
         post = "<span class='alert'>New!</span>"
         pre = "<i class='fa fa-road'></i>"
         url = "/getting-started/"
         weight = -100
```

Checking AMP page with code below:

```html
<ul>
              {{ range .Site.Menus.main}}
              <li>
                <a href="{{ .URL | relLangURL }}"> {{ .Name }}</a>
              </li>
              {{ end }}
</ul>
```

## Expected Behavior

http://localhost:1313/about/
http://localhost:1313/getting-started/

## Actual Behavior

http://localhost:1313/amp/about/
http://localhost:1313/amp/getting-started/

## Other scenario by adding "amptest" at href 

```html
<ul>
              {{ range .Site.Menus.main}}
              <li>
                <a href="amptest{{ .URL | relLangURL }}"> {{ .Name }}</a>
              </li>
              {{ end }}
</ul>
```
## Actual Behavior

http://localhost:1313/amp/amptest/about/
http://localhost:1313/amp/amptest/getting-started/
