### ISSUE TITLE
Add cascade._target (slice)

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7782]
A common request is to be able to turn off rendering of section pages for a given section, but not all of them. This is currently almost impossible (at least not in a simple way).

What I suggest is to add a discriminator to `cascade`, so you can selectively add apply them to a subset of the pages.

```yaml
cascade:
  _forKinds: "**"
    _build:
      render: true
      list: always
      publishResources: false
```

/cc @regisphilibert

**Comment by regisphilibert** [comment]
> A common request

I did not know. Sections in my world often have their own `_index.md` from which I can manage `_build` but again... My world is limited.

Can I enquire how the `_forKind` selector works?

I will add a suggestion which might make you cringe depending on how far it is from your original design, but providing the `**` referenced in your example is indeed a glob syntax, why not:

1. Make cascade take slices of maps as well a map
2. Add a `_target` key to any slice so user can apply cascade using glob

ex:
```yaml
cascade:
  - _target: /california/*
     background: `yosemite.jpg`
  - _target: /california/sf/*
     background: `goldenbridge.jpg`
```

If this solves the problem at hand, it also adds more power to cascade without having to create too many `_index.md` down the tree...
