### ISSUE TITLE
Make build.render a enum

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7783]
This is the current setup:

```
_build:
  render: true
  list: always
  publishResources: true
```

If you set `render=false` it will not be printed to disk and `Page.Permalink` will be empty.

There are, however, situations where you need a URL, but not the file (in SPA situation with URL rewrite).
