### ISSUE TITLE
Blackfriday config for nofollowLinks/noreferrerLinks not works any more

### ISSUE THREAD

**Issue by lazidoca** [gohugoio/hugo#7785]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
0.75.1
</pre>

### Does this issue reproduce with the latest release?
Yes

It seems like the configuration for nofollowLinks/noreferrerLinks doesn't work any more. I didn't test other blackfriday configurations so I am not sure if others still work. I downloaded hugo v0.58.1 and test with the same configuration. Version v0.58.1 works just fine which adds `rel="nofollow noreferrer"` to the `a` tag.

My configuration:

```toml
[blackfriday]
fractions = false
noreferrerLinks = true
hrefTargetBlank = true
nofollowLinks = true

[markup]
[markup.blackFriday]
hrefTargetBlank = true
nofollowLinks = true
noreferrerLinks = true
```
