### ISSUE TITLE
Expand the i18n API to support PluralCount

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7791]
go-i18n has now added `PluralCount` to their API which Hugo uses in a backward compatible way (e.g. if the user passes in a number, e.g. `.WordCount`.)

If would, however, be nice if the user could pass in more complex objects and indicate plural some other way, e.g.:

```
{{ i18n "hello" $page $pluralCount }}
```

Or something ...

**Comment by jmooring** [comment]
I think this was resolved with https://github.com/gohugoio/hugo/pull/8456.

You can now do this:

layouts/_default/single.html

```html
{{ $details := dict
  "color" "black"
  "demeanor" "spiteful"
}}
{{ T "cat" (dict "count" 2 "details" $details) }}
```

i18n/en.toml

```toml
[cat]
one = "I have {{ .count }} cat. It is {{ .details.color }} and {{ .details.demeanor }}."
other = "I have {{ .count }} cats. They are {{ .details.color }} and {{ .details.demeanor }}."

```

Rendering:

```
I have 2 cats. They are black and spiteful.
```
