### ISSUE TITLE
Multilingual, multihost site with relativeURLs enabled has broken links when viewing without a server 

### ISSUE THREAD

**Issue by ahtremblay** [gohugoio/hugo#7805]
### What version of Hugo are you using?

(`v0.76.3`)

### Does this issue reproduce with the latest release?

yes

### Problem

When used in conjunction with multilingual features, relativeURLs seems to rewrite to the parent folder of the file, instead of where the file actually is - thus producing a 404 error on every URL

### Details

My config file is:

```
languages:
  en-us:
    baseURL: https://example.com
    languageName: English (United States)
    title: Example US
  fr-fr:
    baseURL: https://example.fr
    languageName: Français (France)
    title: Example FR
defaultContentLanguage: en-us
defaultContentLanguageInSubdir: true
relativeURLs: true
```

When I run hugo, it creates these folders:

<pre>
public
- en-us
   - css
- fr-fr
   - css
</pre>

However, the relativeURLs:true flag rewrites the urls using public/ as the root and not the corresponding language folders. For instance, a template such as

```
<html>
<link href="/css/test.css">
</html>
```

will be rewriten, for a file in `en-us`, to:

```
<html>
<link href="../css/test.css">
</html>
```

but the file is in `<link href="css/test.css">`. So none of the relativeUrls work! Finally, when adding defaultContentLanguageInSubdir=true even the default language has broken relative urls.
