### ISSUE TITLE
Multilingual bug: Hugo does not preserve capitalization of multilingual codes and hreflang

### ISSUE THREAD

**Issue by ahtremblay** [gohugoio/hugo#7808]
### What version of Hugo are you using?

(v0.76.3)

### Does this issue reproduce with the latest release?

yes

### Problem

The hrefland code is language dash country code where the country code is in upper case. For instances `en-CA` or `en-GB` or `fr-FR`.

My config file is:

```
languages:
  en-US:
    languageName: English (United States)
  fr-FR:
    languageName: Français (France)
```

But the directory structure produced is lowered to small caps `en-us` and `fr-fr` respectively. The sitemap.xml file also are lowered to small caps:

```
  <url>
    <xhtml:link
                rel="alternate"
                hreflang="fr-fr"
                href="https://example.fr/"
                />
    <xhtml:link
                rel="alternate"
                hreflang="en-us"
                href="https://example.com/"
                />
  </url>
```

and so-on.

**Comment by IngCr3at1on** [comment]
Looking for something to contribute to (I miss working on open source lol) I'm sure this is a relatively easy fix but I'm curious; does this behavior break anything (a fix almost certainly would partial compat breaks)?

**Comment by ahtremblay** [comment]
It at least breaks a config file such as this:

```
languages:
  en-US:
    languageName: English (United States)
defaultContentLanguage: en-US
```

this outputs `site config value "en-US" for defaultContentLanguage does not match any language definition` for `hugo`

whereas this works just fine:

```
languages:
  en-us:
    languageName: English (United States)
defaultContentLanguage: en-us
```

and second, it violates the hreflang specifications that Google uses for SEO and country identification. Google is probably smart enough to realize that `en-us` means `en-US`, but, as far as I know, it's not documented.

**Comment by IngCr3at1on** [comment]
I did a tiny bit of research cause I was curious (I don't normally deal with such things):

It would appear moz.com disagrees with your assessment, https://moz.com/learn/seo/hreflang-tag though frankly, I have no idea how reliable a source that is.

Taking a bunch closer look at the HTML RFCs for Language Tags, specifically rfc5646 it appears that you're correct WRT language tags of the form `Language-Region` but the topic is muddled a bit when you look at other forms of language tags, those of type `Language-Variant` for example.

https://tools.ietf.org/html/rfc5646#appendix-A

----

Hard for me to say (especially as a complete outsider to the project only looking for something to do) whether a change here is warranted or not but I would say a discussion is likely needed.

**Comment by ahtremblay** [comment]
At the end of the day, I would say what matters is how Google sees it because its Google that brings in the dough. Here they state: https://support.google.com/webmasters/answer/189077?hl=en

> Supported language/region codes
> The value of the hreflang attribute identifies the language (in ISO 639-1 format) and optionally a region (in ISO 3166-1 Alpha 2 format) of an alternate URL. (The language need not be related to the region.) For example:

So looing at ISO 3166-1 Alpha 2 format, we get https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

They are all upper case.

**Comment by pamubay** [comment]
for correct capitalization (for `hreflang` attribute)  you can manually set the `languageCode`.
```
languages:
  en-US:
   languageName: English (United States)
   languageCode: en-US
  fr-FR:
    languageName: Français (France)
    languageCode: fr-FR
```

and access it via `.Site.LanguageCode`

**Comment by ahtremblay** [comment]
> for correct capitalization (for `hreflang` attribute) you can manually set the `languageCode`.
> 
> ```
> languages:
>   en-US:
>    languageName: English (United States)
>    languageCode: en-US
>   fr-FR:
>     languageName: Français (France)
>     languageCode: fr-FR
> ```
> 
> and access it via `.Site.LanguageCode`

The following `config.yaml`:


```
languages:
  en-US:
    languageName: English (United States)
    languageCode: en-US
  fr-FR:
    languageName: Français (France)
    languageCode: en-FR
defaultContentLanguage: en-US
defaultContentLanguageInSubdir: true
```
causes `hugo` to fail with `Error: site config value "en-US" for defaultContentLanguage does not match any language definition`
