### ISSUE TITLE
Multilingual bug: having _index.md and _index.en-us.md causes hugo to silently ignore all content for certain valid config.yaml

### ISSUE THREAD

**Issue by ahtremblay** [gohugoio/hugo#7810]
### What version of Hugo are you using?

(v0.76.3)

### Does this issue reproduce with the latest release?

yes

### problem

If I define multiple content files with language codes for example:

```
_index.md
_index.en-ca.md
_index.fr-fr.md
```

then if my `config.yaml` does not list all of these languages, `hugo` compiles 0 pages or assets.

For instance, if my `config.yaml` is

```
languages:
  en-us:
    languageName: English
defaultContentLanguage: en-us
```

Then the output is:

<pre>
                   | EN-US  
-------------------+--------
  Pages            |     0  
  Paginator pages  |     0  
  Non-page files   |     0  
  Static files     |     0  
  Processed images |     0  
  Aliases          |     0  
  Sitemaps         |     1  
  Cleaned          |     0  
</pre>

### work-around

Either Deleting `_index.en-ca.md` and `_index.fr-fr.md`, or adding the language references in `config.yaml` resolves the issue. For instance:

```
languages:
  en-us:
    languageName: English (United States)
  en-ca:
    languageName: English (Canada)
  fr-fr:
    languageName: Français
defaultContentLanguage: en-us
```

will compile:

<pre>
                   | EN  
-------------------+-----
  Pages            |  3
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     |  0  
  Processed images |  0  
  Aliases          |  0  
  Sitemaps         |  1  
  Cleaned          |  0 
</pre>

However, I might want to change my language listings without having to delete all of my translations. this bug prevents this.
