### ISSUE TITLE
Add module.replacements

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#7904]
I've been scratching my head with a problem long enough now to understand that this warrants a better solution.

In Hugo Modules we can use Go Modules' `replace` directive inside `go.mod` to temporarily redirect a path to a module to point to a local folder, very useful for local development.

There are, however, several problems with this approach:

* You need to remember to remove that directive once done editing (there is no way to set this via configuration).
* If you do this in a vendored project you 1) Must also remember to turn off vendoring for that path (ignoreVendorPaths)) and 2) You would need Go installed to resolve the dependencies, which also can have some issues with private repos, esp. on CI hosts.

There are probably more, but the 2 above are the most important ones.

So, I suggest that we add a new `replacements` config directive:

```toml
[module]
# replacements is a comma separated list (alternatively a slice) of replacement directives 
replacements = "github.com/mod1 => ../mod1,github.com/mod2 => ../mod2"
```

* The syntax matches the one used in `go.mod`
* The semantics is a little different; a replaced path would be the same as setting `imports.path` to that new value, making it a local Theme Component like the components stored in `/theme`.
* The replacement can of course target an import from a nested module.

The prime motivation with the above is to ease development, but also to allow configuring preview versions of themes without to much mockery. In both situations you would do this via the environment:

```
HUGO_MODULE_REPLACEMENTS=""github.com/mod1 => ../mod1,github.com/mod2 => ../mod2" hugo
```
