### ISSUE TITLE
CSS minification removes whitespace in calc function

### ISSUE THREAD

**Issue by urbantrout** [gohugoio/hugo#7971]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.78.2/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

Hugo Pipeline `minify` is too aggressive when it comes to removing whitespaces. 

Inside the calc funciton `+` and `-` need to be surrounded by a whitespace, otherwise the function does not work. See https://css-tricks.com/a-complete-guide-to-calc-in-css/

**Comment by pamubay** [comment]
weird, can't reproduce this.

i tried both `minify` for resources pipes and via `--minify`. both produces whitespace around the operator `+`/`-`

do you have any example to reproduce this?

**Comment by urbantrout** [comment]
Could you try it in combination with custom properties. E.g.:

```css
background-color: hsl(calc(var(--hue) + 160), 85%, 39%);
```

**Comment by pamubay** [comment]
Still can't reproduce this.

## Test 1
```
resources.Get "style.scss" | toCSS | minify
```
1. Run `hugo`  :heavy_check_mark:  [PASS]
2. Run `hugo --minify`  :heavy_check_mark:  [PASS]
3. Run (1) and (2) with `--gc` :heavy_check_mark:  [PASS]

## Test 2

```
resources.Get "style.scss" | toCSS (dict "outputStyle" "compressed") | minify
```

1. Run `hugo`  :heavy_check_mark:  [PASS]
2. Run `hugo --minify`  :heavy_check_mark:  [PASS]
3. Run (1) and (2) with `--gc` :heavy_check_mark:  [PASS]

Version:
```
Hugo Static Site Generator v0.79.0-DEV-8F5C9A74/extended linux/amd64 BuildDate: 2020-11-23T08:42:54+0700
```

There is no `tdewolff/minify` upgrade since hugo `0.78.2` release until current `master(8F5C9A74)`, so it's same `minify` package.

**Comment by urbantrout** [comment]
Thanks for your quick replies!

Here is my detailled setup:

- Hugo 0.78.2

## package.json
```json
{
  "scripts": {
    "dev": "hugo server --watch",
    "build": "NODE_ENV=production hugo --cleanDestinationDir --minify"
  },
  "dependencies": {
    "autoprefixer": "^10.0.2",
    "postcss": "^8.1.7",
    "tailwindcss": "^2.0.1"
  }
}
```
## Template
```html
{{ $style := resources.Get "css/main.css" | resources.PostCSS (dict "noMap" true) | minify }}
<link rel="stylesheet" href="{{ $style.RelPermalink }}">
```

## main.css
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.bg {
  background: linear-gradient(
    45deg,
    hsl(calc(0 + 40), 75%, 50%),
    hsl(calc(180 + 40), 75%, 50%)
  );
}
```

## postcss.config.js
```js
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}
```

## Output
### Expected:
```css
.bg {
 background: linear-gradient( 45deg,hsl(calc(0 + 40),75%,50%),hsl(calc(180 + 40),75%,50%) );
}
```
### Actual:
```css
.bg {
 background: linear-gradient( 45deg,hsl(calc(0+40),75%,50%),hsl(calc(180+40),75%,50%) );
}
```

**Comment by davidsneighbour** [comment]
Your problem could be a different one: 0+40 means an octal number and that might be why calc fails, because it trusts you ;) Try 0.0+40 and it might work. Why is there a 0 anyway and not just a 40?

**Comment by urbantrout** [comment]
But 180 + 40 in the second color step is also not working. I just used 0 as an example. You could replace it with any value including CSS custom properties.

**Comment by urbantrout** [comment]
Float numbers do not solve the issue for me.

**Comment by davidsneighbour** [comment]
yep, the reference says that operators MUST be surrounded by whitespace (because if they aren't the +/- is understood as part of the number behind it). 
https://developer.mozilla.org/en-US/docs/Web/CSS/calc()

**Comment by urbantrout** [comment]
Yes, I know that. I put whitespaces before and after the plus sign as seen in `main.css` above. But `minify` removes them.

**Comment by pamubay** [comment]
I don't test it with `PostCSS`, but this test produces correct result.

## Test 1

```css
// assets/test.css 
.bg {
  background: linear-gradient(
    45deg,
    hsl(calc(0 + 40), 75%, 50%),
    hsl(calc(180 + 40), 75%, 50%)
  );
}
```

Template:
```
{{- $testCSS := resources.Get "test.css" | minify -}}
 <link rel="stylesheet" href="{{ $testCSS.RelPermalink }}?{{ now.Unix }}">
```

1. Run `hugo --minify` :heavy_check_mark: 
2. Run `hugo --minify --gc`  :heavy_check_mark: 

output:
```
.bg{background:linear-gradient( 45deg,hsl(calc(0 + 40),75%,50%),hsl(calc(180 + 40),75%,50%) )}
```
