### ISSUE TITLE
related content not showing when I copy the default related config

### ISSUE THREAD

**Issue by DanielRuf** [gohugoio/hugo#8002]
When I add the following to my config.toml file, the related article disappears:

https://gohugo.io/content-management/related/#configure-related-content

```toml
[related]
  includeNewer = false
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "keywords"
    weight = 100

  [[related.indices]]
    name = "date"
    weight = 10
```

Is this a known issue? What is the correct default config when I run `hugo server -D`?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown
</pre>
