### ISSUE TITLE
bundle resource is copied to wrong directory when Multilingual Mode and Custom output format

### ISSUE THREAD

**Issue by blackb1rd** [gohugoio/hugo#8021]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo master branch
</pre>

### Does this issue reproduce with the latest release?
Yes.

There a image in content folder name `cat-behaviour.jpg` -> `content/cat-behaviour.jpg`

Expected output:

```
public/htmlcontent/cat-behaviour.jpg
public/th/htmlcontent/cat-behaviour.jpg
```

Acual output

```
public/htmlcontent/cat-behaviour.jpg
```

the `public/th/htmlcontent/cat-behaviour.jpg` is not exist and it seems not copied.

Reppsitory for reproduce:
https://github.com/blackb1rd/hugo-71

Config file
```toml
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"

[outputFormats]
  [outputFormats.HTMLCONTENT]
  mediaType = "text/html"
  baseName = 'htmlcontent'
  path = "htmlcontent"
  isPlainText = false
  isHTML = true

[outputs]
home = [ "HTML", "RSS", "JSON", "HTMLCONTENT"]
page = [ "HTML", "HTMLCONTENT"]
section = ["HTML", "RSS", "HTMLCONTENT"]

[languages]
  [languages.en]
    languageName = "English"
    title = "In English"
    weight = 2
  [languages.th]
    languageName = "ไทย"
    title = "th ไทย"
    weight = 1
```
