### ISSUE TITLE
Cascade Parameters set in _index.md cannot be overwritten / added to in children Pages

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/hugo#8053]
As described in [this](https://discourse.gohugo.io/t/cascade-parameters-set-in-index-md-cannot-be-overwritten-in-children-pages/29939) forum topic -and confirmed by me- Cascade parameter keys set in the `_index.md` of a Section or Nested Section cannot be overwritten in the frontmatter of children pages.

Content tree:

```
/content
	/book-1
		_index.md
		/part-1
			_index.md
			/chapter-1
				featured.jpg
				index.md
```

Cascade parameters set in `content/book-1/_index.md`

```
cascade:
    authors: John Smith
    layout: book
    book:
        title: Example Title
        publisher: Example Publisher
        publish_date: 2020-01-01
```

If a user tries to add an extra parameters in `chapter-1/index.md` under the book: key, only the new parameters show up, replacing what was set above.

For example if a user adds the following in `chapter-1/index.md` 

```
book:
    part: 1
    chapter: 1
```

Then all key value pairs under `book:` set in `content/book-1/_index.md` are removed and only what entered in the child page `chapter-1/index.md`  is returned.

I think that Hugo should allow overwriting / adding to the keys of cascaded frontmatter.
