### ISSUE TITLE
Documentation:  How to Deploy Hugo as a GitHub Pages using GitHub Action Workflow

### ISSUE THREAD

**Issue by gagarine** [gohugoio/hugo#8204]
The doc page [Deploy Hugo as a GitHub Pages](https://gohugo.io/hosting-and-deployment/hosting-on-github/ ) use a local bash script. It would be certainly much easier in a lot of case to use [Github Action Workflow](https://github.com/features/actions)

Their is several way to do this. But one simple way was featured on the GitHub blog: https://github.blog/2020-03-22-github-action-hero-shohei-ueda/ . The actions: https://github.com/marketplace/actions/github-pages-action

That would be a great addition to the documentation. Eventually Hugo could provide an "official" action too.

**Comment by adityatelange** [comment]
The following actions script should work fine

using https://github.com/peaceiris/actions-hugo and https://github.com/peaceiris/actions-gh-pages

```yml
name: Build GH-Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # manual run

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

        # when using theme as submodule
      - name: Get Theme
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --gc --verbose --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
```
