### ISSUE TITLE
Absolute URLs in menu.toml generated incorrectly

### ISSUE THREAD

**Issue by Shatur95** [gohugoio/hugo#8231]
## Description

The following menu (with absolute url) works as expected with `hugo server`

```toml
[[main_right]]
  pre = "<i class=\"fab fa-github-alt\"></i> "
  name = "GitHub"
  url = "https://github.com/crow-translate"
  weight = 20
```

But if I run `hugo` command, the generated website has a wrong link: `https://crow-translate.github.io/ru/https:/github.com/crow-translate`

[Source code](https://github.com/crow-translate/website-source), [generated website](https://github.com/crow-translate/crow-translate.github.io).

## Environment

**Hugo:** 0.80.0
**OS:** Linux
