### ISSUE TITLE
'hugo new post' should infer frontmatter format from config.{toml,yaml,json}

### ISSUE THREAD

**Issue by legends2k** [gohugoio/hugo#8260]
Hugo Version: Hugo Static Site Generator v0.80.0/extended darwin/amd64 BuildDate: unknown
Does this issue reproduce with the latest release?  Yes

`hugo new posts/hello.md` defaults to YAML frontmatter for the newly created markdown file.  It should've chosen TOML as frontmatter format inferring it from the `config.toml` in repo `/`.

Related: #5241
I don't agree with [rationale behind closing this](https://github.com/gohugoio/hugo/issues/5241#issuecomment-423469803) i.e. GitHub understands YAML so `hugo new` defaults to YAML.  I could be hosting the site anywhere, doesn't matter what GitHub does.  The tool shouldn't know/care about meta stuff like where the pages are hosted.

**Comment by legends2k** [comment]
Doing `hugo new post/hello.md --config config.toml` generates a file with the expected TOML front matter

**Comment by davidsneighbour** [comment]
What format are your archetype files? THAT is the format used.

**Comment by legends2k** [comment]
@davidsneighbour `archetypes/default.md` reads

``` toml
+++
title = "{{ humanize .TranslationBaseName | title }}"
description = ""
date = {{ .Date }}
tags = []
draft = true
+++
```
