### ISSUE TITLE
add site.GetPages, .GetPages

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8273]
## Current status
This is very common for a Front Matter fields to hold a list of file paths to content files in order to establish a one to many relationships between pages or settings.

Currently one has to define its own solution using `range` and `site.GetPage` and append it to a `slice`. This might not be very efficient when dealing with hundreds of pages.

## Solution
If easily implemented and more efficient than the user defined solution Hugo could sport its own methods to retrieve a collection based on a slice of file paths with `site.GetPages` and `.Page.GetPages`.

## Example

```yaml
title: Famous blog post
related_posts:
- great-article.md
- another-good-idea.md
- keep-going.md
related_pages:
- /product/reminder.md
- /contact.md
```

```
{{ with .Params.related_posts }}
  {{ with $.Parent.GetPages . }}
    <h3> Related Posts </h3>
    {{ range . }}
    <a href="{{ .RelPermalink" }}>{{ .Title }}</a>
    {{ end }}
  {{ end }}
{{ end }}

{{ with $.Params.related_pages }}
  {{ with site.GetPages . }}
    <h3> See also </h3>
    {{ range . }}
    <a href="{{ .RelPermalink" }}>{{ .Title }}</a>
    {{ end }}
  {{ end }}
{{ end }}
```
