### ISSUE TITLE
Support 200.html

### ISSUE THREAD

**Issue by ngdangtu-vn** [gohugoio/hugo#8274]
Surge support `200.html` for various purposes. And I think it would be nice if Hugo could add this page too. It would be more convenient for me than create a dummy content and use `_default/single.html`. And that trick doesn't work well if I have a blog that need page content. Using `200.html` as static is also out of the question because my `200.html` needs data generated from Hugo.

(It would be even cooler if we could have custom Page Kind. But that seems expensive so I'll just request for 200.html)

**Comment by faraixyz** [comment]
> (It would be even cooler if we could have custom Page Kind. But that seems expensive so I'll just request for 200.html)

Try adding [custom output format](https://gohugo.io/templates/output-formats#readout).

**Comment by ngdangtu-vn** [comment]
> > (It would be even cooler if we could have custom Page Kind. But that seems expensive so I'll just request for 200.html)
> 
> Try adding [custom output format](https://gohugo.io/templates/output-formats#readout).

Because I couldn't do that so I have come here ask for this feature. Anyway, - how did you do that to archive page `200.html`. The custom format doesn't receive new kind of template. Which means Hugo will output `200.html` from an `index.html`, not from `200.html`.

**Comment by faraixyz** [comment]
The documentation for that is prtety bad, but it would do what you're looking for.

```yaml
output:
    home: ["HTML", "RSS", "200"]

mediaTypes:
    text/200.html:
        suffixes: [".html"]

outputFormats:
    200:
        mediaType: text/200.html
        baseName: 200
        isHTML: true
        permalinkable: false
```

You can then create a 200.html inside the layouts folder.

**Comment by ngdangtu-vn** [comment]
It didn't work. I put `200.html` template file in layouts but got nothing.
Do you have a sample repo that actually works?

**Comment by ngdangtu-vn** [comment]
@faraixyz 
I tested it again with a completely clean project, [`200.zip`](https://github.com/gohugoio/hugo/files/6044003/200.zip). But nothing seems work. It only use your config, (and I disable a certain useless kinds to but nothing changed.). This is not the way and we need `200.html` support.

(If you think your way is the right way, please share your code that works so I can learn what did I do wrong.)

**Comment by faraixyz** [comment]
Ok, I've figured it out now.

```yaml
outputs:
  home: ["HTML", "RSS", "200"]

outputFormats:
  200:
    mediaType: text/html
    baseName: 200
    isHTML: true
    permalinkable: true
```

Then your template should be named `index.200.html`.
