### ISSUE TITLE
allow languagePrefix to be defined via config

### ISSUE THREAD

**Issue by fnordfish** [gohugoio/hugo#8279]
In my multilingual project, I'd like to be able to have more control over the generated URLs.
I'd like to be able to define which`languagePrefix` is used, instead of the language key.

As an example:
`http://base/en/some-post` -> `http://base/questions/some-post`
`http://base/de/some-post` -> `http://base/fragen/some-post`

I've tried to just use those translations as keys in the translations config, which produced the right document structure, but broke i18n, because the keys are no longer language codes.
I've also tired to just use hard-code the entire `url` as page params, which also worked for pages, but had no effect on the home page.

https://github.com/gohugoio/hugo/blob/04b89857e104ac7dcbf9fc65d8d4f1a1178123e6/hugolib/site.go#L1294-L1297

Instead of using `lang.Lang`, we could extend `Language` with a `LanguagePrefix`, which could default to `Lang`?

```yaml
languages:
  de:
    languageName: Deutsch
    languagePrefix: "/fragen" # << purposed new config key
  en:
    languageName: English
    languagePrefix: "/questions"  # << purposed new config key
```

**Comment by davidsneighbour** [comment]
```
# config.yaml
defaultContentLanguageInSubdir: true

languages:
  fragen:
	languageName: Deutsch
  questions:
	languageName: English
```

Should do that. I could also think of a way where you use `slug` in the front matter of your list-files, but I don't know your content structure, so this might fail.

I can't find the place where it's written, but the language slug can be anything and is not covered by rules, you just need to be careful where you define language related things so that you are using fragen/questions instead of de/en.
