### ISSUE TITLE
SASS/SCSS default behavior for encoding data uri changed without notice

### ISSUE THREAD

**Issue by johannesgiani** [gohugoio/hugo#8354]
Given the following inline/data uri SVG:
```scss
.svg-input {
  background-image: url('data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 4.248c-3.148-5.402-12-3.825-12 2.944 0 4.661 5.571 9.427 12 15.808 6.43-6.381 12-11.147 12-15.808 0-6.792-8.875-8.306-12-2.944z" id="path"/><clipPath id="clip"><use href="#shape"/></clipPath></svg>');
}
```

in 0.80 this gets automatically base64 encoded when processing with `resources.Get "/style.scss" | resources.ToCSS | resources.Minify | resources.Fingerprint }}`:

```scss
.svg-input{
  background-image:url(data:image/svg+xml;charset=UTF-8;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgdmlld0JveD0iMCAwIDI0IDI0Ij48cGF0aCBkPSJNMTIgNC4yNDhjLTMuMTQ4LTUuNDAyLTEyLTMuODI1LTEyIDIuOTQ0QzAgMTEuODUzIDUuNTcxIDE2LjYxOSAxMiAyM2M2LjQzLTYuMzgxIDEyLTExLjE0NyAxMi0xNS44MDguMC02Ljc5Mi04Ljg3NS04LjMwNi0xMi0yLjk0NHoiIGlkPSJwYXRoIi8+PGNsaXBQYXRoIGlkPSJjbGlwIj48dXNlIGhyZWY9IiNzaGFwZSIvPjwvY2xpcFBhdGg+PC9zdmc+);
}


```

while in 0.81+ there is no encoding:
```scss
svg-input{
  background-image:url('data:image/svg+xml;charset=UTF-8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 4.248c-3.148-5.402-12-3.825-12 2.944 0 4.661 5.571 9.427 12 15.808 6.43-6.381 12-11.147 12-15.808 0-6.792-8.875-8.306-12-2.944z" id="path"/><clipPath id="clip"><use href="#shape"/></clipPath></svg>');
}

```

Would be cool to document the default behavior somewhere and to make base64 encoding configurable. In my case the base64 encoding was just there and after updating my SVG broke.

### What version of Hugo are you using (`hugo version`)?

hugo v0.82.0+extended darwin/amd64 BuildDate=unknown

libsass

### Does this issue reproduce with the latest release?

yes
