### ISSUE TITLE
Build Options in front matter may not work in some cases

### ISSUE THREAD

**Issue by Kzer-Za** [gohugoio/hugo#8477]
<pre>
hugo v0.82.0+extended linux/amd64 BuildDate=unknown

</pre>

I am making a multilingual site with these site-wide options:

```yaml
baseURL: /
disableKinds: ["taxonomy", "term"]
permalinks:
  posts: /:filename/

defaultContentLanguageInSubdir: true
languages:
  en:
    title: English title
    weight: 1
  ru:
    title: Русское название
    weight: 2

```

I want posts as separate entities to be published, but unavailable as a list, so in `content/posts` I created `_index.md` that contains only this:

```yaml
---
_build:
  list: never
  render: never
---
```

However, when I generate the site, the Russian version of the site still contains `posts` directory with `index.html` that lists all the posts. The English version does not contain it, but the Russian version does. Let's say I create 4 files in `content/posts` in addition to _index.md:

`a.en.md  a.ru.md  b.en.md  b.ru.md  _index.md`

Then the content of `public/en/` is:

`404.html  a  b	index.html  index.xml  sitemap.xml`

But the content of `public/ru/` is:

`404.html  a  b	index.html  index.xml  posts  sitemap.xml`

Notice the presence of `posts`.
