### ISSUE TITLE
Syntax Highlighting of Yaml-code

### ISSUE THREAD

**Issue by VladyslavBondarenko** [gohugoio/hugo#8545]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.83.1+extended darwin/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
yes, v0.83.1.

### Issue: 
A single line after a pipe in Yaml is styled wrongly.

```yaml
scripts:
  singleLineScript: |
    npm install
  multipleLineScript: |
    npm install
    npm start
```

results into 
![image](https://user-images.githubusercontent.com/17024977/118793047-e61efa00-b8a0-11eb-9280-842aa2cfb9d9.png)

Note the indentation and font color of the first `npm install`. Multiple lines are highlighted correctly.
