### ISSUE TITLE
Error when mounting file to data directory

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8556]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo v0.83.1-5AFE0A57+extended darwin/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes

### The problem

When trying to use file mounts on the data directory...
```yaml
module:
  mounts:
  - source: data
    target: data
  - source: netlify.toml
    target: data/netlify.toml
```

 Hugo produces the following error:
```
Error: add site dependencies: create deps: create PathSpec: build filesystems: this fs supports directories only
```
This would be tremendously helpful, as user could inspect from hugo's site.Data, package.json, netlify.toml, `.forestry/config.yaml` and many other repo's root config files.

PS: I seem to recall threads mentioning that the problem/limitation was known but I could not find any existing GH issue.
