### ISSUE TITLE
Allow smarter merging of config (esp. params) from themes

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8633]
This has been discussed before, but I'm creating a brand new issue.

Given the below theme configuration:

```toml
[params]
[params.colours]
blue="#337DFF"
green="#68FF33"
red="#FF3358"
```

If I would like to use the above theme, but I want a different shade of red, I currently need to copy the entire block, even the colours I'm totally happy with. This is painful even in the simplest setup.

I'm currently doing a spring cleaning now in the config area, and I need to simplify this logic, so I might as well take on this important problem.

What I'm suggesting is that we introduce an implicit new `_merge` keyword which tells Hugo which _merge strategy_ to use: One of `none`, `shallow` and `deep`.

The current strategy when merging config from a theme, using `params` as the example, is `shallow`: That is, we only add params options with new keys.

My current take on it is that we change the default for `params` only to `deep` (which is what the theme authors wants). This would be a potentially breaking change, so we'll allow people to set this strategy on any node in the configuration:

```toml
[params]
_merge = "shallow"
[params.colours]
blue="#337DFF"
green="#68FF33"
red="#FF3358"
```

**Comment by bep** [comment]
This is now the default setup:

```yaml
build:
  _merge: none
caches:
  _merge: none
frontmatter:
  _merge: none
imaging:
  _merge: none
languages:
  _merge: none
  en:
    _merge: none
    menus:
      _merge: shallow
    params:
      _merge: deep
markup:
  _merge: none
mediatypes:
  _merge: shallow
menus:
  _merge: shallow
minify:
  _merge: none
module:
  _merge: none
outputformats:
  _merge: shallow
permalinks:
  _merge: none
related:
  _merge: none
sitemap:
  _merge: none
taxonomies:
  _merge: none
```
