### ISSUE TITLE
Custom menus not working after upgrading to v0.84

### ISSUE THREAD

**Issue by anthonynelzin** [gohugoio/hugo#8672]
My custom menus broke after upgrading to Hugo v0.84. They’ve been working fine for years, I didn’t change a thing in my config:

```
menu:
    header:
        - identifier: "À propos"
          name: "À propos"
          url: /a-propos/
          weight: 1
        - identifier: "Commencez ici"
          name: "Commencez ici"
          url: /commencez-ici/
          weight: 2
        - identifier: "Défileur"
          name: "Défileur"
          url: /defileur/
          weight: 3
        - identifier: "Guide orthotypographique"
          name: "Orthotypo"
          url: /guide-orthotypographique/
          weight: 4
        - identifier: "Mentions légales"
          name: "Mentions légales"
          url: /mentions-legales/
          weight: 5
        - identifier: "RSS"
          name: "RSS"
          url: /index.xml
          weight: 6
```

Nor did I change a thing in my templates:

```
<div class="menu_pages">
	{{ range .Site.Menus.header }}
		<p><a href="{{ .URL }}">{{ .Name }}</a></p>
	{{ end }}
</div>
```

I know that v0.84 changed some things about the merging of params, but I don’t see how it could affect me. I tried to debug using `{{ printf "%#v" .Site.Menus.header }}`, but it simply returns nil. I’m at a loss of ideas.

### What version of Hugo are you using (`hugo version`)?

hugo v0.84.0+extended darwin/arm64

### Does this issue reproduce with the latest release?

Yes.

**Comment by anthonynelzin** [comment]
Content source here: https://github.com/anthonynelzin/metrozendodo.fr
Theme source here: https://github.com/anthonynelzin/metrozendodo

**Comment by bep** [comment]
Could you try to rename the config from `menu` to `menus`? We changed that long time ago; we did have a way to make it backwards compatible, but that may have broken in my "config rewrite".

**Comment by anthonynelzin** [comment]
Unfortunately, it looks like it doesn’t work.

**Comment by jmooring** [comment]
Confirmed.

With v0.83.1 this worked:

```toml
[languages.en]

[[menus.foo]]
name = "foo-a"
url = "/foo-a/"

[[menus.foo]]
name = "foo-b"
url = "/foo-b/"
```

With v0.84 you must do this instead:

```toml
[languages.en]

[[languages.en.menus.foo]]
name = "foo-a"
url = "/foo-a/"

[[languages.en.menus.foo]]
name = "foo-b"
url = "/foo-b/"
```






Minimal reproducible example:

```bash
git clone --single-branch -b hugo-github-issue-8672 https://github.com/jmooring/hugo-testing hugo-github-issue-8672
cd hugo-github-issue-8672
hugo server
```

If a `languages` key is present in the site configuration, none of te
