### ISSUE TITLE
`hugo mod npm pack` ignores `module.replacements` configuration

### ISSUE THREAD

**Issue by schnerring** [gohugoio/hugo#8711]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.84.2-E0C67958+extended windows/amd64 BuildDate=2021-06-28T10:59:21Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

-----

I currently build [a theme](https://github.com/schnerring/hugo-gruvbox) from scratch that includes an `exampleSite` that I use to develop the theme. I use `npm` to bundle `prismjs` which works fine. I also got `hugo mod npm pack` working to generate the `package.config` for my `exampleSite/`:

```toml
[module]
  replacements = "github.com/schnerring/hugo-gruvbox -> ../.."
  [[module.imports]]
    path = "github.com/schnerring/hugo-gruvbox"
```

I haven't investigated whether or not this behavior is intended but when specifiying the theme with `theme = ["github.com/schnerring/hugo-gruvbox"]` instead of using `[[module.imports]]`, the `replacements` functionality doesn't work.

The actual bug is that `hugo mod npm pack` doesn't care about the `replacements` part and skips to upstream. This also happens when explicitly using `replace` inside the `.mod` file. This means that one has to push changes upstream first to be able to generate the files with `hugo mod npm pack`.

This took me a while to figure it out since `replacements` with a local module worked, but `hugo mod npm pack` didn't.

**Comment by schnerring** [comment]
I'm not sure what the issue was but I got it working.

The only issue remaining is the part where `replacements` only works with `[[module.imports]]` but not with setting via `theme = [ ... ]`.

**Comment by bep** [comment]
> but not with setting via theme = [ ... ].

How can you set it there?

**Comment by schnerring** [comment]
You said both were equivalent (correct me if I'm wrong):

> This:
```toml
[module]
  [[module.imports]]
    path = "github.com/yihui/hugo-xmin"
  [[module.imports]]
    path = "github.com/yourname/my-shortcodes"
```
> Is the same as:
> 
```toml
theme = ["github.com/yihui/hugo-xmin",  "github.com/yourname/my-shortcodes" ]
```

Source: https://discourse.gohugo.io/t/how-to-add-a-theme-using-modules-for-beginners/20665/2
