### ISSUE TITLE
Create a new post in the other languages' directory

### ISSUE THREAD

**Issue by whatacold** [gohugoio/hugo#8768]
Hi,

I use the multilingual mode of Hugo, which has below language settings:
```toml
DefaultContentLanguage = "en"
hasCJKLanguage = true

[languages]
  [languages.en]
    contentDir = "content/en"
    weight = 1
  [languages.zh-cn]
    contentDir = "content/zh-cn"
    weight = 2
```

But it seems there is no way to create a new post in the `zh-cn` subdir.
For example, I tried to new a post by `hugo new -c zh-cn t1.org`, but it didn't work.

My Hugo version is v0.80.0, and the blog is at https://whatacold.io/
