### ISSUE TITLE
Notes release notes 0.86

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#8770]
* Minify
* Cascade

```toml
[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
```
