### ISSUE TITLE
Cascade _target.kind not accepting glob pattern

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8888]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.86.1-F6821B88+extended darwin/amd64 BuildDate=2021-07-30T10:13:35Z VendorInfo=gohugoio

</pre>

### Does this issue reproduce with the latest release?
Yes

Using the following `cascade` configuration: 

```
# content/_index.md
cascade:
- _target:
    path: /poetry/**
    lang: en
    kind: '{section,page}'
```

Hugo returns the following error:

``` 
Error: Error building site: ".../content/en/_index.md:1:1": "{section,page}" is not a valid Page Kind
```

As per doc:
> A Glob pattern matching the Page’s Kind(s), e.g. “{home,section}”.
