### ISSUE TITLE
time.Format - timezone details missing with time_full and time_long with TOML dates 

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#8895]
This issue title is... terrible.

content/tests/pass.md

```toml
+++
title = "Pass"
date = "2021-08-16T06:00:00-07:00"  # String
draft = false
+++
```

content/tests/fail.md

```toml
+++
title = "Fail"
date = 2021-08-16T06:00:00-07:00    # Date
draft = false
+++
```

||pass.md|fail.md
:--|:--|:--
`{{ .Date \| time.Format ":time_full" }}`|6:00:00 am Pacific Daylight Time|6:00:00 am
`{{ .Date \| time.Format ":time_long" }}`|6:00:00 am PDT|6:00:00 am
