### ISSUE TITLE
Add suffix selector to Output Formats

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8897]
## The problem

While this is possible and recommended to define any mediaType's extensions as an array of suffices, it is not currently possible to choose which suffix to use when generating a file from an output format.

To clarify, if I...
1. add the `rss` suffix to the built-in `application/rss+xml` media 
2. and use this media type on custom output format

```yaml
# 1
mediaTypes:
  application/rss+xml:
    suffixes:
    - xml
    - rss

# 2
outputFormats:
  rss_feed:
    mediaType: application/rss+xml
    baseName: feed
```

The `rss_feed` output format will generate a `feed.xml` file, using the first suffix. 

Even though several suffixes are declared on the media type, it is impossible to choose one when assigning it to an output format.

## The proposed solution (as suggested [here](https://discourse.gohugo.io/t/mediatypes-how-to-choose-which-suffix/34294/4?u=regis))

Adding a `suffix` key to the `outputFormat`.

**If set**, Hugo would use the given `suffix` when generating the file.
**If not set**, current behaviour prevails, it would use the first suffix.

```yaml
# 2
outputFormats:
  rss_feed:
    mediaType: application/rss+xml
    baseName: feed
    suffix: rss
```
Would generate `/feed.rss`
