### ISSUE TITLE
Make _merge into a slice and add the append keyword (for slices)

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8933]
Currently, for (now obvious to me) security reasons, a module cannot set up mounts configuration on the project level.

I think this would be to the benefit of the user, if modules could administer one project's mount system for say, put a directory at the root of the project which could be treated as part of `assets` that the module transform. 

Or a module dealing with media transformation could setup an `/media` directory at the root and mount it into `assets/media` to user `resources` or `content/media/` to use Page Resources etc...

Currently the module documentation would have to direct the user to copy/paste the mount settings and apply it themselves to their project which is not ideal.

```yaml
# config/_default/module.yaml
imports:
- path: github.com/mememe/that-media-module
  trustMount: true
```

We could use something like `enableMount` but I think using trust makes a stronger statement and pass on to the user the importance of this bool.

**Comment by schnerring** [comment]
I am developing a theme and the themes config contains the following:

```toml
[[mounts]]
  source = "assets"
  target = "assets"
[[mounts]]
  source = "layouts"
  target = "layouts"
[[mounts]]
  source = "static"
  target = "static"
[[mounts]]
  source = "node_modules/prismjs"
  target = "assets/prismjs"
[[mounts]]
  source = "node_modules/prism-themes/themes"
  target = "assets/prism-themes"
[[mounts]]
  source = "node_modules/typeface-fira-code/files"
  target = "static/fonts"
[[mounts]]
  source = "node_modules/typeface-roboto-slab/files"
  target = "static/fonts"
[[mounts]]
  source = "node_modules/@tabler/icons/icons"
  target = "assets/tabler-icons"
[[mounts]]
  source = "node_modules/simple-icons/icons"
  target = "assets/simple-icons"
```

As you can see, I mount a couple of npm dependencies.

I created a new example site which uses the theme like so:

```toml
[module]
  _merge = "deep"
  [[module.imports]]
    path = "github.com/schnerring/hugo-gruvbox"
```

This results in the site not being able to resolve resources from `node_modules`.

I have to copy and paste the module mounts from the theme to the site and then everything works as expected.

What's interesting is that if I use the module from the local file system via `replacements`, it works:

```toml
[module]
  replacements = "github.com/schnerring/hugo-gruvbox -> ../../hugo-gruvbox"
```

But the site actually goes looking for the files in `../../hugo-gruvbox/node_modules` instead of `./node_modules`. Is this intended? Because when running `hugo config`, the map looks the same in both scenarios and doesn't suggest that Hugo goes looking for files in the `replacements` directory.
