### ISSUE TITLE
Add includeFiles and excludeFiles to mount configuration

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9042]
We have the `ignoreFiles` option, but it only works for a sub-set of Hugo's source files (content, data?), and changing it to mean something else would create havoc.

Long story short, what would be relatively simple to implement and pretty powerful is to add a `filter` option to the mount config, e.g.:

```toml
[module]
[[module.mounts]]
source = 'content'
target = 'content'
includeFiles = ['blog/**', 'docs/**']
excludeFiles = '**.jpg'
```

Some notes about the above:

* The include/exclude patterns are the regular Glob we use in other places; much faster than regexp and easier for people to reason about when it comes to file paths. They should contain Unix slashes even if on Windows.
* We accept either a string or a slice for these options.
* Since this needs to work on all file operations (dir listing, `.Stat`, `.Open`), we need to do this on the file system level.

/cc @regisphilibert @jmooring etc.
