### ISSUE TITLE
Incorrect file permissions with hugo new

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9057]
hugo v0.89.0-DEV-096F5E19+extended linux/amd64 BuildDate=2021-10-18T09:08:01-0700

```toml
[languages.en]
weight = 1
contentDir = 'content/en'
[languages.de]
weight = 2
contentDir = 'content/de'
```

```bash
hugo new content/en/post/foo.md
ls -l content/en/post/
```

> -rwx--x--x 1 jmooring jmooring 69 Oct 18 09:38 foo.md

With v0.88.1:

> -rw------- 1 jmooring jmooring 69 Oct 18 09:41 foo.md

My umask/default permissions are configured such that all new files get 600 and all new directories get 711.
