### ISSUE TITLE
Localization: allow to match locale with an additional parameter instead of the language key.

### ISSUE THREAD

**Issue by razonyang** [gohugoio/hugo#9109]
Hugo supports localize time and dates since v0.87.0, but I'm stuck by specifying the language key that not defined in https://github.com/gohugoio/locales.

For example:

```toml
[zh_hans] # localization works as expected.
  languageName = "zh_hans"

[zh-cn]
  languageName = "zh-cn"
  locale = "zh_hans" # additional parameter to match the locale
 ```

- https://discourse.gohugo.io/t/is-it-possible-to-make-language-key-to-be-differenced-with-locale-name/35386
