### ISSUE TITLE
Regression with "hugo new" from a theme

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#9129]
See https://discourse.gohugo.io/t/can-you-use-markdown-files-for-default-content-in-a-theme/35447

**Comment by danielfdickinson** [comment]
FYI (in case it gives some clues to check with the listed issue) I'm working on a minimal reproducible test case for a related (but different) bug with ``hugo new``. For obvious reasons I suspect the archetype-related changes. I will create a bug report once I have the test case created. (Hugo in my case in running in WSL2, with VSCode running on Windows 10). The site is a Hugo module, but the theme is only available as a git submodule, and I am mounting other modules in order to import their README.md files as assets to use in pages on the site. The issue I have is related to having both the site's ``content -> content`` mount and one module that mounts ``content/docs -> content/some/other/dir/docs``.

**Comment by danielfdickinson** [comment]
## Preface

It turns out the case I have is the same bug. I now have a repo at <https://github.com/danielfdickinson/hugo-mounted-content-subdir-bug-0-89> for demonstrating the issue.

## Seeing the issue using the repository

1. ``git clone https://github.com/danielfdickinson/hugo-mounted-content-subdir-bug-0-89.git``
2. (Probably optional): ``hugo server``
3. See that the site is generated correctly by browsing to <http://localhost:1313/>
4. ``Ctrl-C``
5. ``hugo new post/a-new-post.md``
6. See:
   ```
   Error: mkdir /tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/danielfdickinson/netlify-new-oldnew-mashup/example!site@v0.0.0-20211013045709-e4253b573e12/content/docs/post/: permission denied
   ```
7. ``hugo mod vendor``
8. ``hugo new post/another-new-post.md``
9. See:
   ```
   panic: [BUG] no Page found for "/home/daniel/webdev/debug/verify-steps-content-subdir-bug/_vendor/github.com/danielfdickinson/netlify-new-oldnew-mashup/exampleSite/content/docs/post/another-new-post.md"
   
   goroutine 1 [running]:
   github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0xc00047c180, {0xc000812e70, 0xa9}, {0xc0007a46c0, 0xa})
           /root/project/hugo/create/content.go:268 +0x354
   github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0xc00047c180)
           /root/project/hugo/create/content.go:237 +0x1ad
   github.com/gohugoio/hugo/create.NewContent.func1()
           /root/project/hugo/create/content.go:100 +0x297
   github.com/gohugoio/hugo/create.NewContent(0xc000465760, {0x0, 0x0}, {0x7ffd5d2ec085, 0x66f045})
           /root/project/hugo/create/content.go:104 +0x5f8
   github.com/gohugoio/hugo/commands.(*newCmd).newContent(0xc00049bbc0, 0xc0003a2000, {0xc000139d50, 0x1, 0x0})
           /root/project/hugo/commands/new.go:83 +0x150
   github.com/spf13/cobra.(*Command).execute(0xc0003a2000, {0xc000139d20, 0x1, 0x1})
           /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
   github.com/spf13/cobra.(*Command).ExecuteC(0xc0006e8780)
           /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
   github.com/gohugoio/hugo/commands.Execute({0xc00003c0a0, 0x2, 0x2})
           /root/project/hugo/commands/hugo.go:92 +0xb4
   main.main()
           /root/project/hugo/main.go:23 +0x58
   ```

## The relevent config:

From:

https://github.com/danielfdickinson/hugo-mounted-content-subdir-bug-0-89/blob/dce95ec1364dac9851d1f2910bb2cdce3f3130c5/config.toml#L62

to the end of that file.

```toml
[module]

  [[module.mounts]]
    source = 'content'
    target = 'content'

  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'
  [[module.mounts]]
    source = 'data'
    target = 'data'

  [[module.mounts]]
    source = 'assets'
    target = 'assets'

  [[module.mounts]]
    source = 'i18n'
    target = 'i18n'

  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'

  [[module.imports]]
    ignoreConfig = true
    ignoreMounts = true
    path = "github.com/danielfdickinson/hugo-debug-tables"

    [[module.imports.mounts]]
      source = "static"
      target = "static"

    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "data"
      target = "data"

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/README-debug-tables.md"

    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"

  [[module.imports]]
    path = "github.com/danielfdickinson/hugo-minimal-test"

    [[module.imports.mounts]]
      source = "static"
      target = "static"

    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "data"
      target = "data"

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"

  [[module.imports]]
    path = "github.com/danielfdickinson/netlify-new-oldnew-mashup/exampleSite"
    ignoreConfig = true
    ignoreImports = true

    [[module.imports.mounts]]
      source = "content/docs"
      target = "content/test-docs"
```
