### ISSUE TITLE
Unexpected behavior when pulling in multiple Hugo modules with similar content

### ISSUE THREAD

**Issue by nathlaroche** [gohugoio/hugo#9173]
### What version of Hugo are you using (`hugo version`)?

hugo v0.89.2-63E3A5EB+extended linux/amd64 BuildDate=2021-11-08T15:22:24Z VendorInfo=gohugoio
(same issue seen when building on Windows)

### Does this issue reproduce with the latest release?

Yes

### Issue description

We are trying to implement the following use case using Hugo modules. We need to document microservices as standalone products and we also need to combine these microservices into another product. We were hoping to use Hugo modules to implement this scenario (we've been using Hugo modules in other situations and think they're amazing!). 

Here's our scenario (only showing content folders here for simplicity):

Git repo 1: Hugo module microservice 1
├── content
│  ├──overview
│  ├──installation
│  ├──configuration

Git repo 2: Hugo module microservice 2
├── content
│  ├──overview
│  ├──installation
│  ├──deployment

Git repo 3: Product A
├── content
│  ├──product_overview
│  ├── microservice1
│  │  ... (_content pulled in from Hugo module_)
│  ├── microservice2
│  │  ... (_content pulled in from Hugo module_)

Our module.toml file for Product A looks something like this:

```
[[imports]]
      path = "github.com/company_repo/microservice1"
      disabled = false
      
      [[imports.mounts]]
           source = "content/installation"
           target = "content/microservice1/installation"

      [[imports.mounts]]
           source = "content/configuration"
           target = "content/microservice1/configuration"

      [[imports.mounts]]
           source = "content/overview"
           target = "content/microservice1/overview"

[[imports]]
      path = "github.com/company_repo/microservice2"
      disabled = false
      
      [[imports.mounts]]
           source = "content/installation"
           target = "content/microservice2/installation"

      [[imports.mounts]]
           source = "content/deployment"
           target = "content/microservice2/deployment"

      [[imports.mounts]]
           source = "content/overview"
           target = "content/microservice2/overview"
```

The issue we are seeing is that, when pulling in the microservice modules, if more than one `imports.mounts source` has the same name (for example, `source = "content/installation"` is available in both microservice1 and microservice 2), only one instance is imported. So the actual output looks something like this:

Product A doc:
├── content
│  ├──product_overview
│  ├── microservice1
│  │  ├──installation
│  │  ├──configuration
│  │  ├──overview
│  ├── microservice2
│  │  ├──deployment

If I import only one module, then the Product A documentation generates correctly, importing the microservice documentation successfully. But if I add another module in my module.toml file, then only one source gets imported.

It seems to be the same issue reported [here](https://github.com/wowchemy/wowchemy-hugo-themes/issues/1933).

Am I doing something incorrectly, or is there a limitation with Hugo modules that the source name must be unique for all modules? We love Hugo modules and think they would be ideal in this case. But perhaps there is something else you would suggest for this scenario?

Thank you!

**Comment by nathlaroche** [comment]
Update: We've been able to make this work using the (great!) new includeFiles configuration parameter. Our module.toml file now looks something like this:

```toml
[[imports]]
      path = "github.com/company_repo/microservice1"
      disabled = false
      
	[[imports.mounts]]
		source = "content"
		target = "content/microservice1"
		includeFiles = ['configuration/**', 'installation/**', 'overview/**']


[[imports]]
      path = "github.com/company_repo/microservice2"
      disabled = false

	[[imports.mounts]]
		source = "content"
		target = "content/microservice2"
		includeFiles = ['configuration/**', 'deployment/**', 'overview/**']
```
And this works like a charm. 

It's not clear to me why our original approach did not work, though, Maybe I'm not understanding mounts correctly?  Any information on how they work would be very much appreciated! :)
