### ISSUE TITLE
combine menus in modules and site

### ISSUE THREAD

**Issue by davidejones** [gohugoio/hugo#9219]
I have a hugo module where the config file contains menu data. e.g

```
Params:
	hugo: "Rocks"

menu:
    main_menu:
        - identifier: 'product'
          name: 'Product'
          url: 'https://www.somewherecool.com/product/'
          weight: 1
```

The purpose of having the menu in the module is so we can make a menu change in one place and it update on all our sites. This works great.

However on one of the consuming sites I now need to define another menu that is specific to that site.  e.g

```
menu:
    side_menu:
        - identifier: 'side_menu_item1'
          name: 'Side Menu Item'
          url: 'https://www.something-side-menu.com/'
          weight: 1

```

So I'm intending to have the `side_menu` coming from my hugo site and the `main_menu` coming from the module.
However when i do this I only have the `side_menu` in my site i loose the `main_menu`. Its one or the other.

**PROPOSAL**
To address this I'm proposing a couple of options:

1. when defining a menu in a hugo module config it merges with the menu in the consuming site. So in my example above you would end up with both side_menu and main_menu existing. I believe Params already works this way today.

**OR**

2. adding a new mount target beyond `[archetypes assets content data i18n layouts static]` to include menus?
