### ISSUE TITLE
Build cache is required, but could not be located

### ISSUE THREAD

**Issue by chengjun** [gohugoio/hugo#9309]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version 

</pre>

0.91.0

```
Run peaceiris/actions-hugo@v2
Hugo version: 0.91.0
/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/actions_hugo/_temp -f /home/runner/work/_temp/f496a467-32a5-47a2-81a4-8b300f6e61b7
/home/runner/actions_hugo/bin/hugo version
hugo v0.91.0-D1DC0E9A+extended linux/amd64 BuildDate=2021-12-17T09:50:20Z VendorInfo=gohugoio
```
### Does this issue reproduce with the latest release?

I guess yes!

https://github.com/chengjun/starter-hugo-academic/runs/4603137806?check_suite_focus=true

```
Run hugo --gc --minify
build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
Error: failed to download modules: failed to execute 'go [mod download]': failed to execute binary "go" with args [mod download]: build cache is required, but could not be located: GOCACHE is not defined and neither $XDG_CACHE_HOME nor $HOME are defined
 *errors.errorString
hugo: collected modules in 897 ms
Total in 898 ms
Error: Process completed with exit code 255.
```

I run `hugo` within **github action**:

```
name: Deploy to chengjun.github.io
on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true 

      - name: Build
        run: hugo --gc --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: chengjun/chengjun.github.io
          publish_branch: main  # default: gh-pages
          publish_dir: ./public
```

## Update

When I downgrade the version to 0.90.0, it works well. I guess it is the problem of the new version.
