### ISSUE TITLE
Module mounts with identical sources are not recursively copied to targets

### ISSUE THREAD

**Issue by robbymilo** [gohugoio/hugo#9426]
### What version of Hugo are you using (`hugo version`)?

<pre>
hugo v0.92.0-B3549403+extended linux/amd64 BuildDate=2022-01-12T08:23:18Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

**What happened:**
Added three (3) module mounts - two (2) have the same source, but different targets. In config.toml for example: 

```toml
[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "extra-content"
target = "content/resources-a"

[[module.mounts]]
source = "extra-content"
target = "content/resources-b"
```

Note the `extra-content` dir contains subdirs, and the resulting `public` output:

![Screenshot from 2022-01-26 16-02-15](https://user-images.githubusercontent.com/8106669/151188120-63ded5e0-39b1-434b-bbaa-9dfbc404b127.png)

**What I expected to happened:**
`public/resources-b` would also contain `extra-content/subdir`.

---

To reproduce with 0.92.0:
```shell
git clone git@github.com:robbymilo/hugo-bug.git
cd hugo-bug && git chceckout module-mounts
hugo
ls -Ral public/resources*
```

You will see the difference between 
`public/resources-a` and 
`public/resources-b`. 

`public/resources-a` contains the subdirs for `extra-content`, while `public/resources-b` does not.
