### ISSUE TITLE
Exclude event attributes when rendering markdown

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9463]
### Current Behavior

config.toml

```toml
[markup.goldmark.renderer]
unsafe = false

[markup.goldmark.parser.attribute]
block = true
title = true
```

markdown

````md
## Heading {onclick="alert('heading')"}

> Blockquote
{ondblclick="alert('blockquote')"}

```bash {onmouseover="alert('code fence')"}
codefences
```
````

renders

```html
<h2 onclick="alert('heading')" id="heading">Heading</h2>

<blockquote><p>Blockquote</p></blockquote>

<div class="highlight" onmouseover="alert('code fence')">...
```

### Desired Behavior

Remove attribute events from headings and code fences. The block attributes are already being sanitized.

```html
<h2 id="heading">Heading</h2>

<blockquote><p>Blockquote</p></blockquote>

<div class="highlight">...
```

Reference:
- <https://discourse.gohugo.io/t/35150/6>
- <https://discourse.gohugo.io/t/35069/4>

Testing:

```bash
git clone --single-branch -b hugo-github-issue-9463 https://github.com/jmooring/hugo-testing hugo-github-issue-9463
cd hugo-github-issue-9463
hugo server
```
