### ISSUE TITLE
Module replacements not able to resolve nested modules

### ISSUE THREAD

**Issue by UtkarshVerma** [gohugoio/hugo#9494]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
Yes

### The issue
I have the following in my `config.yaml`.
```yaml
module:
  replacements:
    - github.com/UtkarshVerma/hugo-yoru -> ../../hugo-yoru
  imports:
    - path: github.com/UtkarshVerma/hugo-yoru
```

Now, the `hugo-yoru` module depends on FontAwesome. When I run Hugo server, I get the following error:
```
Error: module "github.com/FortAwesome/Font-Awesome" not found; either add it as a Hugo Module or store it in "/home/subaru/GitHub/bitbanged.com/themes".: module does not exist
```

Thanks in advance.
