### ISSUE TITLE
Hugo generates inexistent TOC items when there are skipped heading levels

### ISSUE THREAD

**Issue by refparo** [gohugoio/hugo#9498]
For example:

```markdown
# H1

...main content...

> ### H3
>
> (some extra content inside blockquote)
```

with config:

```yaml
markup:
  tableOfContents:
    startLevel: 1
    endLevel: 2 # So H3 should not render
```

yields this TOC:

- H1
  - (an empty item)

The empty item isn't expected.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?

Yes.
