### ISSUE TITLE
Change default value markup.highlight.lineNumbersInTable to false

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9596]
With v0.92.2 and earlier, with `lineNos=true`, the only way to produce a selectable block of code was to set `lineNumbersInTable=true`, so it was a sensible default.

With v0.93.0 and later, `lineNos=true` plus `lineNumbersInTable=false` produces a selectable block of code. It is no longer necessary to set `lineNumbersInTable=true`. This new and desirable behavior was introduced with https://github.com/gohugoio/hugo/commit/ea54a99ca5c4ed9e66574553f6c057fb83d0aca3.

Is the current default causing any problems?
- In the absence of any external styling, no. However, the additional markup is not required.
- With external styling, sometimes.

I ran into this with a Bootstrap 5 implementation, where `_reboot.scss` was setting:

```css
pre,
code,
kbd,
samp {
  font-family: $font-family-code;
  @include font-size(1em); // Correct the odd `em` font sizing in all browsers.
  direction: ltr #{"/* rtl:ignore */"};
  unicode-bidi: bidi-override;
}
```

Producing this:

<img src="https://user-images.githubusercontent.com/335669/156470907-0ebff135-5fd7-497e-92ec-dfbb1ae0a36d.png" width="50%" alt="screen capture">

The bidirectional rules have been [removed](https://github.com/twbs/bootstrap/commit/989de20baed8a578fe825649c5b819238887f83c) in HEAD, but anyone using a production release will run into this problem.

Example:

```bash
git clone --single-branch -b hugo-github-issue-9596 https://github.com/jmooring/hugo-testing hugo-github-issue-9596
cd hugo-github-issue-9596
hugo server
```

Follow up....

Even when using Bootstrap 5 at HEAD, setting `lineNumbersInTable=true` still produces undesirable results (space after final line of code):

<img src="https://user-images.githubusercontent.com/335669/156475461-2ea5e97a-0c7c-44a8-86dc-8114e3156698.png" width="50%" alt="another screen capture">
