### ISSUE TITLE
Goldmark regression: HTML comments in markdown are not rendered as HTML comments

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9650]
Reference: <https://discourse.gohugo.io/t/inline-html-comments-not-being-recognized-in-markdown-files/37598>

config

```toml
[markup.goldmark.renderer]
unsafe = true
```

markdown

```html
a <!-- b --> c
```

result

```html
<p>a &lt;!-- b --&gt; c</p>
```
Upstream: <https://github.com/yuin/goldmark/issues/285>
