### ISSUE TITLE
Javascript minification renames variables incorrectly

### ISSUE THREAD

**Issue by ShaneMcC** [gohugoio/hugo#9713]
Since 0.93.0 javascript minification in hugo sometimes ends up renaming variables incorrectly causing unexpected errors with some libraries.

This looks to be a bug with upstream: https://github.com/tdewolff/minify/issues/469

Disabling variable renaming in `config.toml` fixes the problem:

```toml
[minify]
  [minify.tdewolff]
    [minify.tdewolff.js]
      keepVarNames = true
```

This may be something worth doing by default until upstream fixes their bug. (Similar to how https://github.com/gohugoio/hugo/issues/8759 was handled)

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.95.0-9F2E76AF+extended linux/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes
