### ISSUE TITLE
Allow permalinks configuration syntax to `url` Front Matter.

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#9714]
### Currently

Currently, batch permalink settings can only happen through the site's config's `permalinks` object. For every setting, it takes a content directory as key and a string that can include "template strings" syntax as value.

To set the permalink of the `/recipe` directory using the slug:

```yaml
permalinks:
  recipe: /delicious-recipe/:slug
```

That is limiting to batch editing content files of a root directory. The recent `:sections` templates brought more power to the desired permalink but did not fully resolve the limited "targeting" of the batch. For example, if your content files are in a subdirectory `content/cooking/recipe`, you would have no way (at least I did not find one) to target the files in the directory to batch assign a permalink structure.

### The proposal

Allow the `url` Front Matter key to use the same syntax as permalink's configuration.

```yaml
---
# content/cooking/recipe/_index.md
title: Delicious Recipes
url: /delicious-recipe
cascade:
  url: /delicious-recipe/:slug
---
```
