### ISSUE TITLE
Starting with Hugo v0.96.0 md5 differs at every deploy without any change in files, and all the files are uploaded to S3

### ISSUE THREAD

**Issue by lupsa** [gohugoio/hugo#9729]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended darwin/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes (v0.96)
No (v0.95)

```toml
[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "main"
URL = "s3://abc.com?region=eu-north-1"
cloudFrontDistributionID = "abc"

[[deployment.matchers]]
pattern = "^.*\\.(js|css|svg|ttf|woff2|woff)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.*\\.(png|jpg|jpeg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^sitemap\\.xml$"
contentType = "application/xml"
gzip = true

[[deployment.matchers]]
pattern = "^.*\\.(html|xml|json)$"
gzip = true

```
