### ISSUE TITLE
hugo --minify loses some spaces

### ISSUE THREAD

**Issue by knutov** [gohugoio/hugo#9801]
`hugo v0.97.3+extended linux/amd64 BuildDate=unknown`
installed from `brew`

with `hugo --minify` some spaces between words are missing. 

There was all ok couple monthes ago with 0.92 I suppose (but not sure)

from `config.yaml`:

```
minify:
  tdewolff:
    html:
      keepDocumentTags: true
      keepQuotes: true
```

source code (with bulma css framework):

```
<span class="has-text-grey">some text</span>
<div class="is-hidden-tablet"> </div>
<span class="has-text-grey">other words</span>
```

The space on second line supposed to be visible on desktop and this string is making new line on mobile screen.

I have to add `keepWhitespace: true` to the config but it keeps too much for me.

Is there a better solution?
