### ISSUE TITLE
Add custom external optimizer for files per extention

### ISSUE THREAD

**Issue by knutov** [gohugoio/hugo#9802]
As continue of https://discourse.gohugo.io/t/optimize-svg-from-asstets-with-svgo/37122

It would be great to have the way to setup external optimizer (like a shell script) to optimize files which Hugo does not support.

Example - optimize .svg assets with svgo. 

I think we can have config structure like:
```
...
optimize:
  svg: svgo --multipass ${SRC:?} -o ${DST:?}
  png: cp $SRC $DST && pngquant --speed 1 --ext .png --force --strip $DST
```

Or may be there is already a solution for this?
